package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class AnalyticsActivity extends Activity{
 private ExpenseDb db;private LinearLayout content;private int BG,CARD,TEXT,MUTED,ACCENT;private final DecimalFormat money=new DecimalFormat("#,##0.00");private Calendar selected=Calendar.getInstance(),compareA=Calendar.getInstance(),compareB=Calendar.getInstance();private boolean annual=false;private Button periodBtn;private String active="cat";
 static class Item{String name;double value;int color;Item(String n,double v,int c){name=n;value=v;color=c;}}
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new ExpenseDb(this);DetectionRules.reclassifyExisting(this);compareB.add(Calendar.MONTH,-1);initPalette();build();showCategory();}
 @Override protected void onResume(){super.onResume();renderActive();}
 private void initPalette(){boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);ACCENT=Color.rgb(255,193,7);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(8),dp(6),dp(8),dp(6));return v;}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,12));return b;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(0,i.getSystemWindowInsetTop()+dp(22),0,i.getSystemWindowInsetBottom());return i;});root.requestApplyInsets();LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(12),dp(8),dp(12),dp(4));Button back=btn("‹");back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView t=tv("Gráficos y análisis",24,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);titles.addView(t);titles.addView(tv("Visualizá, compará y editá categorías",13,MUTED));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));Button edit=btn("Categorías");edit.setOnClickListener(v->startActivity(new Intent(this,CategorySettingsActivity.class)));head.addView(edit,new LinearLayout.LayoutParams(dp(105),dp(46)));root.addView(head);
  LinearLayout controls=new LinearLayout(this);controls.setPadding(dp(12),dp(4),dp(12),dp(4));periodBtn=btn(periodLabel());periodBtn.setOnClickListener(v->choosePeriod());Button mode=btn("Mes / Año");mode.setOnClickListener(v->{annual=!annual;periodBtn.setText(periodLabel());renderActive();});controls.addView(periodBtn,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(105),dp(46));mp.setMargins(dp(8),0,0,0);controls.addView(mode,mp);root.addView(controls);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(10),dp(4),dp(10),dp(8));Button cat=btn("Categorías"),mer=btn("Comercios"),evo=btn("Evolución"),cmp=btn("Comparar");for(Button b:new Button[]{cat,mer,evo,cmp}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(118),dp(46));p.setMargins(dp(3),0,dp(3),0);tabs.addView(b,p);}cat.setOnClickListener(v->{active="cat";showCategory();});mer.setOnClickListener(v->{active="mer";showMerchant();});evo.setOnClickListener(v->{active="evo";showEvolution();});cmp.setOnClickListener(v->{active="cmp";showCompare();});hs.addView(tabs);root.addView(hs);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(4),dp(12),dp(22));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private String periodLabel(){SimpleDateFormat f=new SimpleDateFormat(annual?"yyyy":"MMMM yyyy",new Locale("es","UY"));String s=f.format(selected.getTime());return s.substring(0,1).toUpperCase()+s.substring(1);}
 private void choosePeriod(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{selected.set(y,m,1);periodBtn.setText(periodLabel());renderActive();},selected.get(Calendar.YEAR),selected.get(Calendar.MONTH),1);d.setTitle(annual?"Elegí año":"Elegí mes");d.show();}
 private void renderActive(){if(content==null)return;if("mer".equals(active))showMerchant();else if("evo".equals(active))showEvolution();else if("cmp".equals(active))showCompare();else showCategory();}
 private void clear(String title,String sub){content.removeAllViews();TextView h=tv(title,22,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv(sub,14,MUTED));}
 private ArrayList<Object[]> rowsFor(Calendar base,boolean year){Calendar a=(Calendar)base.clone();a.set(Calendar.DAY_OF_MONTH,1);a.set(Calendar.HOUR_OF_DAY,0);a.set(Calendar.MINUTE,0);a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);if(year){a.set(Calendar.MONTH,Calendar.JANUARY);}Calendar b=(Calendar)a.clone();b.add(year?Calendar.YEAR:Calendar.MONTH,1);Cursor c=db.getReadableDatabase().rawQuery("SELECT type,amount,currency,category,description,ts FROM tx WHERE ts>=? AND ts<? ORDER BY ts",new String[]{String.valueOf(a.getTimeInMillis()),String.valueOf(b.getTimeInMillis())});ArrayList<Object[]> r=new ArrayList<>();while(c.moveToNext())r.add(new Object[]{c.getString(0),c.getDouble(1),c.getString(2),c.getString(3),c.getString(4),c.getLong(5)});c.close();return r;}
 private LinkedHashMap<String,Double> categoryMap(Calendar p,boolean year){HashMap<String,Double> m=new HashMap<>();for(Object[]r:rowsFor(p,year)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;String k=categoryKey((String)r[3],(String)r[4]);m.put(k,m.getOrDefault(k,0.0)+(Double)r[1]);}return sort(m);}private LinkedHashMap<String,Double> merchantMap(Calendar p,boolean year){HashMap<String,Double> m=new HashMap<>();for(Object[]r:rowsFor(p,year)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;String k=merchantKey((String)r[4]);m.put(k,m.getOrDefault(k,0.0)+(Double)r[1]);}return sort(m);}private LinkedHashMap<String,Double> sort(Map<String,Double>in){ArrayList<Map.Entry<String,Double>>a=new ArrayList<>(in.entrySet());a.sort((x,y)->Double.compare(y.getValue(),x.getValue()));LinkedHashMap<String,Double>o=new LinkedHashMap<>();for(Map.Entry<String,Double>e:a)o.put(e.getKey(),e.getValue());return o;}
 private void showCategory(){active="cat";clear("Gastos por categoría",annual?"Distribución del año seleccionado":"Distribución del mes seleccionado");LinkedHashMap<String,Double>m=categoryMap(selected,annual);ArrayList<Item>items=new ArrayList<>();double total=0;for(Map.Entry<String,Double>e:m.entrySet()){items.add(new Item(e.getKey(),e.getValue(),CategoryPrefs.color(this,e.getKey())));total+=e.getValue();}addTotal(total);if(!items.isEmpty()){DonutView v=new DonutView(this,items,total);content.addView(v,new LinearLayout.LayoutParams(-1,dp(265)));}for(Item i:items)addRank(i,total,true);if(items.isEmpty())content.addView(tv("No hay gastos para este período.",15,MUTED));}
 private void showMerchant(){active="mer";clear("Gastos por comercio",annual?"Top comercios del año":"Top comercios del mes");LinkedHashMap<String,Double>m=merchantMap(selected,annual);ArrayList<Item>items=new ArrayList<>();double total=0;int ix=0;for(Map.Entry<String,Double>e:m.entrySet()){if(ix>=12)break;int c=CategoryPrefs.PALETTE[ix%CategoryPrefs.PALETTE.length];items.add(new Item(e.getKey(),e.getValue(),c));total+=e.getValue();ix++;}addTotal(total);if(!items.isEmpty()){BarsView v=new BarsView(this,items);content.addView(v,new LinearLayout.LayoutParams(-1,dp(Math.max(210,items.size()*36+45))));}for(Item i:items)addRank(i,total,false);}
 private void showEvolution(){active="evo";clear("Evolución","Últimos 12 meses hasta el período seleccionado");ArrayList<Item>months=new ArrayList<>();Calendar c=(Calendar)selected.clone();c.add(Calendar.MONTH,-11);for(int i=0;i<12;i++){double sum=0;for(Object[]r:rowsFor(c,false))if("GASTO".equals(r[0])&&"UYU".equals(r[2]))sum+=(Double)r[1];String n=new SimpleDateFormat("MMM",new Locale("es","UY")).format(c.getTime());months.add(new Item(n,sum,ACCENT));c.add(Calendar.MONTH,1);}LineView v=new LineView(this,months);content.addView(v,new LinearLayout.LayoutParams(-1,dp(280)));content.addView(tv("La línea usa el gasto total mensual. Elegí otro mes arriba para mover la ventana de 12 meses.",14,MUTED));}
 private void showCompare(){active="cmp";clear("Comparar meses","Elegí dos meses diferentes y compará total y categorías");LinearLayout pick=new LinearLayout(this);Button a=btn(monthName(compareA)),b=btn(monthName(compareB));a.setOnClickListener(v->pickCompare(compareA,true));b.setOnClickListener(v->pickCompare(compareB,false));pick.addView(a,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(46),1);bp.setMargins(dp(8),0,0,0);pick.addView(b,bp);content.addView(pick);LinkedHashMap<String,Double>ma=categoryMap(compareA,false),mb=categoryMap(compareB,false);double ta=sum(ma),tb=sum(mb);TextView h=tv(monthName(compareA)+": $ "+money.format(ta)+"\n"+monthName(compareB)+": $ "+money.format(tb)+"\nDiferencia: "+(ta-tb>=0?"+":"")+"$ "+money.format(ta-tb),18,ta>tb?Color.rgb(230,90,90):Color.rgb(70,190,120));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setBackground(bg(CARD,14));h.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.setMargins(0,dp(10),0,dp(8));content.addView(h,hp);LinkedHashSet<String>keys=new LinkedHashSet<>();keys.addAll(ma.keySet());keys.addAll(mb.keySet());CompareView cv=new CompareView(this,new ArrayList<>(keys),ma,mb);content.addView(cv,new LinearLayout.LayoutParams(-1,dp(Math.max(220,keys.size()*42+55))));}
 private void pickCompare(Calendar target,boolean first){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{target.set(y,m,1);showCompare();},target.get(Calendar.YEAR),target.get(Calendar.MONTH),1);d.setTitle(first?"Primer mes":"Segundo mes");d.show();}
 private String monthName(Calendar c){String s=new SimpleDateFormat("MMM yyyy",new Locale("es","UY")).format(c.getTime());return s.substring(0,1).toUpperCase()+s.substring(1);}private double sum(Map<String,Double>m){double x=0;for(double v:m.values())x+=v;return x;}
 private void addTotal(double total){TextView t=tv((annual?"Total del año":"Total del período")+"\n$ "+money.format(total),22,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setBackground(bg(CARD,14));t.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(8));content.addView(t,p);}
 private void addRank(Item i,double total,boolean cat){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(9),dp(7),dp(9),dp(7));r.setBackground(bg(CARD,11));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,0,0,dp(5));r.setLayoutParams(rp);View dot=new View(this);dot.setBackground(bg(i.color,100));r.addView(dot,new LinearLayout.LayoutParams(dp(18),dp(18)));TextView n=tv(i.name,15,TEXT);r.addView(n,new LinearLayout.LayoutParams(0,-2,1));double pct=total==0?0:i.value/total*100;TextView val=tv("$ "+money.format(i.value)+" · "+new DecimalFormat("0.0").format(pct)+"%",14,TEXT);r.addView(val);if(cat)r.setOnClickListener(v->showCategoryDetail(i.name));else r.setOnClickListener(v->showMerchantDetail(i.name));content.addView(r);}
 private void showCategoryDetail(String category){
  LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(4),dp(8),dp(8));ScrollView sc=new ScrollView(this);LinearLayout rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);sc.addView(rows);box.addView(tv("Tocá un movimiento para cambiar su categoría. El cambio también actualiza/aprende la regla correspondiente en la lista blanca.",13,MUTED));box.addView(sc,new LinearLayout.LayoutParams(-1,dp(430)));
  Calendar a=(Calendar)selected.clone();a.set(Calendar.DAY_OF_MONTH,1);a.set(Calendar.HOUR_OF_DAY,0);a.set(Calendar.MINUTE,0);a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);if(annual)a.set(Calendar.MONTH,Calendar.JANUARY);Calendar b=(Calendar)a.clone();b.add(annual?Calendar.YEAR:Calendar.MONTH,1);
  Cursor c=db.getReadableDatabase().rawQuery("SELECT id,amount,currency,category,description,ts FROM tx WHERE type='GASTO' AND ts>=? AND ts<? ORDER BY ts DESC",new String[]{String.valueOf(a.getTimeInMillis()),String.valueOf(b.getTimeInMillis())});int count=0;SimpleDateFormat df=new SimpleDateFormat("dd/MM",Locale.US);
  while(c.moveToNext()){long id=c.getLong(0);double amount=c.getDouble(1);String cur=c.getString(2),cat=c.getString(3),desc=c.getString(4);long ts=c.getLong(5);if(!category.equals(categoryKey(cat,desc)))continue;count++;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(10),dp(8),dp(10),dp(8));row.setBackground(bg(CARD,10));TextView name=tv((desc==null?"Sin descripción":desc)+"   "+("USD".equals(cur)?"USD ":"$ ")+money.format(amount),14,TEXT);row.addView(name);row.addView(tv(df.format(new Date(ts))+" · Categoría: "+(cat==null?"Otros":cat),12,MUTED));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,0,0,dp(5));rows.addView(row,rp);final long fid=id;final String fcat=cat;row.setOnClickListener(v->showCategoryPicker(fid,fcat,category));}
  c.close();if(count==0)rows.addView(tv("No hay movimientos en esta categoría.",14,MUTED));AlertDialog dlg=new AlertDialog.Builder(this).setTitle(category).setView(box).setNegativeButton("Cerrar",null).create();dlg.show();
 }
 private void showCategoryPicker(long id,String current,String reopenCategory){ArrayList<String> cats=new ArrayList<>(DetectionRules.categoryNames(this));if(current!=null&&!current.trim().isEmpty()&&!cats.contains(current.trim()))cats.add(0,current.trim());cats.add("＋ Nueva categoría…");String[] arr=cats.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Cambiar categoría").setItems(arr,(d,w)->{if(w==arr.length-1){EditText e=new EditText(this);e.setHint("Nueva categoría");new AlertDialog.Builder(this).setTitle("Nueva categoría").setView(e).setPositiveButton("Guardar",(x,y)->{String nc=e.getText().toString().trim();if(!nc.isEmpty()){DetectionRules.assignMovementCategory(this,id,nc);showCategory();}}).setNegativeButton("Cancelar",null).show();}else{DetectionRules.assignMovementCategory(this,id,arr[w]);showCategory();}}).setNegativeButton("Cancelar",null).show();}
 private void showMerchantDetail(String merchant){StringBuilder b=new StringBuilder();double total=0;int n=0;SimpleDateFormat df=new SimpleDateFormat("dd/MM HH:mm",Locale.US);for(Object[]r:rowsFor(selected,annual)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2])||!merchant.equals(merchantKey((String)r[4])))continue;double a=(Double)r[1];total+=a;n++;b.append(df.format(new Date((Long)r[5]))).append("   $ ").append(money.format(a)).append("\n");}new AlertDialog.Builder(this).setTitle(merchant+" · $ "+money.format(total)).setMessage("Compras: "+n+"\n\n"+b).setPositiveButton("Cerrar",null).show();}
 private String categoryKey(String cat,String desc){String c=cat==null?"":cat.trim();for(String allowed:DetectionRules.categoryNames(this))if(allowed.equalsIgnoreCase(c))return allowed;return DetectionRules.categoryFor(this,desc,"Otros");}
 private String merchantKey(String desc){String s=norm(desc);if(has(s,"disco"))return"Disco";if(has(s,"devoto"))return"Devoto";if(has(s,"geant"))return"Géant";if(has(s,"tienda inglesa"))return"Tienda Inglesa";if(has(s,"tata","ta-ta"))return"Ta-Ta";if(has(s,"ancap"))return"ANCAP";if(has(s,"axion"))return"Axion";if(has(s,"pedidos ya","pedidosya"))return"PedidosYa";if(has(s,"farmashop"))return"Farmashop";if(has(s,"ute"))return"UTE";if(has(s,"antel"))return"Antel";if(has(s,"netflix"))return"Netflix";if(has(s,"google"))return"Google";if(s.isEmpty())return"Sin comercio";String cleaned=s.replaceAll("\\b(nro|nº|no|suc|sucursal|local)\\b"," ").replaceAll("\\d+"," ").replaceAll("[^a-záéíóúñ ]"," ").replaceAll("\\s+"," ").trim();if(cleaned.isEmpty())cleaned=s;String[]p=cleaned.split(" ");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(p.length,3);i++){if(i>0)b.append(' ');b.append(p[i].substring(0,1).toUpperCase()).append(p[i].substring(1));}return b.toString();}private String norm(String x){if(x==null)return"";return java.text.Normalizer.normalize(x,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();}private boolean has(String s,String...x){for(String v:x)if(s.contains(v))return true;return false;}
 class DonutView extends View{ArrayList<Item>a;double total;Paint p=new Paint(1);DonutView(Context c,ArrayList<Item>x,double t){super(c);a=x;total=t;}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),sz=Math.min(w*.50f,h*.72f),l=dp(12),top=(h-sz)/2;RectF r=new RectF(l,top,l+sz,top+sz);float st=-90;for(Item i:a){float sw=(float)(360*i.value/Math.max(1,total));p.setColor(i.color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(sz*.22f);c.drawArc(r,st,sw,false,p);st+=sw;}p.setStyle(Paint.Style.FILL);p.setColor(TEXT);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(dp(14));c.drawText("Total",r.centerX(),r.centerY()-dp(6),p);p.setTextSize(dp(18));p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("$ "+money.format(total),r.centerX(),r.centerY()+dp(18),p);p.setTypeface(null);float x=l+sz+dp(42),y=top+dp(14);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(dp(12));for(int j=0;j<Math.min(a.size(),8);j++){Item i=a.get(j);p.setColor(i.color);c.drawCircle(x,y,dp(5),p);p.setColor(TEXT);c.drawText(i.name,x+dp(12),y+dp(4),p);y+=dp(25);}}}
 class BarsView extends View{ArrayList<Item>a;Paint p=new Paint(1);BarsView(Context c,ArrayList<Item>x){super(c);a=x;}protected void onDraw(Canvas c){super.onDraw(c);double max=1;for(Item i:a)max=Math.max(max,i.value);float y=dp(18);p.setTextSize(dp(12));for(Item i:a){p.setColor(TEXT);c.drawText(i.name,dp(8),y+dp(13),p);float x=dp(115),ww=(getWidth()-dp(205))*(float)(i.value/max);p.setColor(Color.argb(45,150,150,150));c.drawRoundRect(x,y,x+getWidth()-dp(205),y+dp(15),dp(7),dp(7),p);p.setColor(i.color);c.drawRoundRect(x,y,x+ww,y+dp(15),dp(7),dp(7),p);p.setColor(TEXT);c.drawText("$ "+money.format(i.value),getWidth()-dp(82),y+dp(13),p);y+=dp(36);}}}
 class LineView extends View{ArrayList<Item>a;Paint p=new Paint(1);LineView(Context c,ArrayList<Item>x){super(c);a=x;}protected void onDraw(Canvas c){super.onDraw(c);float L=dp(38),T=dp(24),R=getWidth()-dp(12),B=getHeight()-dp(35);double max=1;for(Item i:a)max=Math.max(max,i.value);p.setColor(MUTED);p.setStrokeWidth(dp(1));for(int j=0;j<=4;j++){float y=T+(B-T)*j/4;c.drawLine(L,y,R,y,p);}p.setColor(ACCENT);p.setStrokeWidth(dp(3));float px=0,py=0;for(int i=0;i<a.size();i++){float x=L+(R-L)*i/(a.size()-1f),y=B-(B-T)*(float)(a.get(i).value/max);if(i>0)c.drawLine(px,py,x,y,p);c.drawCircle(x,y,dp(4),p);p.setColor(TEXT);p.setTextSize(dp(10));p.setTextAlign(Paint.Align.CENTER);c.drawText(a.get(i).name,x,B+dp(18),p);p.setColor(ACCENT);px=x;py=y;}p.setTextAlign(Paint.Align.LEFT);}}
 class CompareView extends View{ArrayList<String>keys;Map<String,Double>a,b;Paint p=new Paint(1);CompareView(Context c,ArrayList<String>k,Map<String,Double>x,Map<String,Double>y){super(c);keys=k;a=x;b=y;}protected void onDraw(Canvas c){super.onDraw(c);double max=1;for(String k:keys)max=Math.max(max,Math.max(a.getOrDefault(k,0.0),b.getOrDefault(k,0.0)));float y=dp(18);p.setTextSize(dp(11));for(String k:keys){p.setColor(TEXT);c.drawText(k,dp(7),y+dp(13),p);float x=dp(105),W=getWidth()-dp(120),wa=W*(float)(a.getOrDefault(k,0.0)/max),wb=W*(float)(b.getOrDefault(k,0.0)/max);p.setColor(CategoryPrefs.color(AnalyticsActivity.this,k));c.drawRect(x,y,x+wa,y+dp(10),p);p.setColor(Color.rgb(120,140,160));c.drawRect(x,y+dp(13),x+wb,y+dp(23),p);y+=dp(42);}}}
}
