package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class AnalyticsActivity extends Activity{
 private ExpenseDb db;private LinearLayout content;private int BG,CARD,TEXT,MUTED,ACCENT;private Calendar selected=Calendar.getInstance();private boolean annual=false;private Button periodBtn;private String active="cat";private final DecimalFormat money=new DecimalFormat("#,##0.00");private SharedPreferences extras;
 static class Pt{String n;double v;Pt(String n,double v){this.n=n;this.v=v;}}
 static class Extra{String name;double amount;boolean income;Extra(String n,double a,boolean i){name=n;amount=a;income=i;}}
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new ExpenseDb(this);extras=getSharedPreferences("analytics_balance",0);palette();build();showCategory();}
 protected void onResume(){super.onResume();render();}
 private void palette(){boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);ACCENT=Color.rgb(255,193,7);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(8),dp(6),dp(8),dp(6));return v;}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,12));return b;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(0,i.getSystemWindowInsetTop()+dp(18),0,i.getSystemWindowInsetBottom());return i;});LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(12),dp(6),dp(12),dp(4));Button back=btn("‹");back.setOnClickListener(v->finish());h.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView title=tv("Gráficos y análisis",24,TEXT);title.setTypeface(null,Typeface.BOLD);titles.addView(title);titles.addView(tv("Visualizá, compará y editá categorías",13,MUTED));h.addView(titles,new LinearLayout.LayoutParams(0,-2,1));Button cats=btn("Categorías");cats.setOnClickListener(v->startActivity(new Intent(this,CategorySettingsActivity.class)));h.addView(cats,new LinearLayout.LayoutParams(dp(105),dp(46)));root.addView(h);
 LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(12),dp(4),dp(12),dp(4));Button prev=btn("‹"),next=btn("›"),mode=btn("Mes / Año");periodBtn=btn(periodLabel());prev.setOnClickListener(v->{selected.add(annual?Calendar.YEAR:Calendar.MONTH,-1);refreshPeriod();});next.setOnClickListener(v->{selected.add(annual?Calendar.YEAR:Calendar.MONTH,1);refreshPeriod();});mode.setOnClickListener(v->{annual=!annual;refreshPeriod();});periodBtn.setOnClickListener(v->pickPeriod());nav.addView(prev,new LinearLayout.LayoutParams(dp(44),dp(46)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(46),1);pp.setMargins(dp(5),0,dp(5),0);nav.addView(periodBtn,pp);nav.addView(next,new LinearLayout.LayoutParams(dp(44),dp(46)));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(96),dp(46));mp.setMargins(dp(6),0,0,0);nav.addView(mode,mp);root.addView(nav);
 HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(10),dp(4),dp(10),dp(8));Button cat=btn("Categorías"),sav=btn("Ahorro"),bal=btn("Balance"),cmp=btn("Comparar");for(Button b:new Button[]{cat,sav,bal,cmp}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(118),dp(46));p.setMargins(dp(3),0,dp(3),0);tabs.addView(b,p);}cat.setOnClickListener(v->{active="cat";showCategory();});sav.setOnClickListener(v->{active="sav";showSavings();});bal.setOnClickListener(v->{active="bal";showBalance();});cmp.setOnClickListener(v->{active="cmp";showCompare();});hs.addView(tabs);root.addView(hs);
 ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(4),dp(12),dp(22));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);root.requestApplyInsets();}
 private void refreshPeriod(){periodBtn.setText(periodLabel());render();}private void render(){if(content==null)return;if(active.equals("sav"))showSavings();else if(active.equals("bal"))showBalance();else if(active.equals("cmp"))showCompare();else showCategory();}
 private String periodLabel(){SimpleDateFormat f=new SimpleDateFormat(annual?"yyyy":"MMMM yyyy",new Locale("es","UY"));String s=f.format(selected.getTime());return s.substring(0,1).toUpperCase()+s.substring(1);}private String ym(Calendar c){return new SimpleDateFormat("yyyy-MM",Locale.US).format(c.getTime());}private String mn(Calendar c){return new SimpleDateFormat("MMM",new Locale("es","UY")).format(c.getTime());}
 private void pickPeriod(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{selected.set(y,m,1);refreshPeriod();},selected.get(Calendar.YEAR),selected.get(Calendar.MONTH),1);d.setTitle("Elegir período");d.show();}
 private void clear(String t,String s){content.removeAllViews();TextView h=tv(t,22,TEXT);h.setTypeface(null,Typeface.BOLD);content.addView(h);content.addView(tv(s,14,MUTED));}
 private double[] totals(Calendar c){Calendar a=(Calendar)c.clone();a.set(Calendar.DAY_OF_MONTH,1);a.set(Calendar.HOUR_OF_DAY,0);a.set(Calendar.MINUTE,0);a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);Calendar b=(Calendar)a.clone();b.add(Calendar.MONTH,1);Cursor q=db.getReadableDatabase().rawQuery("SELECT type,amount,currency FROM tx WHERE ts>=? AND ts<?",new String[]{""+a.getTimeInMillis(),""+b.getTimeInMillis()});double in=0,out=0;while(q.moveToNext()){if(!"UYU".equals(q.getString(2)))continue;if("INGRESO".equals(q.getString(0)))in+=q.getDouble(1);else if("GASTO".equals(q.getString(0)))out+=q.getDouble(1);}q.close();for(Extra e:loadExtras(c)){if(e.income)in+=e.amount;else out+=e.amount;}return new double[]{in,out};}
 private ArrayList<Extra> loadExtras(Calendar c){ArrayList<Extra> a=new ArrayList<>();String s=extras.getString("m_"+ym(c),"");if(s.isEmpty())return a;for(String row:s.split("\\n")){String[] p=row.split("\\|",3);if(p.length==3)try{a.add(new Extra(new String(android.util.Base64.decode(p[0],0)),Double.parseDouble(p[2]),"I".equals(p[1])));}catch(Exception ignored){}}return a;}
 private void saveExtras(Calendar c,ArrayList<Extra>a){StringBuilder s=new StringBuilder();for(Extra e:a){if(s.length()>0)s.append('\n');s.append(android.util.Base64.encodeToString(e.name.getBytes(),android.util.Base64.NO_WRAP)).append('|').append(e.income?'I':'E').append('|').append(e.amount);}extras.edit().putString("m_"+ym(c),s.toString()).apply();}
 private ArrayList<Pt> savings(){ArrayList<Pt>a=new ArrayList<>();Calendar c=(Calendar)selected.clone();c.add(Calendar.MONTH,-11);for(int i=0;i<12;i++){double[]t=totals(c);a.add(new Pt(mn(c),t[0]-t[1]));c.add(Calendar.MONTH,1);}return a;}
 private void showSavings(){active="sav";clear("Evolución del ahorro","Últimos 12 meses hasta el período seleccionado");ArrayList<Pt>a=savings();content.addView(new SignedLine(this,a,false),new LinearLayout.LayoutParams(-1,dp(310)));content.addView(tv("El cero queda al centro: arriba hay ahorro y abajo déficit. Ahorro mensual = ingresos - gastos + ajustes del período.",14,MUTED));addSummary();addExtras();}
 private void showBalance(){active="bal";clear("Balance acumulado","Últimos 12 meses hasta el período seleccionado");ArrayList<Pt>s=savings(),a=new ArrayList<>();double acc=0;for(Pt p:s){acc+=p.v;a.add(new Pt(p.n,acc));}content.addView(new SignedLine(this,a,true),new LinearLayout.LayoutParams(-1,dp(310)));content.addView(tv("La línea muestra el ahorro acumulado de los 12 meses. Cada mes suma su ahorro o resta su déficit al saldo anterior.",14,MUTED));addSummary();addExtras();}
 private void addSummary(){double[]t=totals(selected);double s=t[0]-t[1];TextView v=tv("Ingresos: $ "+money.format(t[0])+"   −   Gastos: $ "+money.format(t[1])+"\n"+(s>=0?"Ahorro: $ ":"Déficit: $ ")+money.format(Math.abs(s)),17,TEXT);v.setTypeface(null,Typeface.BOLD);GradientDrawable g=bg(CARD,14);g.setStroke(dp(1),s>=0?Color.rgb(50,180,105):Color.rgb(230,70,70));v.setBackground(g);v.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,dp(8));content.addView(v,p);}
 private void addExtras(){LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView t=tv("Otros ingresos y egresos",18,TEXT);t.setTypeface(null,Typeface.BOLD);head.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button add=btn("+ Agregar");add.setOnClickListener(v->editExtra(-1));head.addView(add,new LinearLayout.LayoutParams(dp(105),dp(44)));content.addView(head);ArrayList<Extra>a=loadExtras(selected);if(a.isEmpty())content.addView(tv("Agregá dinero que tengas en otros lugares o ajustes que quieras incluir en el cálculo.",14,MUTED));for(int i=0;i<a.size();i++){final int ix=i;Extra e=a.get(i);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);String sign=e.income?"+ ":"− ";TextView x=tv(e.name+"\n"+(e.income?"Ingreso":"Egreso")+"   "+sign+"$ "+money.format(e.amount),15,TEXT);r.addView(x,new LinearLayout.LayoutParams(0,-2,1));Button ed=btn("✎"),del=btn("×");ed.setOnClickListener(v->editExtra(ix));del.setOnClickListener(v->{ArrayList<Extra>z=loadExtras(selected);if(ix<z.size()){z.remove(ix);saveExtras(selected,z);render();}});r.addView(ed,new LinearLayout.LayoutParams(dp(52),dp(44)));r.addView(del,new LinearLayout.LayoutParams(dp(52),dp(44)));r.setBackground(bg(CARD,10));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(3),0,dp(3));content.addView(r,rp);}content.addView(tv("Estos montos pertenecen al mes seleccionado y se reflejan tanto en Ahorro como en Balance.",13,MUTED));}
 private void editExtra(int ix){ArrayList<Extra>a=loadExtras(selected);Extra old=ix>=0&&ix<a.size()?a.get(ix):null;LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),0,dp(18),0);EditText name=new EditText(this),amount=new EditText(this);name.setHint("Concepto");name.setText(old==null?"":old.name);amount.setHint("Monto (UYU)");amount.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);amount.setText(old==null?"":String.valueOf(old.amount));Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Ingreso (suma)","Egreso (resta)"}));if(old!=null&&!old.income)type.setSelection(1);f.addView(name);f.addView(amount);f.addView(type);new AlertDialog.Builder(this).setTitle(ix<0?"Agregar monto":"Editar monto").setView(f).setPositiveButton("Guardar",(d,w)->{try{String n=name.getText().toString().trim();double m=Double.parseDouble(amount.getText().toString().replace(',','.'));if(n.isEmpty()||m<0)return;Extra e=new Extra(n,m,type.getSelectedItemPosition()==0);if(ix>=0&&ix<a.size())a.set(ix,e);else a.add(e);saveExtras(selected,a);render();}catch(Exception ignored){}}).setNegativeButton("Cancelar",null).show();}
 private void showCategory(){active="cat";clear("Gastos por categoría",annual?"Distribución del año seleccionado":"Distribución del mes seleccionado");Calendar a=(Calendar)selected.clone();a.set(Calendar.DAY_OF_MONTH,1);if(annual)a.set(Calendar.MONTH,0);Calendar b=(Calendar)a.clone();b.add(annual?Calendar.YEAR:Calendar.MONTH,1);Cursor q=db.getReadableDatabase().rawQuery("SELECT COALESCE(NULLIF(TRIM(category),''),'Otros'),SUM(CASE WHEN type='GASTO' THEN amount WHEN type='INGRESO' AND LOWER(COALESCE(category,''))='transferencias' THEN -amount ELSE 0 END) AS net FROM tx WHERE currency='UYU' AND ts>=? AND ts<? AND (type='GASTO' OR (type='INGRESO' AND LOWER(COALESCE(category,''))='transferencias')) GROUP BY COALESCE(NULLIF(TRIM(category),''),'Otros') ORDER BY net DESC",new String[]{""+a.getTimeInMillis(),""+b.getTimeInMillis()});double total=0;ArrayList<Pt>p=new ArrayList<>();while(q.moveToNext()){String n=q.getString(0);double v=q.getDouble(1);p.add(new Pt(n,v));total+=v;}q.close();TextView sum=tv("Total del período\n$ "+money.format(total),20,TEXT);sum.setTypeface(null,Typeface.BOLD);sum.setBackground(bg(CARD,14));content.addView(sum);for(Pt x:p){int amountColor=x.v<0?Color.rgb(76,200,100):TEXT;TextView r=tv(x.n+"     $ "+money.format(Math.abs(x.v))+"   ›",15,amountColor);r.setBackground(bg(CARD,10));r.setPadding(dp(12),dp(10),dp(12),dp(10));final String catName=x.n;r.setOnClickListener(v->showCategoryMovements(catName,a.getTimeInMillis(),b.getTimeInMillis()));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(3),0,dp(3));content.addView(r,rp);}if(!p.isEmpty()){ArrayList<CategoryBarItem> bars=new ArrayList<>();for(Pt x:p)bars.add(new CategoryBarItem(x.n,x.v,CategoryPrefs.color(this,x.n)));content.addView(new CategoryBars(this,bars),new LinearLayout.LayoutParams(-1,dp(Math.max(210,bars.size()*36+45))));}if(p.isEmpty())content.addView(tv("No hay gastos para este período.",15,MUTED));}
 private void showCategoryMovements(String category,long from,long to){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(4),dp(16),dp(8));ScrollView sc=new ScrollView(this);sc.addView(box);boolean transfers="transferencias".equalsIgnoreCase(category);String sql=transfers?"SELECT id,description,amount,ts,source,type FROM tx WHERE currency='UYU' AND ts>=? AND ts<? AND LOWER(COALESCE(category,''))='transferencias' AND type IN ('GASTO','INGRESO') ORDER BY ts DESC,id DESC":"SELECT id,description,amount,ts,source,type FROM tx WHERE type='GASTO' AND currency='UYU' AND ts>=? AND ts<? AND COALESCE(NULLIF(TRIM(category),''),'Otros')=? ORDER BY ts DESC,id DESC";String[] args=transfers?new String[]{String.valueOf(from),String.valueOf(to)}:new String[]{String.valueOf(from),String.valueOf(to),category};Cursor q=db.getReadableDatabase().rawQuery(sql,args);SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy",new Locale("es","UY"));double total=0;int count=0;while(q.moveToNext()){long id=q.getLong(0);String desc=q.getString(1),src=q.getString(4),type=q.getString(5);double amount=q.getDouble(2);long ts=q.getLong(3);double signed="INGRESO".equals(type)?-amount:amount;total+=signed;count++;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(10),dp(8),dp(10),dp(8));row.setBackground(bg(CARD,10));String amountText=("INGRESO".equals(type)?"- $ ":"$ ")+money.format(amount);row.addView(tv((desc==null||desc.trim().isEmpty()?"Sin descripción":desc)+"     "+amountText,15,TEXT));row.addView(tv(df.format(new Date(ts))+" · "+("INGRESO".equals(type)?"Recibida":"Enviada")+" · "+categorySourceLabel(src),12,MUTED));row.setOnClickListener(v->showMoveCategoryPicker(id,category));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(3),0,dp(3));box.addView(row,rp);}q.close();box.addView(tv(count+" movimientos · Neto $ "+money.format(total)+"\nTocá un movimiento para cambiar su categoría.",14,MUTED),0);new AlertDialog.Builder(this).setTitle(category).setView(sc).setPositiveButton("Cerrar",null).show();}
 private String categorySourceLabel(String s){if(s==null||s.trim().isEmpty())return"Origen no identificado";String n=s.toLowerCase(Locale.ROOT);if(n.startsWith("conciliado:"))return"Excel + notificación";if(n.startsWith("notificacion:"))return"Notificación";if(n.equals("correo")||n.contains("email"))return"Correo";if(n.contains("xls")||n.contains("excel"))return"Excel";if(n.equals("manual"))return"Manual";if(n.equals("recurrente"))return"Recurrente";return"Origen no identificado";}
 private void showMoveCategoryPicker(long id,String current){ArrayList<String> cats=new ArrayList<>(DetectionRules.categoryNames(this));if(current!=null&&!current.trim().isEmpty()&&!cats.contains(current.trim()))cats.add(0,current.trim());String[] arr=cats.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Cambiar categoría").setItems(arr,(d,w)->{DetectionRules.assignMovementCategory(this,id,arr[w]);render();Toast.makeText(this,"Categoría actualizada y movimientos equivalentes reclasificados",Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancelar",null).show();}
 private void showCompare(){active="cmp";clear("Comparar","Comparación simple del período seleccionado con el anterior");Calendar prev=(Calendar)selected.clone();prev.add(Calendar.MONTH,-1);double[]a=totals(selected),b=totals(prev);double sa=a[0]-a[1],sb=b[0]-b[1];content.addView(tv(periodLabel()+": $ "+money.format(sa)+"\nMes anterior: $ "+money.format(sb)+"\nDiferencia: $ "+money.format(sa-sb),18,TEXT));}
 private String shortM(double v){double a=Math.abs(v);String s=a>=1000000?new DecimalFormat("0.#").format(a/1000000)+"M":a>=1000?new DecimalFormat("0.#").format(a/1000)+"k":new DecimalFormat("0").format(a);return(v<0?"-$":"$")+s;}
 static class CategoryBarItem{String name;double value;int color;CategoryBarItem(String n,double v,int c){name=n;value=v;color=c;}}
 class CategoryBars extends View{ArrayList<CategoryBarItem>a;Paint p=new Paint(1);CategoryBars(Context c,ArrayList<CategoryBarItem>x){super(c);a=x;}protected void onDraw(Canvas c){super.onDraw(c);double max=1;for(CategoryBarItem i:a)max=Math.max(max,i.value);float y=dp(18);p.setTextSize(dp(12));for(CategoryBarItem i:a){p.setColor(TEXT);c.drawText(i.name,dp(8),y+dp(13),p);float x=dp(115),track=Math.max(dp(40),getWidth()-dp(205)),ww=track*(float)(i.value/max);p.setColor(Color.argb(45,150,150,150));c.drawRoundRect(x,y,x+track,y+dp(15),dp(7),dp(7),p);p.setColor(i.color);c.drawRoundRect(x,y,x+ww,y+dp(15),dp(7),dp(7),p);p.setColor(i.value<0?Color.rgb(76,200,100):TEXT);c.drawText("$ "+money.format(Math.abs(i.value)),getWidth()-dp(82),y+dp(13),p);y+=dp(36);}}}
 class SignedLine extends View{ArrayList<Pt>a;boolean accumulated;Paint p=new Paint(1);SignedLine(Context c,ArrayList<Pt>x,boolean ac){super(c);a=x;accumulated=ac;p.setTypeface(Typeface.DEFAULT);}protected void onDraw(Canvas c){super.onDraw(c);float l=dp(58),r=getWidth()-dp(8),top=dp(20),bot=getHeight()-dp(42),mid=(top+bot)/2f;double mx=1;for(Pt x:a)mx=Math.max(mx,Math.abs(x.v));double step=Math.pow(10,Math.floor(Math.log10(mx)));mx=Math.ceil(mx/step)*step;p.setStrokeWidth(dp(1));p.setColor(MUTED);for(int i=-2;i<=2;i++){float y=mid-(bot-top)*i/4f;c.drawLine(l,y,r,y,p);p.setTextSize(dp(10));c.drawText(shortM(mx*i/2.0),dp(2),y+dp(4),p);}p.setColor(Color.LTGRAY);p.setStrokeWidth(dp(2));c.drawLine(l,mid,r,mid,p);float dx=(r-l)/11f;Path path=new Path();for(int i=0;i<a.size();i++){float x=l+i*dx;float y=(float)(mid-(a.get(i).v/mx)*(bot-top)/2f);if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}p.setColor(accumulated?Color.rgb(40,160,230):ACCENT);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(3));c.drawPath(path,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<a.size();i++){float x=l+i*dx;float y=(float)(mid-(a.get(i).v/mx)*(bot-top)/2f);p.setColor(a.get(i).v>=0?Color.rgb(80,200,100):Color.rgb(245,75,75));c.drawCircle(x,y,dp(5),p);p.setColor(TEXT);p.setTextSize(dp(10));p.setTextAlign(Paint.Align.CENTER);c.drawText(a.get(i).n,x,bot+dp(20),p);}p.setTextAlign(Paint.Align.LEFT);}}
}
