package com.pablo.controlgastos;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class AnalyticsActivity extends Activity {
    private ExpenseDb db;
    private LinearLayout content;
    private final DecimalFormat money=new DecimalFormat("#,##0.00");
    private int BG,CARD,TEXT,MUTED,YELLOW;

    static class Item { String name; double value; Item(String n,double v){name=n;value=v;} }
    @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);initPalette();db=new ExpenseDb(this);build();showCategory();}
    private void initPalette(){boolean light=ThemePrefs.isLight(this);BG=light?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=light?Color.WHITE:Color.rgb(22,32,41);TEXT=light?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=light?Color.rgb(95,105,112):Color.rgb(158,169,178);YELLOW=Color.rgb(255,207,52);}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView tv(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(8),dp(6),dp(8),dp(6));return v;}
    private GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private Button tab(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,12));return b;}

    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(12),dp(12),dp(12),dp(6));
        Button back=tab("‹");back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));
        LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView t=tv("Gráficos y análisis",24,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);titles.addView(t);String m=new SimpleDateFormat("MMMM yyyy",new Locale("es","UY")).format(new Date());titles.addView(tv(m.substring(0,1).toUpperCase()+m.substring(1),14,MUTED));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(10),dp(5),dp(10),dp(8));Button cat=tab("Por categoría"),merchant=tab("Por comercio"),compare=tab("Comparar"),bud=tab("Presupuestos");for(Button b:new Button[]{cat,merchant,compare,bud}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(125),dp(48));p.setMargins(dp(3),0,dp(3),0);tabs.addView(b,p);}hs.addView(tabs);root.addView(hs);
        ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(5),dp(12),dp(20));sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        cat.setOnClickListener(v->showCategory());merchant.setOnClickListener(v->showMerchant());compare.setOnClickListener(v->showCompare());bud.setOnClickListener(v->showBudgets());setContentView(root);
    }

    private void clear(String title,String sub){content.removeAllViews();TextView h=tv(title,22,TEXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv(sub,14,MUTED));}
    private ArrayList<Object[]> monthRows(int offset){Calendar a=Calendar.getInstance();a.set(Calendar.DAY_OF_MONTH,1);a.set(Calendar.HOUR_OF_DAY,0);a.set(Calendar.MINUTE,0);a.set(Calendar.SECOND,0);a.set(Calendar.MILLISECOND,0);a.add(Calendar.MONTH,offset);Calendar b=(Calendar)a.clone();b.add(Calendar.MONTH,1);Cursor c=db.getReadableDatabase().rawQuery("SELECT type,amount,currency,category,description,ts FROM tx WHERE ts>=? AND ts<? ORDER BY ts DESC",new String[]{String.valueOf(a.getTimeInMillis()),String.valueOf(b.getTimeInMillis())});ArrayList<Object[]> r=new ArrayList<>();while(c.moveToNext())r.add(new Object[]{c.getString(0),c.getDouble(1),c.getString(2),c.getString(3),c.getString(4),c.getLong(5)});c.close();return r;}
    private LinkedHashMap<String,Double> categories(int offset){HashMap<String,Double> m=new HashMap<>();for(Object[] r:monthRows(offset)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;String k=categoryKey((String)r[3],(String)r[4]);m.put(k,m.getOrDefault(k,0.0)+(Double)r[1]);}return sort(m);}
    private LinkedHashMap<String,Double> merchants(int offset){HashMap<String,Double> m=new HashMap<>();for(Object[] r:monthRows(offset)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;String k=merchantKey((String)r[4]);m.put(k,m.getOrDefault(k,0.0)+(Double)r[1]);}return sort(m);}
    private LinkedHashMap<String,Double> sort(Map<String,Double> in){ArrayList<Map.Entry<String,Double>> a=new ArrayList<>(in.entrySet());a.sort((x,y)->Double.compare(y.getValue(),x.getValue()));LinkedHashMap<String,Double> out=new LinkedHashMap<>();for(Map.Entry<String,Double> e:a)out.put(e.getKey(),e.getValue());return out;}

    private void showCategory(){clear("Gastos por categoría","Suma automática de todos los gastos del mes");LinkedHashMap<String,Double> m=categories(0);double total=0;for(double v:m.values())total+=v;addTotal(total);int i=0;for(Map.Entry<String,Double> e:m.entrySet()){addBar(e.getKey(),e.getValue(),total);if(++i>=12)break;}}
    private void showMerchant(){clear("Gastos por comercio","Agrupa variantes como DISCO 23, Supermercado Disco y Disco Express");LinkedHashMap<String,Double> m=merchants(0);double total=0;for(double v:m.values())total+=v;addTotal(total);int i=0;for(Map.Entry<String,Double> e:m.entrySet()){String name=e.getKey();double value=e.getValue();LinearLayout row=barRow(name,value,total);row.setOnClickListener(v->showMerchantDetail(name));content.addView(row);if(++i>=15)break;}}
    private void showMerchantDetail(String merchant){StringBuilder b=new StringBuilder();double total=0;int n=0;SimpleDateFormat df=new SimpleDateFormat("dd/MM HH:mm",Locale.US);for(Object[] r:monthRows(0)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;if(!merchant.equals(merchantKey((String)r[4])))continue;double a=(Double)r[1];total+=a;n++;b.append(df.format(new Date((Long)r[5]))).append("   $ ").append(money.format(a)).append("\n");}new AlertDialog.Builder(this).setTitle(merchant+" · $ "+money.format(total)).setMessage("Compras: "+n+"\n\n"+b).setPositiveButton("Cerrar",null).show();}

    private void showCompare(){clear("Comparación mes a mes","Mes actual contra el mes anterior");LinkedHashMap<String,Double> now=categories(0),prev=categories(-1);double tn=0,tp=0;for(double v:now.values())tn+=v;for(double v:prev.values())tp+=v;double diff=tn-tp;double pct=tp==0?0:diff/tp*100;TextView total=tv("Mes actual: $ "+money.format(tn)+"\nMes anterior: $ "+money.format(tp)+"\nCambio: "+(diff>=0?"+":"")+money.format(diff)+"  ("+(pct>=0?"+":"")+new DecimalFormat("0.0").format(pct)+"%)",18,diff>0?Color.rgb(220,75,75):Color.rgb(45,160,90));total.setTypeface(Typeface.DEFAULT,Typeface.BOLD);total.setBackground(bg(CARD,14));total.setPadding(dp(14),dp(12),dp(14),dp(12));content.addView(total);
        LinkedHashSet<String> keys=new LinkedHashSet<>();keys.addAll(now.keySet());keys.addAll(prev.keySet());for(String k:keys){double a=now.getOrDefault(k,0.0),p=prev.getOrDefault(k,0.0);double max=Math.max(1,Math.max(a,p));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));box.setBackground(bg(CARD,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,0);box.setLayoutParams(lp);TextView name=tv(k+"   Ahora $ "+money.format(a)+" · Antes $ "+money.format(p),15,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);box.addView(name);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(1000);pb.setProgress((int)(1000*a/max));box.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));ProgressBar pp=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pp.setMax(1000);pp.setProgress((int)(1000*p/max));box.addView(pp,new LinearLayout.LayoutParams(-1,dp(12)));content.addView(box);}}

    private void showBudgets(){clear("Presupuestos por categoría","Tocá una categoría para fijar o cambiar su límite mensual");LinkedHashMap<String,Double> spent=categories(0);LinkedHashSet<String> keys=new LinkedHashSet<>(Arrays.asList("Supermercado","Comida","Combustible","Transporte","Servicios","Salud","Tecnología","Regalos","Educación","Otros"));keys.addAll(spent.keySet());SharedPreferences p=getSharedPreferences("budgets",MODE_PRIVATE);for(String k:keys){double s=spent.getOrDefault(k,0.0);double lim=Double.longBitsToDouble(p.getLong(k,Double.doubleToLongBits(0)));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(12),dp(10),dp(12),dp(10));row.setBackground(bg(CARD,12));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,0,0,dp(7));row.setLayoutParams(rp);String label=k+"\nGastado: $ "+money.format(s)+(lim>0?"  ·  Límite: $ "+money.format(lim)+"\nDisponible: $ "+money.format(lim-s):"  ·  Sin límite");TextView t=tv(label,15,lim>0&&s>lim?Color.rgb(220,75,75):TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);row.addView(t);if(lim>0){ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(1000);pb.setProgress((int)Math.min(1000,1000*s/lim));row.addView(pb,new LinearLayout.LayoutParams(-1,dp(14)));}final String fk=k;row.setOnClickListener(v->editBudget(fk));content.addView(row);}}
    private void editBudget(String cat){SharedPreferences p=getSharedPreferences("budgets",MODE_PRIVATE);double old=Double.longBitsToDouble(p.getLong(cat,Double.doubleToLongBits(0)));EditText e=new EditText(this);e.setHint("Límite mensual");e.setInputType(2|8192);if(old>0)e.setText(String.valueOf(old));new AlertDialog.Builder(this).setTitle("Presupuesto · "+cat).setView(e).setPositiveButton("Guardar",(d,w)->{try{double v=Double.parseDouble(e.getText().toString().replace(',','.'));p.edit().putLong(cat,Double.doubleToLongBits(v)).apply();showBudgets();}catch(Exception ex){Toast.makeText(this,"Monto inválido",Toast.LENGTH_LONG).show();}}).setNeutralButton("Quitar límite",(d,w)->{p.edit().remove(cat).apply();showBudgets();}).setNegativeButton("Cancelar",null).show();}

    private void addTotal(double total){TextView t=tv("Total del mes\n$ "+money.format(total),22,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setBackground(bg(CARD,14));t.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(8));content.addView(t,lp);}
    private void addBar(String name,double value,double total){content.addView(barRow(name,value,total));}
    private LinearLayout barRow(String name,double value,double total){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(9),dp(12),dp(9));box.setBackground(bg(CARD,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(6));box.setLayoutParams(lp);double pct=total==0?0:value/total*100;TextView t=tv(name+"   $ "+money.format(value)+"   "+new DecimalFormat("0.0").format(pct)+"%",15,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);box.addView(t);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(1000);pb.setProgress((int)Math.min(1000,pct*10));box.addView(pb,new LinearLayout.LayoutParams(-1,dp(14)));return box;}

    private String categoryKey(String cat,String desc){String c=cat==null?"":cat.trim();if(!c.isEmpty()&&!c.equalsIgnoreCase("Sin categoría")&&!c.equalsIgnoreCase("Banco"))return c;String s=norm(desc);if(has(s,"disco","devoto","geant","tienda inglesa","tata","supermerc"))return "Supermercado";if(has(s,"ancap","combust","axion","nafta","gasoil"))return "Combustible";if(has(s,"ute","ose","antel","movistar","claro","netflix","google"))return "Servicios";if(has(s,"farm","san roque","martinelli"))return "Salud";if(has(s,"pedidos","restaurant","mcdonald","burger","comida"))return "Comida";if(has(s,"peaje","uber","taxi","transporte"))return "Transporte";return "Otros";}
    private String merchantKey(String desc){String s=norm(desc);if(has(s,"disco"))return "Disco";if(has(s,"devoto"))return "Devoto";if(has(s,"geant"))return "Géant";if(has(s,"tienda inglesa"))return "Tienda Inglesa";if(has(s,"tata","ta-ta"))return "Ta-Ta";if(has(s,"ancap"))return "ANCAP";if(has(s,"axion"))return "Axion";if(has(s,"pedidos ya","pedidosya"))return "PedidosYa";if(has(s,"farmashop"))return "Farmashop";if(has(s,"ute"))return "UTE";if(has(s,"antel"))return "Antel";if(has(s,"netflix"))return "Netflix";if(has(s,"google"))return "Google";if(s.isEmpty())return "Sin comercio";String cleaned=s.replaceAll("\\b(nro|nº|no|suc|sucursal|local)\\b"," ").replaceAll("\\d+"," ").replaceAll("[^a-záéíóúñ ]"," ").replaceAll("\\s+"," ").trim();if(cleaned.isEmpty())cleaned=s;String[] parts=cleaned.split(" ");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(parts.length,3);i++){if(i>0)b.append(' ');String p=parts[i];b.append(p.substring(0,1).toUpperCase()).append(p.substring(1));}return b.toString();}
    private String norm(String x){if(x==null)return "";return java.text.Normalizer.normalize(x,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();}
    private boolean has(String s,String... x){for(String v:x)if(s.contains(v))return true;return false;}
}
