package com.pablo.controlgastos;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;
import android.util.Base64;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.lang.Boolean;
import jxl.*;
import jxl.write.*;

public final class BackupXlsManager {
    private static final String MAGIC="CONTROLGASTOS_BACKUP";
    private static final String FORMAT="3";
    private static final String[] PREF_FILES={"detection_rules","blacklist_rules","category_prefs","budget_projection","appearance","security","behavior"};
    private BackupXlsManager(){}
    public static class Info { public boolean isBackup,hasPrivateData; public int categories,recurring,prefEntries,cards,statements,cardMovements; }
    public static class RestoreResult { public int categories,recurring,prefEntries,movedToOther,cards,statements,cardMovements; public boolean emailRestored; }
    public static void appendBackup(Context c, WritableWorkbook wb, ExpenseDb db) throws Exception { appendBackup(c,wb,db,false); }
    public static void appendBackup(Context c, WritableWorkbook wb, ExpenseDb db, boolean includePrivate) throws Exception {
        int idx=wb.getNumberOfSheets();WritableSheet meta=wb.createSheet("_CG_BACKUP_META",idx++);meta.addCell(new Label(0,0,"magic"));meta.addCell(new Label(1,0,MAGIC));meta.addCell(new Label(0,1,"format"));meta.addCell(new Label(1,1,FORMAT));meta.addCell(new Label(0,2,"app"));meta.addCell(new Label(1,2,"ControlGastos"));meta.addCell(new Label(0,3,"private_data"));meta.addCell(new Label(1,3,includePrivate?"1":"0"));
        WritableSheet prefs=wb.createSheet("_CG_PREFS",idx++);prefs.addCell(new Label(0,0,"archivo"));prefs.addCell(new Label(1,0,"clave"));prefs.addCell(new Label(2,0,"tipo"));prefs.addCell(new Label(3,0,"valor"));int pr=1;for(String file:PREF_FILES)for(Map.Entry<String,?> e:c.getSharedPreferences(file,Context.MODE_PRIVATE).getAll().entrySet()){String[] enc=encodeValue(e.getValue());if(enc==null)continue;prefs.addCell(new Label(0,pr,file));prefs.addCell(new Label(1,pr,e.getKey()));prefs.addCell(new Label(2,pr,enc[0]));prefs.addCell(new Label(3,pr,enc[1]));pr++;}
        LinkedHashSet<String> cats=new LinkedHashSet<>(CategoryPrefs.definedCategories(c));Cursor dc=db.getReadableDatabase().rawQuery("SELECT DISTINCT category FROM tx WHERE category IS NOT NULL AND TRIM(category)<>'' ORDER BY category COLLATE NOCASE",null);try{while(dc.moveToNext())cats.add(dc.getString(0));}finally{dc.close();}WritableSheet cs=wb.createSheet("_CG_CATEGORIAS",idx++);cs.addCell(new Label(0,0,"Categoría"));cs.addCell(new Label(1,0,"Color"));int cr=1;for(String cat:cats){if(cat==null||cat.trim().isEmpty())continue;cs.addCell(new Label(0,cr,cat));cs.addCell(new jxl.write.Number(1,cr,CategoryPrefs.color(c,cat)));cr++;}
        WritableSheet rec=wb.createSheet("_CG_RECURRENTES",idx++);String[] rh={"Tipo","Monto","Moneda","Categoría","Descripción","Día","Activo","Último mes"};for(int i=0;i<rh.length;i++)rec.addCell(new Label(i,0,rh[i]));Cursor rc=db.getReadableDatabase().rawQuery("SELECT type,amount,currency,category,description,day,active,last_ym FROM recurring ORDER BY id",null);int rr=1;try{while(rc.moveToNext()){rec.addCell(new Label(0,rr,nz(rc.getString(0))));rec.addCell(new jxl.write.Number(1,rr,rc.getDouble(1)));rec.addCell(new Label(2,rr,nz(rc.getString(2))));rec.addCell(new Label(3,rr,nz(rc.getString(3))));rec.addCell(new Label(4,rr,nz(rc.getString(4))));rec.addCell(new jxl.write.Number(5,rr,rc.getInt(5)));rec.addCell(new jxl.write.Number(6,rr,rc.getInt(6)));rec.addCell(new Label(7,rr,nz(rc.getString(7))));rr++;}}finally{rc.close();}if(includePrivate)appendPrivate(c,wb,idx);
    }
    private static void appendPrivate(Context c,WritableWorkbook wb,int idx)throws Exception{SharedPreferences ep=c.getSharedPreferences(EmailSyncEngine.PREF,Context.MODE_PRIVATE);WritableSheet es=wb.createSheet("_CG_CORREO",idx++);es.addCell(new Label(0,0,"clave"));es.addCell(new Label(1,0,"valor_base64"));String[][] ev={{"email",ep.getString("email","")},{"password",SecretStore.get(c)},{"host",ep.getString("host","imap.gmail.com")},{"enable_cards",String.valueOf(ep.getBoolean("enable_cards",true))},{"card_months_back",String.valueOf(ep.getInt("card_months_back",1))},{"search_timeout_minutes",String.valueOf(ep.getInt("search_timeout_minutes",2))},{"enable_expenses",String.valueOf(ep.getBoolean("enable_expenses",false))},{"expense_months_back",String.valueOf(ep.getInt("expense_months_back",1))},{"card_whitelist",ep.getString("card_whitelist","sistarbanc|Estado de cuenta")},{"expense_whitelist",ep.getString("expense_whitelist","")}};for(int r=0;r<ev.length;r++){es.addCell(new Label(0,r+1,ev[r][0]));es.addCell(new Label(1,r+1,b64(ev[r][1])));}CreditCardDb helper=new CreditCardDb(c);SQLiteDatabase d=helper.getReadableDatabase();WritableSheet cards=wb.createSheet("_CG_TARJETAS",idx++);cards.addCell(new Label(0,0,"id"));cards.addCell(new Label(1,0,"nombre"));cards.addCell(new Label(2,0,"ultimos4"));Cursor x=d.rawQuery("SELECT id,name,last4 FROM cards ORDER BY id",null);int r=1;try{while(x.moveToNext()){cards.addCell(new jxl.write.Number(0,r,x.getLong(0)));cards.addCell(new Label(1,r,nz(x.getString(1))));cards.addCell(new Label(2,r,nz(x.getString(2))));r++;}}finally{x.close();}WritableSheet st=wb.createSheet("_CG_ESTADOS_TARJETA",idx++);String[] sh={"id","card_id","cierre","vence","total","moneda"};for(int i=0;i<sh.length;i++)st.addCell(new Label(i,0,sh[i]));x=d.rawQuery("SELECT id,card_id,close_date,due_date,total,currency FROM statements ORDER BY id",null);r=1;try{while(x.moveToNext()){st.addCell(new jxl.write.Number(0,r,x.getLong(0)));st.addCell(new jxl.write.Number(1,r,x.getLong(1)));st.addCell(new Label(2,r,nz(x.getString(2))));st.addCell(new Label(3,r,nz(x.getString(3))));st.addCell(new jxl.write.Number(4,r,x.getDouble(4)));st.addCell(new Label(5,r,nz(x.getString(5))));r++;}}finally{x.close();}WritableSheet it=wb.createSheet("_CG_MOV_TARJETA",idx);String[] ih={"statement_id","fecha","descripcion","cuota","monto","moneda"};for(int i=0;i<ih.length;i++)it.addCell(new Label(i,0,ih[i]));x=d.rawQuery("SELECT statement_id,tx_date,description,installment,amount,currency FROM installments ORDER BY id",null);r=1;try{while(x.moveToNext()){it.addCell(new jxl.write.Number(0,r,x.getLong(0)));it.addCell(new Label(1,r,nz(x.getString(1))));it.addCell(new Label(2,r,nz(x.getString(2))));it.addCell(new Label(3,r,nz(x.getString(3))));it.addCell(new jxl.write.Number(4,r,x.getDouble(4)));it.addCell(new Label(5,r,nz(x.getString(5))));r++;}}finally{x.close();}helper.close();}
    public static Info inspect(Context c,Uri uri){Info info=new Info();InputStream in=null;Workbook wb=null;try{in=c.getContentResolver().openInputStream(uri);if(in==null)return info;wb=Workbook.getWorkbook(in);if(!valid(wb))return info;info.isBackup=true;Sheet s=wb.getSheet("_CG_BACKUP_META");info.hasPrivateData=s!=null&&s.getRows()>3&&"1".equals(s.getCell(1,3).getContents());Sheet q=wb.getSheet("_CG_CATEGORIAS");if(q!=null)info.categories=Math.max(0,q.getRows()-1);q=wb.getSheet("_CG_RECURRENTES");if(q!=null)info.recurring=Math.max(0,q.getRows()-1);q=wb.getSheet("_CG_PREFS");if(q!=null)info.prefEntries=Math.max(0,q.getRows()-1);q=wb.getSheet("_CG_TARJETAS");if(q!=null)info.cards=Math.max(0,q.getRows()-1);q=wb.getSheet("_CG_ESTADOS_TARJETA");if(q!=null)info.statements=Math.max(0,q.getRows()-1);q=wb.getSheet("_CG_MOV_TARJETA");if(q!=null)info.cardMovements=Math.max(0,q.getRows()-1);return info;}catch(Exception ignored){return info;}finally{if(wb!=null)wb.close();if(in!=null)try{in.close();}catch(Exception ignored){}}}
    public static RestoreResult restore(Context c,Uri uri,ExpenseDb db)throws Exception{InputStream in=c.getContentResolver().openInputStream(uri);if(in==null)throw new IOException("No se pudo abrir el respaldo");Workbook wb=null;try{wb=Workbook.getWorkbook(in);if(!valid(wb))throw new IOException("El archivo no contiene un respaldo completo de ControlGastos");RestoreResult result=new RestoreResult();restorePrefs(c,wb,result);LinkedHashSet<String> allowed=restoreCategories(c,wb,result);restoreRecurring(db,wb,result);result.movedToOther=applyCategoryConfiguration(db,allowed);if(wb.getSheet("_CG_CORREO")!=null)restorePrivate(c,wb,result);db.reapplySalaryMonthRule();return result;}finally{if(wb!=null)wb.close();try{in.close();}catch(Exception ignored){}}}
    private static void restorePrivate(Context c,Workbook wb,RestoreResult out)throws Exception{Sheet es=wb.getSheet("_CG_CORREO");Map<String,String> m=new HashMap<>();for(int r=1;r<es.getRows();r++)try{m.put(es.getCell(0,r).getContents(),ub64(es.getCell(1,r).getContents()));}catch(Exception ignored){}SharedPreferences.Editor e=c.getSharedPreferences(EmailSyncEngine.PREF,Context.MODE_PRIVATE).edit();e.putString("email",m.getOrDefault("email",""));e.putString("host",m.getOrDefault("host","imap.gmail.com"));e.putBoolean("enable_cards",Boolean.parseBoolean(m.getOrDefault("enable_cards","true")));e.putInt("card_months_back",intv(m.get("card_months_back"),1));e.putInt("search_timeout_minutes",Math.max(1,Math.min(30,intv(m.get("search_timeout_minutes"),2))));e.putBoolean("enable_expenses",Boolean.parseBoolean(m.getOrDefault("enable_expenses","false")));e.putInt("expense_months_back",intv(m.get("expense_months_back"),1));e.putString("card_whitelist",m.getOrDefault("card_whitelist","sistarbanc|Estado de cuenta"));e.putString("expense_whitelist",m.getOrDefault("expense_whitelist",""));e.commit();SecretStore.put(c,m.getOrDefault("password",""));out.emailRestored=true;CreditCardDb h=new CreditCardDb(c);SQLiteDatabase d=h.getWritableDatabase();d.beginTransaction();try{d.delete("installments",null,null);d.delete("statements",null,null);d.delete("cards",null,null);Sheet s=wb.getSheet("_CG_TARJETAS");if(s!=null)for(int r=1;r<s.getRows();r++){ContentValues v=new ContentValues();v.put("id",(long)cellDouble(s.getCell(0,r)));v.put("name",s.getCell(1,r).getContents());v.put("last4",s.getCell(2,r).getContents());d.insert("cards",null,v);out.cards++;}s=wb.getSheet("_CG_ESTADOS_TARJETA");if(s!=null)for(int r=1;r<s.getRows();r++){ContentValues v=new ContentValues();v.put("id",(long)cellDouble(s.getCell(0,r)));v.put("card_id",(long)cellDouble(s.getCell(1,r)));v.put("close_date",s.getCell(2,r).getContents());v.put("due_date",s.getCell(3,r).getContents());v.put("total",cellDouble(s.getCell(4,r)));v.put("currency",s.getCell(5,r).getContents());d.insert("statements",null,v);out.statements++;}s=wb.getSheet("_CG_MOV_TARJETA");if(s!=null)for(int r=1;r<s.getRows();r++){ContentValues v=new ContentValues();v.put("statement_id",(long)cellDouble(s.getCell(0,r)));v.put("tx_date",s.getCell(1,r).getContents());v.put("description",s.getCell(2,r).getContents());v.put("installment",s.getCell(3,r).getContents());v.put("amount",cellDouble(s.getCell(4,r)));v.put("currency",s.getCell(5,r).getContents());d.insert("installments",null,v);out.cardMovements++;}d.setTransactionSuccessful();}finally{d.endTransaction();h.close();}}
    private static boolean valid(Workbook wb){Sheet s=wb.getSheet("_CG_BACKUP_META");return s!=null&&s.getRows()>0&&s.getColumns()>1&&MAGIC.equals(s.getCell(1,0).getContents());}
    private static void restorePrefs(Context c,Workbook wb,RestoreResult out)throws Exception{Sheet s=wb.getSheet("_CG_PREFS");if(s==null)throw new IOException("Falta la configuración del respaldo");HashMap<String,SharedPreferences.Editor> editors=new HashMap<>();for(String file:PREF_FILES)editors.put(file,c.getSharedPreferences(file,Context.MODE_PRIVATE).edit().clear());for(int r=1;r<s.getRows();r++){String file=s.getCell(0,r).getContents(),key=s.getCell(1,r).getContents(),type=s.getCell(2,r).getContents(),value=s.getCell(3,r).getContents();SharedPreferences.Editor e=editors.get(file);if(e==null||key.isEmpty())continue;decodeInto(e,key,type,value);out.prefEntries++;}for(SharedPreferences.Editor e:editors.values())e.commit();}
    private static LinkedHashSet<String> restoreCategories(Context c,Workbook wb,RestoreResult out)throws Exception{Sheet s=wb.getSheet("_CG_CATEGORIAS");if(s==null)throw new IOException("Falta la lista de categorías del respaldo");LinkedHashSet<String> cats=new LinkedHashSet<>();c.getSharedPreferences("category_prefs",Context.MODE_PRIVATE).edit().clear().commit();for(int r=1;r<s.getRows();r++){String cat=s.getCell(0,r).getContents().trim();if(cat.isEmpty())continue;cats.add(cat);try{CategoryPrefs.setColor(c,cat,(int)Math.round(cellDouble(s.getCell(1,r))));}catch(Exception ignored){}out.categories++;}CategoryPrefs.replaceRegistry(c,cats);cats.add("Otros");return cats;}
    private static void restoreRecurring(ExpenseDb db,Workbook wb,RestoreResult out)throws Exception{Sheet s=wb.getSheet("_CG_RECURRENTES");if(s==null)return;SQLiteDatabase sql=db.getWritableDatabase();sql.beginTransaction();try{sql.delete("recurring",null,null);for(int r=1;r<s.getRows();r++){String type=s.getCell(0,r).getContents().trim();if(type.isEmpty())continue;ContentValues v=new ContentValues();v.put("type",type);v.put("amount",cellDouble(s.getCell(1,r)));v.put("currency",s.getCell(2,r).getContents());v.put("category",s.getCell(3,r).getContents());v.put("description",s.getCell(4,r).getContents());v.put("day",(int)Math.round(cellDouble(s.getCell(5,r))));v.put("active",(int)Math.round(cellDouble(s.getCell(6,r))));v.put("last_ym",s.getCell(7,r).getContents());sql.insert("recurring",null,v);out.recurring++;}sql.setTransactionSuccessful();}finally{sql.endTransaction();}}
    private static int applyCategoryConfiguration(ExpenseDb db,Set<String> allowed){HashSet<String> norm=new HashSet<>();for(String x:allowed)norm.add(DetectionRules.norm(x));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,category FROM tx WHERE category IS NOT NULL AND TRIM(category)<>''",null);ArrayList<Long> ids=new ArrayList<>();try{while(c.moveToNext())if(!norm.contains(DetectionRules.norm(c.getString(1))))ids.add(c.getLong(0));}finally{c.close();}ContentValues v=new ContentValues();v.put("category","Otros");for(Long id:ids)db.getWritableDatabase().update("tx",v,"id=?",new String[]{String.valueOf(id)});return ids.size();}
    private static int intv(String s,int d){try{return Integer.parseInt(s);}catch(Exception e){return d;}}
    private static double cellDouble(Cell c){if(c instanceof NumberCell)return((NumberCell)c).getValue();try{return Double.parseDouble(c.getContents().replace(',','.'));}catch(Exception e){return 0;}}private static String nz(String s){return s==null?"":s;}private static String b64(String s){return Base64.encodeToString((s==null?"":s).getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);}private static String ub64(String s){return new String(Base64.decode(s,Base64.DEFAULT),StandardCharsets.UTF_8);}
    private static String[] encodeValue(Object v){if(v instanceof java.lang.Boolean)return new String[]{"B",String.valueOf(v)};if(v instanceof Integer)return new String[]{"I",String.valueOf(v)};if(v instanceof Long)return new String[]{"L",String.valueOf(v)};if(v instanceof Float)return new String[]{"F",String.valueOf(v)};if(v instanceof String)return new String[]{"S",b64((String)v)};if(v instanceof Set){StringBuilder b=new StringBuilder();for(Object x:(Set<?>)v){if(b.length()>0)b.append(',');b.append(b64(String.valueOf(x)));}return new String[]{"SS",b.toString()};}return null;}
    private static void decodeInto(SharedPreferences.Editor e,String key,String type,String value){try{switch(type){case"B":e.putBoolean(key,Boolean.parseBoolean(value));break;case"I":e.putInt(key,Integer.parseInt(value));break;case"L":e.putLong(key,Long.parseLong(value));break;case"F":e.putFloat(key,Float.parseFloat(value));break;case"S":e.putString(key,ub64(value));break;case"SS":HashSet<String> set=new HashSet<>();if(!value.isEmpty())for(String x:value.split(","))set.add(ub64(x));e.putStringSet(key,set);break;}}catch(Exception ignored){}}
}
