package com.pablo.controlgastos;

import android.content.Context;
import android.net.Uri;
import java.io.*;import java.security.MessageDigest;import java.text.*;import java.util.*;import jxl.*;

public class BankXlsImporter {
 public static class Tx{public String type,currency,category,description,original,fingerprint;public double amount;public long ts;}
 public static class Result{public final ArrayList<Tx> rows=new ArrayList<>();public int ignored=0;}

 public static Result parse(Context context,Uri uri)throws Exception{
  InputStream in=context.getContentResolver().openInputStream(uri);if(in==null)throw new IOException("No se pudo abrir el archivo");Workbook wb=null;
  try{wb=Workbook.getWorkbook(in);Result out=new Result();Map<String,Integer> occ=new HashMap<>();for(Sheet sh:wb.getSheets()){int before=out.rows.size();parseSheet(context,sh,out,occ);if(out.rows.size()==before)parseEbroUFallback(context,sh,out,occ);}if(out.rows.isEmpty())throw new IOException("No encontré movimientos reconocibles en el Excel del banco");return out;}finally{if(wb!=null)wb.close();try{in.close();}catch(Exception ignored){}}
 }
 private static void parseSheet(Context context,Sheet sh,Result out,Map<String,Integer> occ){int rows=sh.getRows(),cols=sh.getColumns();if(rows<1||cols<1)return;int header=findHeaderRow(sh);if(header<0)return;HeaderMap hm=buildHeaderMap(sh,header);if(hm.date<0||(hm.debit<0&&hm.credit<0&&hm.amount<0))return;boolean started=false;int invalidAfterStart=0;for(int r=header+1;r<rows;r++){String[] cells=readRow(sh,r,cols);boolean any=false;for(String x:cells)if(!x.isEmpty()){any=true;break;}if(!any){if(started&&++invalidAfterStart>=8)break;continue;}String original=joinRaw(cells);if(looksLikeFooter(original)){if(started)break;else continue;}Date date=findDate(sh,r,hm,cells);AmountInfo ai=findAmount(sh,r,hm,cells);if(date==null||ai==null||ai.amount<=0){out.ignored++;if(started&&++invalidAfterStart>=8)break;continue;}started=true;invalidAfterStart=0;String rawDesc=findDescription(hm,cells);date=adjustMonthBoundaryTransferDate(date,rawDesc,cells);String desc=transferDescription(rawDesc,hm.subject>=0&&hm.subject<cells.length?cells[hm.subject]:"");String currency=findCurrency(cells,sh.getName());String importedCategory=hm.category>=0&&hm.category<cells.length?cells[hm.category]:"";String importedFingerprint=controlGastosFingerprint(hm.document>=0&&hm.document<cells.length?cells[hm.document]:"");addTx(context,out,occ,date,ai,currency,desc,original,importedCategory,importedFingerprint);}}
 private static void parseEbroUFallback(Context context,Sheet sh,Result out,Map<String,Integer> occ){int rows=sh.getRows(),cols=sh.getColumns();if(rows<1||cols<2)return;int header=-1;for(int r=0;r<rows;r++){String first=norm(sh.getCell(0,r).getContents());String all=rowText(sh,r,cols);if(first.contains("fecha")&&all.contains("descripcion")){header=r;break;}}if(header<0){for(int r=0;r<rows;r++){if(rowText(sh,r,cols).contains("movimientos")){for(int k=r+1;k<Math.min(rows,r+8);k++){if(norm(sh.getCell(0,k).getContents()).contains("fecha")){header=k;break;}}if(header>=0)break;}}}if(header<0)return;int debitCol=cols>6?6:Math.max(0,cols-2),creditCol=cols>7?7:Math.max(0,cols-1);int subjectCol=findColumn(sh,header,"asunto"),categoryCol=findColumn(sh,header,"categoria"),documentCol=findColumn(sh,header,"numero de documento");int invalid=0;boolean started=false;for(int r=header+1;r<rows;r++){String[] cells=readRow(sh,r,cols);String original=joinRaw(cells);if(original.isEmpty()){if(started&&++invalid>=8)break;continue;}if(looksLikeFooter(original))break;Date date=dateFromCell(sh.getCell(0,r),cells.length>0?cells[0]:"");if(date==null){if(started&&++invalid>=8)break;continue;}Double debit=debitCol<cols?cellNumber(sh.getCell(debitCol,r),cells[debitCol]):null;Double credit=creditCol<cols?cellNumber(sh.getCell(creditCol,r),cells[creditCol]):null;AmountInfo ai=null;if(debit!=null&&Math.abs(debit)>0.0001)ai=new AmountInfo("GASTO",Math.abs(debit));else if(credit!=null&&Math.abs(credit)>0.0001)ai=new AmountInfo("INGRESO",Math.abs(credit));if(ai==null){if(started&&++invalid>=8)break;continue;}started=true;invalid=0;String rawDesc=cells.length>1?cells[1]:"";date=adjustMonthBoundaryTransferDate(date,rawDesc,cells);String subject=subjectCol>=0&&subjectCol<cells.length?cells[subjectCol]:"";String desc=transferDescription(rawDesc,subject);if(desc.isEmpty())desc="Movimiento bancario";String currency=findCurrency(cells,sh.getName());String importedCategory=categoryCol>=0&&categoryCol<cells.length?cells[categoryCol]:"";String importedFingerprint=controlGastosFingerprint(documentCol>=0&&documentCol<cells.length?cells[documentCol]:"");addTx(context,out,occ,date,ai,currency,desc,original,importedCategory,importedFingerprint);}}
 private static boolean isTransferDescription(String desc){String key=norm(clean(desc)).replaceAll("[^a-z0-9]+"," ").replaceAll("\\s+"," ").trim();return key.contains("transferencia")||key.contains("transfer")||key.equals("transf")||key.startsWith("transf ")||key.equals("trf")||key.startsWith("trf ");}
 private static String transferDescription(String desc,String subject){String d=clean(desc),s=clean(subject);if(isTransferDescription(d)&&!s.isEmpty())return s;return d;}
 private static Date adjustMonthBoundaryTransferDate(Date booked,String desc,String[] cells){
  if(booked==null||!isTransferDescription(desc))return booked;
  Calendar b=Calendar.getInstance();b.setTime(booked);int day=b.get(Calendar.DAY_OF_MONTH),max=b.getActualMaximum(Calendar.DAY_OF_MONTH);if(day<max-2)return booked;
  Calendar next=(Calendar)b.clone();next.add(Calendar.MONTH,1);int nextYear=next.get(Calendar.YEAR),nextMonth=next.get(Calendar.MONTH);
  for(String cell:cells){String digits=cell==null?"":cell.replaceAll("\\D","");if(digits.length()<6)continue;String ymd=digits.substring(0,6);try{int yy=Integer.parseInt(ymd.substring(0,2)),mm=Integer.parseInt(ymd.substring(2,4)),dd=Integer.parseInt(ymd.substring(4,6));int yyyy=2000+yy;if(yyyy!=nextYear||mm-1!=nextMonth)continue;Calendar c=Calendar.getInstance();c.clear();c.setLenient(false);c.set(yyyy,mm-1,dd,12,0,0);Date candidate=c.getTime();long deltaDays=Math.round((atNoon(candidate).getTime()-atNoon(booked).getTime())/86400000d);if(deltaDays>=1&&deltaDays<=3)return candidate;}catch(Exception ignored){}}
  return booked;
 }
 private static int findColumn(Sheet sh,int header,String name){for(int c=0;c<sh.getColumns();c++)if(norm(sh.getCell(c,header).getContents()).contains(name))return c;return-1;}
 private static void addTx(Context context,Result out,Map<String,Integer> occ,Date date,AmountInfo ai,String currency,String desc,String original,String importedCategory,String importedFingerprint){String category=clean(importedCategory);if(category.isEmpty())category=DetectionRules.categoryFor(context,original,classify(desc));String day=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(date);String canonical=day+"|"+ai.type+"|"+currency+"|"+String.format(Locale.US,"%.2f",ai.amount)+"|"+norm(desc)+"|"+norm(original);int n=occ.containsKey(canonical)?occ.get(canonical)+1:1;occ.put(canonical,n);Tx tx=new Tx();tx.type=ai.type;tx.amount=ai.amount;tx.currency=currency;tx.category=category;tx.description=desc.isEmpty()?"Movimiento bancario":desc;tx.original=original;tx.ts=atNoon(date).getTime();tx.fingerprint=(importedFingerprint!=null&&!importedFingerprint.isEmpty())?importedFingerprint:sha256("bank-xls|"+canonical+"|occ="+n);out.rows.add(tx);}private static String controlGastosFingerprint(String document){String d=clean(document);if(d.regionMatches(true,0,"CG:",0,3)){String f=d.substring(3).trim();if(f.matches("(?i)[0-9a-f]{64}"))return f.toLowerCase(Locale.ROOT);}return"";}
 private static String[] readRow(Sheet sh,int r,int cols){String[] cells=new String[cols];for(int c=0;c<cols;c++)cells[c]=clean(sh.getCell(c,r).getContents());return cells;}private static String rowText(Sheet sh,int r,int cols){return norm(joinRaw(readRow(sh,r,cols)));}
 private static class HeaderMap{int date=-1,desc=-1,subject=-1,debit=-1,credit=-1,amount=-1,category=-1,document=-1;}private static class AmountInfo{String type;double amount;AmountInfo(String t,double a){type=t;amount=a;}}
 private static int findHeaderRow(Sheet sh){int best=-1,bestScore=-1;for(int r=0;r<sh.getRows();r++){boolean hasDate=false,hasDebit=false,hasCredit=false,hasAmount=false;int score=0;for(int c=0;c<sh.getColumns();c++){String s=norm(sh.getCell(c,r).getContents());if(s.contains("fecha")||s.equals("date")){hasDate=true;score+=5;}if(hasAny(s,"descripcion","concepto","detalle","movimiento","leyenda"))score+=3;if(hasAny(s,"debito","debe","egreso","cargo","retiro")){hasDebit=true;score+=3;}if(hasAny(s,"credito","haber","ingreso","deposito")){hasCredit=true;score+=3;}if(hasAny(s,"importe","monto","amount")){hasAmount=true;score+=2;}}boolean valid=hasDate&&((hasDebit||hasCredit)||hasAmount);if(valid&&score>bestScore){bestScore=score;best=r;}}return best;}
 private static HeaderMap buildHeaderMap(Sheet sh,int header){HeaderMap h=new HeaderMap();if(header<0)return h;for(int c=0;c<sh.getColumns();c++){String s=norm(sh.getCell(c,header).getContents());if(h.date<0&&(s.contains("fecha")||s.equals("date")))h.date=c;if(h.desc<0&&hasAny(s,"concepto","descripcion","detalle","movimiento","leyenda","referencia"))h.desc=c;if(h.subject<0&&s.contains("asunto"))h.subject=c;if(h.debit<0&&hasAny(s,"debito","debe","egreso","cargo","retiro"))h.debit=c;if(h.credit<0&&hasAny(s,"credito","haber","ingreso","deposito"))h.credit=c;if(h.amount<0&&hasAny(s,"importe","monto","amount"))h.amount=c;if(h.category<0&&s.contains("categoria"))h.category=c;if(h.document<0&&s.contains("numero de documento"))h.document=c;}return h;}
 private static Date findDate(Sheet sh,int r,HeaderMap h,String[] cells){if(h.date>=0&&h.date<cells.length){Date d=dateFromCell(sh.getCell(h.date,r),cells[h.date]);if(d!=null)return d;}for(int c=0;c<cells.length;c++){Date d=dateFromCell(sh.getCell(c,r),cells[c]);if(d!=null)return d;}return null;}
 private static Date dateFromCell(Cell cell,String text){if(cell instanceof DateCell)try{return((DateCell)cell).getDate();}catch(Exception ignored){}if(cell instanceof NumberCell)try{double serial=((NumberCell)cell).getValue();if(serial>20000&&serial<80000)return excelSerialToDate(serial);}catch(Exception ignored){}String s=text==null?"":text.trim();if(!s.isEmpty()){String[] p={"dd/MM/yyyy","d/M/yyyy","dd/MM/yy","d/M/yy","dd-MM-yyyy","d-M-yyyy","yyyy-MM-dd","MM/dd/yyyy","M/d/yyyy","MM/dd/yy","M/d/yy","dd/MM/yyyy HH:mm","d/M/yyyy HH:mm","MM/dd/yyyy HH:mm","M/d/yyyy HH:mm"};for(String x:p)try{SimpleDateFormat f=new SimpleDateFormat(x,Locale.US);f.setLenient(false);Date d=f.parse(s);if(d!=null)return d;}catch(Exception ignored){}Double serial=parseNumber(s);if(serial!=null&&serial>20000&&serial<80000)return excelSerialToDate(serial);}return null;}
 private static Date excelSerialToDate(double serial){Calendar c=Calendar.getInstance(TimeZone.getTimeZone("UTC"),Locale.US);c.clear();c.set(1899,Calendar.DECEMBER,30,0,0,0);long ms=c.getTimeInMillis()+Math.round(serial*86400000d);return new Date(ms);}
 private static AmountInfo findAmount(Sheet sh,int r,HeaderMap h,String[] cells){if(h.debit>=0){Double v=cellNumber(sh.getCell(h.debit,r),cells[h.debit]);if(v!=null&&Math.abs(v)>0.0001)return new AmountInfo("GASTO",Math.abs(v));}if(h.credit>=0){Double v=cellNumber(sh.getCell(h.credit,r),cells[h.credit]);if(v!=null&&Math.abs(v)>0.0001)return new AmountInfo("INGRESO",Math.abs(v));}if(h.amount>=0){Double v=cellNumber(sh.getCell(h.amount,r),cells[h.amount]);if(v!=null&&Math.abs(v)>0.0001)return new AmountInfo(v<0?"GASTO":"INGRESO",Math.abs(v));}return null;}
 private static Double cellNumber(Cell cell,String text){if(cell instanceof NumberCell)try{return((NumberCell)cell).getValue();}catch(Exception ignored){}return parseNumber(text);}
 private static String findDescription(HeaderMap h,String[] cells){if(h.desc>=0&&h.desc<cells.length&&!cells[h.desc].isEmpty())return cells[h.desc];String best="";for(String s:cells)if(s.length()>best.length()&&parseNumber(s)==null&&!looksLikeDate(s))best=s;return best;}private static boolean looksLikeDate(String s){return s.matches("\\d{1,4}[-/]\\d{1,2}[-/]\\d{1,4}.*");}private static boolean looksLikeFooter(String s){String n=norm(s);return n.contains("esta informacion es la que consta en los sistemas del banco")||n.contains("supeditada a los ajustes");}
 private static Double parseNumber(String src){if(src==null)return null;String s=src.trim().replace("\u00a0","").replace(" ","");if(s.isEmpty())return null;boolean neg=s.startsWith("-")||(s.startsWith("(")&&s.endsWith(")"));s=s.replaceAll("[^0-9,.-]","");if(s.isEmpty()||s.equals("-")||s.equals(".")||s.equals(","))return null;s=s.replace("-","");int comma=s.lastIndexOf(','),dot=s.lastIndexOf('.');if(comma>=0&&dot>=0){if(comma>dot)s=s.replace(".","").replace(',','.');else s=s.replace(",","");}else if(comma>=0)s=s.replace(',','.');try{double v=Double.parseDouble(s);return neg?-v:v;}catch(Exception e){return null;}}
 private static String findCurrency(String[] cells,String sheetName){String all=(sheetName+" "+joinRaw(cells)).toUpperCase(Locale.ROOT);if(all.contains("USD")||all.contains("U$S")||all.contains("US$")||all.contains("DOLAR")||all.contains("DÓLAR"))return"USD";return"UYU";}private static String classify(String desc){String s=norm(desc);if(hasAny(s,"super","tienda inglesa","devoto","disco","tata","geant"))return"Supermercado";if(hasAny(s,"ancap","combustible","estacion de servicio","nafta","gasoil"))return"Combustible";if(hasAny(s,"ute","ose","antel","movistar","claro"))return"Servicios";if(hasAny(s,"farmacia","san roque","farmashop"))return"Salud";if(hasAny(s,"restaurante","restaurant","delivery","pedidos ya","pedidosya"))return"Comida";if(hasAny(s,"transferencia","transf","trf"))return"Transferencias";if(hasAny(s,"paganza"))return"Pagos";return"Banco";}
 private static Date atNoon(Date d){Calendar c=Calendar.getInstance();c.setTime(d);c.set(Calendar.HOUR_OF_DAY,12);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTime();}private static String clean(String s){return s==null?"":s.replace('\n',' ').replace('\r',' ').trim();}private static String joinRaw(String[] a){StringBuilder b=new StringBuilder();for(String s:a){if(s==null||s.isEmpty())continue;if(b.length()>0)b.append(" | ");b.append(s);}return b.toString();}private static String norm(String s){if(s==null)return"";String n=java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","");return n.toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();}private static boolean hasAny(String s,String...w){for(String x:w)if(s.contains(x))return true;return false;}private static String sha256(String s){try{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[]x=md.digest(s.getBytes("UTF-8"));StringBuilder b=new StringBuilder();for(byte v:x)b.append(String.format(Locale.US,"%02x",v&255));return b.toString();}catch(Exception e){return String.valueOf(s.hashCode());}}
}
