package com.pablo.controlgastos;

import android.app.*;import android.os.Bundle;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;

public class BlacklistActivity extends Activity{
 private static class Row{EditText word;LinearLayout view;}
 private final ArrayList<Row> rows=new ArrayList<>();private LinearLayout list;private int TEXT,MUTED;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);build();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 private void build(){boolean l=ThemePrefs.isLight(this);int bg=l?Color.rgb(246,248,249):Color.rgb(11,18,24);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.DKGRAY:Color.LTGRAY;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(bg);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(14),i.getSystemWindowInsetTop()+dp(34),dp(14),i.getSystemWindowInsetBottom()+dp(14));return i;});root.requestApplyInsets();TextView t=new TextView(this);t.setText("Lista negra de notificaciones");t.setTextSize(24);t.setTextColor(TEXT);root.addView(t);TextView info=new TextView(this);info.setText("No hay límite fijo. Estas palabras excluyen notificaciones aunque también coincidan con una regla positiva. No distingue mayúsculas ni tildes y funciona por fragmentos. Nunca elimina movimientos del Excel.");info.setTextColor(MUTED);info.setTextSize(14);info.setPadding(0,dp(8),0,dp(10));root.addView(info);ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));ArrayList<String> saved=BlacklistRules.load(this);for(String s:saved)addRow(s);if(saved.isEmpty())addRow("");LinearLayout actions=new LinearLayout(this);Button add=new Button(this);add.setText("+ Agregar regla");add.setAllCaps(false);Button save=new Button(this);save.setText("Guardar");save.setAllCaps(false);actions.addView(add,new LinearLayout.LayoutParams(0,dp(54),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(54),1);sp.setMargins(dp(8),0,0,0);actions.addView(save,sp);root.addView(actions);setContentView(root);add.setOnClickListener(v->addRow(""));save.setOnClickListener(v->saveRules());}
 private void addRow(String text){Row r=new Row();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);EditText w=new EditText(this);w.setHint("Palabra o frase a excluir");w.setText(text);w.setTextColor(TEXT);w.setHintTextColor(MUTED);Button del=new Button(this);del.setText("×");del.setTextSize(20);row.addView(w,new LinearLayout.LayoutParams(0,dp(56),1));row.addView(del,new LinearLayout.LayoutParams(dp(48),dp(48)));r.word=w;r.view=row;rows.add(r);list.addView(row);del.setOnClickListener(v->{if(rows.size()==1){w.setText("");return;}rows.remove(r);list.removeView(row);});}
 private void saveRules(){ArrayList<String>x=new ArrayList<>();for(Row r:rows){String s=r.word.getText().toString().trim();if(!s.isEmpty())x.add(s);}BlacklistRules.save(this,x);Toast.makeText(this,"Lista negra guardada",Toast.LENGTH_SHORT).show();finish();}
}
