package com.pablo.controlgastos;

import android.app.*;import android.os.Bundle;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;

public class BlacklistActivity extends Activity{
 private final ArrayList<EditText> words=new ArrayList<>();
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);build();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 private void build(){boolean l=ThemePrefs.isLight(this);int bg=l?Color.rgb(246,248,249):Color.rgb(11,18,24),text=l?Color.rgb(31,38,44):Color.rgb(242,245,247),muted=l?Color.DKGRAY:Color.LTGRAY;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(14),dp(14),dp(14));root.setBackgroundColor(bg);TextView t=new TextView(this);t.setText("Lista negra de notificaciones");t.setTextSize(24);t.setTextColor(text);root.addView(t);TextView info=new TextView(this);info.setText("Estas palabras excluyen notificaciones aunque también coincidan con una regla positiva. No distingue mayúsculas, minúsculas ni tildes y funciona por fragmentos. Solo se aplica a notificaciones: nunca elimina movimientos del Excel.");info.setTextColor(muted);info.setTextSize(14);info.setPadding(0,dp(8),0,dp(10));root.addView(info);ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ArrayList<String> saved=BlacklistRules.load(this);for(int i=0;i<BlacklistRules.MAX_RULES;i++){LinearLayout row=new LinearLayout(this);TextView n=new TextView(this);n.setText(String.valueOf(i+1));n.setTextColor(muted);n.setGravity(Gravity.CENTER);row.addView(n,new LinearLayout.LayoutParams(dp(34),dp(52)));EditText w=new EditText(this);w.setHint("Palabra o frase a excluir");w.setTextColor(text);w.setHintTextColor(muted);if(i<saved.size())w.setText(saved.get(i));words.add(w);row.addView(w,new LinearLayout.LayoutParams(0,dp(52),1));list.addView(row);}sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button save=new Button(this);save.setText("Guardar lista negra");save.setOnClickListener(v->{ArrayList<String>x=new ArrayList<>();for(EditText e:words)x.add(e.getText().toString());BlacklistRules.save(this,x);Toast.makeText(this,"Lista negra guardada",Toast.LENGTH_SHORT).show();finish();});root.addView(save);setContentView(root);}
}
