package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class BudgetActivity extends Activity{
 private ExpenseDb db;private LinearLayout table;private TextView yearTitle,summary;private Spinner currency;private int year,BG,CARD,TEXT,MUTED,GREEN,RED,YELLOW;private final String[] MONTHS={"Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Set","Oct","Nov","Dic"};private DecimalFormat money;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new ExpenseDb(this);year=Calendar.getInstance().get(Calendar.YEAR);DecimalFormatSymbols s=new DecimalFormatSymbols(new Locale("es","UY"));s.setGroupingSeparator('.');s.setDecimalSeparator(',');money=new DecimalFormat("#,##0.00",s);initPalette();build();refresh();}
 private void initPalette(){boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);GREEN=Color.rgb(55,180,105);RED=Color.rgb(225,85,85);YELLOW=Color.rgb(255,193,7);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(8),dp(7),dp(8),dp(7));return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,12));return b;}
 private LinearLayout.LayoutParams cellLp(int w,int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(w),dp(h));p.setMargins(0,0,dp(6),dp(6));return p;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(14),i.getSystemWindowInsetTop()+dp(22),dp(14),i.getSystemWindowInsetBottom()+dp(10));return i;});root.requestApplyInsets();TextView title=tv("Presupuesto y proyección",27,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title);root.addView(tv("Cada mes muestra el gasto real, tu plan y dos referencias: el mes anterior y el mismo mes del año anterior. Tocá una celda para usar una referencia o escribir tu propio presupuesto.",14,MUTED));LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER_VERTICAL);Button prev=btn("‹"),next=btn("›");yearTitle=tv("",20,TEXT);yearTitle.setGravity(Gravity.CENTER);yearTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);currency=new Spinner(this);currency.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"UYU","USD"}));controls.addView(prev,new LinearLayout.LayoutParams(dp(48),dp(48)));controls.addView(yearTitle,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));controls.addView(currency,new LinearLayout.LayoutParams(dp(95),dp(48)));root.addView(controls);LinearLayout actions=new LinearLayout(this);Button copy=btn("Proyectar desde año anterior"),current=btn("Ir al año actual");actions.addView(copy,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(52),1);cp.setMargins(dp(8),0,0,0);actions.addView(current,cp);root.addView(actions);summary=tv("",16,TEXT);summary.setBackground(bg(CARD,12));summary.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(8),0,dp(8));root.addView(summary,sp);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setFillViewport(false);ScrollView vs=new ScrollView(this);table=new LinearLayout(this);table.setOrientation(LinearLayout.VERTICAL);table.setPadding(0,0,dp(8),dp(12));vs.addView(table);hs.addView(vs,new HorizontalScrollView.LayoutParams(-2,-1));root.addView(hs,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);prev.setOnClickListener(v->{year--;refresh();});next.setOnClickListener(v->{year++;refresh();});current.setOnClickListener(v->{year=Calendar.getInstance().get(Calendar.YEAR);refresh();});copy.setOnClickListener(v->copyPreviousYear());currency.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){refresh();}public void onNothingSelected(android.widget.AdapterView<?>p){}});}
 private String cur(){return currency.getSelectedItem()==null?"UYU":currency.getSelectedItem().toString();}
 private LinkedHashSet<String> categories(){LinkedHashSet<String> out=CategoryPrefs.definedCategories(this);Cursor c=db.getReadableDatabase().rawQuery("SELECT DISTINCT category FROM tx WHERE category IS NOT NULL AND TRIM(category)<>'' ORDER BY category COLLATE NOCASE",null);while(c.moveToNext())out.add(c.getString(0));c.close();return out;}
 private double actual(String cat,int y,int m){Calendar s=Calendar.getInstance();s.clear();s.set(y,m,1,0,0,0);Calendar e=(Calendar)s.clone();e.add(Calendar.MONTH,1);Cursor c=db.getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM tx WHERE type='GASTO' AND currency=? AND category=? AND ts>=? AND ts<?",new String[]{cur(),cat,String.valueOf(s.getTimeInMillis()),String.valueOf(e.getTimeInMillis())});double v=c.moveToFirst()?c.getDouble(0):0;c.close();return v;}
 private double[][] actuals(ArrayList<String> cats){double[][] a=new double[cats.size()][12];for(int i=0;i<cats.size();i++)for(int m=0;m<12;m++)a[i][m]=actual(cats.get(i),year,m);return a;}
 private double previousMonth(String cat,int m){int y=year,mm=m-1;if(mm<0){mm=11;y--;}return actual(cat,y,mm);}private double previousYearSameMonth(String cat,int m){return actual(cat,year-1,m);}
 private SharedPreferences prefs(){return getSharedPreferences("budget_projection",MODE_PRIVATE);}private String key(String cat,int month){return cur()+"|"+year+"|"+month+"|"+cat;}private double projection(String cat,int m){long bits=prefs().getLong(key(cat,m),Double.doubleToLongBits(0));return Double.longBitsToDouble(bits);}private void saveProjection(String cat,int m,double v){SharedPreferences.Editor e=prefs().edit();if(v<=0)e.remove(key(cat,m));else e.putLong(key(cat,m),Double.doubleToLongBits(v));e.apply();}
 private void refresh(){if(table==null||yearTitle==null)return;yearTitle.setText(String.valueOf(year));table.removeAllViews();ArrayList<String> cats=new ArrayList<>(categories());double[][] act=actuals(cats);addHeader();double totalActual=0,totalPlan=0;double[] ma=new double[12],mp=new double[12];for(int i=0;i<cats.size();i++){String cat=cats.get(i);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(cat,14,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setGravity(Gravity.CENTER_VERTICAL);name.setBackground(bg(CategoryPrefs.color(this,cat),10));row.addView(name,cellLp(128,126));for(int m=0;m<12;m++){double a=act[i][m],p=projection(cat,m),pm=previousMonth(cat,m),py=previousYearSameMonth(cat,m);totalActual+=a;totalPlan+=p;ma[m]+=a;mp[m]+=p;final int fm=m;TextView cell=budgetCell(cat,m,a,p,pm,py);cell.setOnClickListener(v->editProjection(cat,fm,p,previousMonth(cat,fm),previousYearSameMonth(cat,fm)));row.addView(cell,cellLp(142,126));}table.addView(row);}LinearLayout total=new LinearLayout(this);total.setGravity(Gravity.CENTER_VERTICAL);TextView tn=tv("TOTAL",15,TEXT);tn.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tn.setBackground(bg(CARD,10));total.addView(tn,cellLp(128,92));for(int m=0;m<12;m++){TextView c=budgetCell("",m,ma[m],mp[m],0,0);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);total.addView(c,cellLp(142,92));}table.addView(total);double diff=totalActual-totalPlan;String status=totalPlan<=0?"Sin proyección anual":(diff>0?"▲ Por encima: ":"▼ Por debajo: ")+cur()+" "+money.format(Math.abs(diff));summary.setText("Año "+year+" · Real: "+cur()+" "+money.format(totalActual)+" · Proyectado: "+cur()+" "+money.format(totalPlan)+"\n"+status);summary.setTextColor(totalPlan<=0?TEXT:(diff>0?RED:GREEN));}
 private void addHeader(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView c=tv("Categoría",15,TEXT);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.setBackground(bg(CARD,10));h.addView(c,cellLp(128,58));for(String m:MONTHS){TextView v=tv(m,15,TEXT);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setBackground(bg(CARD,10));h.addView(v,cellLp(142,58));}table.addView(h);}
 private TextView budgetCell(String cat,int month,double actual,double plan,double pm,double py){double diff=actual-plan;int color=plan<=0?MUTED:(diff>0.005?RED:(diff<-0.005?GREEN:YELLOW));String status=plan<=0?"Sin plan":(diff>0.005?"▲ +"+money.format(diff):(diff<-0.005?"▼ -"+money.format(-diff):"= En línea"));String refs=cat.isEmpty()?"":"\nMes ant. "+money.format(pm)+"\nAño ant. "+money.format(py);TextView v=tv("Real "+money.format(actual)+"\nPlan "+money.format(plan)+"\n"+status+refs,12,color);v.setGravity(Gravity.CENTER);v.setBackground(bg(CARD,10));v.setPadding(dp(8),dp(7),dp(8),dp(7));v.setLineSpacing(0f,1.04f);return v;}
 private double parseAmount(String raw)throws Exception{String s=raw==null?"":raw.trim().replace(" ","");if(s.isEmpty())return 0;if(s.contains(",")&&s.contains(".")){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(".","").replace(',','.');else s=s.replace(",","");}else if(s.contains(","))s=s.replace(',','.');return Double.parseDouble(s);}
 private void editProjection(String cat,int month,double old,double pm,double py){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),0,dp(20),0);TextView refs=tv("Referencias reales:\n• Mes anterior: "+cur()+" "+money.format(pm)+"\n• Mismo mes del año anterior: "+cur()+" "+money.format(py),14,TEXT);box.addView(refs);EditText e=new EditText(this);e.setHint("Monto proyectado");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(old>0)e.setText(money.format(old));box.addView(e);Button usePm=btn("Usar mes anterior · "+money.format(pm));Button usePy=btn("Usar año anterior · "+money.format(py));box.addView(usePm);box.addView(usePy);AlertDialog dlg=new AlertDialog.Builder(this).setTitle(cat+" · "+MONTHS[month]+" "+year).setView(box).setPositiveButton("Guardar",null).setNeutralButton("Quitar",null).setNegativeButton("Cancelar",null).create();usePm.setOnClickListener(v->{if(pm>0){saveProjection(cat,month,pm);dlg.dismiss();refresh();}});usePy.setOnClickListener(v->{if(py>0){saveProjection(cat,month,py);dlg.dismiss();refresh();}});dlg.setOnShowListener(x->{dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{double val=parseAmount(e.getText().toString());saveProjection(cat,month,val);dlg.dismiss();refresh();}catch(Exception ex){Toast.makeText(this,"Monto inválido",Toast.LENGTH_LONG).show();}});dlg.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{saveProjection(cat,month,0);dlg.dismiss();refresh();});});dlg.show();}
 private void copyPreviousYear(){final int source=year-1;new AlertDialog.Builder(this).setTitle("Proyectar "+year).setMessage("Voy a usar los gastos reales de "+source+" como proyección mensual para "+year+". Podrás editar cada celda y también usar la referencia del mes anterior.").setPositiveButton("Copiar",(d,w)->{ArrayList<String> cats=new ArrayList<>(categories());SharedPreferences.Editor e=prefs().edit();for(String cat:cats)for(int m=0;m<12;m++){double v=actual(cat,source,m);if(v>0)e.putLong(key(cat,m),Double.doubleToLongBits(v));}e.apply();refresh();Toast.makeText(this,"Proyección creada desde "+source,Toast.LENGTH_LONG).show();}).setNegativeButton("Cancelar",null).show();}
}
