package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class BudgetActivity extends Activity{
 private ExpenseDb db;private LinearLayout table;private TextView yearTitle,summary;private Spinner currency;private int year,BG,CARD,TEXT,MUTED,GREEN,RED,YELLOW;private final String[] MONTHS={"Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Set","Oct","Nov","Dic"};private DecimalFormat money;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new ExpenseDb(this);year=Calendar.getInstance().get(Calendar.YEAR);DecimalFormatSymbols s=new DecimalFormatSymbols(new Locale("es","UY"));s.setGroupingSeparator('.');s.setDecimalSeparator(',');money=new DecimalFormat("#,##0.00",s);initPalette();build();refresh();}
 private void initPalette(){boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);GREEN=Color.rgb(55,180,105);RED=Color.rgb(225,85,85);YELLOW=Color.rgb(255,193,7);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(8),dp(7),dp(8),dp(7));return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,12));return b;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(14),i.getSystemWindowInsetTop()+dp(22),dp(14),i.getSystemWindowInsetBottom()+dp(10));return i;});root.requestApplyInsets();
  TextView title=tv("Presupuesto y proyección",27,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title);root.addView(tv("Todas las categorías por mes. Tocá una celda para cargar o cambiar la proyección. El estado muestra si el gasto real está por encima o por debajo del plan.",14,MUTED));
  LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER_VERTICAL);Button prev=btn("‹");Button next=btn("›");yearTitle=tv("",20,TEXT);yearTitle.setGravity(Gravity.CENTER);yearTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);currency=new Spinner(this);currency.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"UYU","USD"}));controls.addView(prev,new LinearLayout.LayoutParams(dp(48),dp(48)));controls.addView(yearTitle,new LinearLayout.LayoutParams(0,dp(48),1));controls.addView(next,new LinearLayout.LayoutParams(dp(48),dp(48)));controls.addView(currency,new LinearLayout.LayoutParams(dp(95),dp(48)));root.addView(controls);
  LinearLayout actions=new LinearLayout(this);Button copy=btn("Proyectar desde año anterior");Button current=btn("Ir al año actual");actions.addView(copy,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(52),1);cp.setMargins(dp(8),0,0,0);actions.addView(current,cp);root.addView(actions);
  summary=tv("",16,TEXT);summary.setBackground(bg(CARD,12));summary.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(8),0,dp(8));root.addView(summary,sp);
  HorizontalScrollView hs=new HorizontalScrollView(this);ScrollView vs=new ScrollView(this);table=new LinearLayout(this);table.setOrientation(LinearLayout.VERTICAL);vs.addView(table);hs.addView(vs,new HorizontalScrollView.LayoutParams(-2,-1));root.addView(hs,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  prev.setOnClickListener(v->{year--;refresh();});next.setOnClickListener(v->{year++;refresh();});current.setOnClickListener(v->{year=Calendar.getInstance().get(Calendar.YEAR);refresh();});copy.setOnClickListener(v->copyPreviousYear());currency.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){refresh();}public void onNothingSelected(android.widget.AdapterView<?>p){}});
 }
 private String cur(){return currency.getSelectedItem()==null?"UYU":currency.getSelectedItem().toString();}
 private LinkedHashSet<String> categories(){LinkedHashSet<String> out=CategoryPrefs.definedCategories(this);Cursor c=db.getReadableDatabase().rawQuery("SELECT DISTINCT category FROM tx WHERE category IS NOT NULL AND TRIM(category)<>'' ORDER BY category COLLATE NOCASE",null);while(c.moveToNext())out.add(c.getString(0));c.close();return out;}
 private double[][] actuals(ArrayList<String> cats){double[][] a=new double[cats.size()][12];Calendar start=Calendar.getInstance();start.clear();start.set(year,Calendar.JANUARY,1,0,0,0);Calendar end=(Calendar)start.clone();end.add(Calendar.YEAR,1);Cursor c=db.getReadableDatabase().rawQuery("SELECT category,amount,ts FROM tx WHERE type='GASTO' AND currency=? AND ts>=? AND ts<?",new String[]{cur(),String.valueOf(start.getTimeInMillis()),String.valueOf(end.getTimeInMillis())});HashMap<String,Integer> ix=new HashMap<>();for(int i=0;i<cats.size();i++)ix.put(cats.get(i),i);while(c.moveToNext()){String cat=c.getString(0);Integer i=ix.get(cat);if(i==null)continue;Calendar d=Calendar.getInstance();d.setTimeInMillis(c.getLong(2));a[i][d.get(Calendar.MONTH)]+=c.getDouble(1);}c.close();return a;}
 private SharedPreferences prefs(){return getSharedPreferences("budget_projection",MODE_PRIVATE);}private String key(String cat,int month){return cur()+"|"+year+"|"+month+"|"+cat;}private double projection(String cat,int m){long bits=prefs().getLong(key(cat,m),Double.doubleToLongBits(0));return Double.longBitsToDouble(bits);}private void saveProjection(String cat,int m,double v){SharedPreferences.Editor e=prefs().edit();if(v<=0)e.remove(key(cat,m));else e.putLong(key(cat,m),Double.doubleToLongBits(v));e.apply();}
 private void refresh(){if(table==null||yearTitle==null)return;yearTitle.setText(String.valueOf(year));table.removeAllViews();ArrayList<String> cats=new ArrayList<>(categories());double[][] act=actuals(cats);addHeader();double totalActual=0,totalPlan=0;double[] ma=new double[12],mp=new double[12];for(int i=0;i<cats.size();i++){String cat=cats.get(i);LinearLayout row=new LinearLayout(this);TextView name=tv(cat,14,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);name.setBackground(bg(CategoryPrefs.color(this,cat),8));row.addView(name,new LinearLayout.LayoutParams(dp(145),dp(74)));for(int m=0;m<12;m++){double a=act[i][m],p=projection(cat,m);totalActual+=a;totalPlan+=p;ma[m]+=a;mp[m]+=p;final int fm=m;TextView cell=budgetCell(cat,m,a,p);cell.setOnClickListener(v->editProjection(cat,fm,p));row.addView(cell,new LinearLayout.LayoutParams(dp(118),dp(74)));}table.addView(row);}
  LinearLayout total=new LinearLayout(this);TextView tn=tv("TOTAL",15,TEXT);tn.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tn.setBackground(bg(CARD,8));total.addView(tn,new LinearLayout.LayoutParams(dp(145),dp(78)));for(int m=0;m<12;m++){TextView c=budgetCell("",m,ma[m],mp[m]);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);total.addView(c,new LinearLayout.LayoutParams(dp(118),dp(78)));}table.addView(total);
  double diff=totalActual-totalPlan;String status=totalPlan<=0?"Sin proyección anual":(diff>0?"▲ Por encima: ":"▼ Por debajo: ")+cur()+" "+money.format(Math.abs(diff));summary.setText("Año "+year+" · Real: "+cur()+" "+money.format(totalActual)+" · Proyectado: "+cur()+" "+money.format(totalPlan)+"\n"+status);summary.setTextColor(totalPlan<=0?TEXT:(diff>0?RED:GREEN));}
 private void addHeader(){LinearLayout h=new LinearLayout(this);TextView c=tv("Categoría",15,TEXT);c.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.setBackground(bg(CARD,8));h.addView(c,new LinearLayout.LayoutParams(dp(145),dp(52)));for(String m:MONTHS){TextView v=tv(m,15,TEXT);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setBackground(bg(CARD,8));h.addView(v,new LinearLayout.LayoutParams(dp(118),dp(52)));}table.addView(h);}
 private TextView budgetCell(String cat,int month,double actual,double plan){double diff=actual-plan;int color=plan<=0?MUTED:(diff>0.005?RED:(diff<-0.005?GREEN:YELLOW));String status=plan<=0?"Sin plan":(diff>0.005?"▲ +"+money.format(diff):(diff<-0.005?"▼ -"+money.format(-diff):"= En línea"));TextView v=tv("Real "+money.format(actual)+"\nPlan "+money.format(plan)+"\n"+status,12,color);v.setGravity(Gravity.CENTER);v.setBackground(bg(CARD,8));v.setPadding(dp(5),dp(5),dp(5),dp(5));return v;}
 private void editProjection(String cat,int month,double old){EditText e=new EditText(this);e.setHint("Monto proyectado");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);if(old>0)e.setText(money.format(old).replace(".","").replace(',','.'));new AlertDialog.Builder(this).setTitle(cat+" · "+MONTHS[month]+" "+year).setMessage("Ingresá el presupuesto proyectado para este mes en "+cur()+".").setView(e).setPositiveButton("Guardar",(d,w)->{try{double v=Double.parseDouble(e.getText().toString().trim().replace(".","").replace(',','.'));saveProjection(cat,month,v);refresh();}catch(Exception ex){Toast.makeText(this,"Monto inválido",Toast.LENGTH_LONG).show();}}).setNeutralButton("Quitar",(d,w)->{saveProjection(cat,month,0);refresh();}).setNegativeButton("Cancelar",null).show();}
 private void copyPreviousYear(){final int source=year-1;new AlertDialog.Builder(this).setTitle("Proyectar "+year).setMessage("Voy a usar los gastos reales de "+source+" como proyección mensual para "+year+". Podrás editar cada celda después.").setPositiveButton("Copiar",(d,w)->{ArrayList<String> cats=new ArrayList<>(categories());int keep=year;year=source;double[][] prev=actuals(cats);year=keep;SharedPreferences.Editor e=prefs().edit();for(int i=0;i<cats.size();i++)for(int m=0;m<12;m++)if(prev[i][m]>0)e.putLong(key(cats.get(i),m),Double.doubleToLongBits(prev[i][m]));e.apply();refresh();Toast.makeText(this,"Proyección creada desde "+source,Toast.LENGTH_LONG).show();}).setNegativeButton("Cancelar",null).show();}
}
