package com.pablo.controlgastos;
import android.app.*;import android.os.Bundle;import android.content.*;import android.net.Uri;import android.widget.*;import java.util.*;import java.util.regex.*;
import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
public class CaptureStatementActivity extends Activity{
 static final int PICK=4102;TextView status,preview;Button process;String recognized="";
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,60,24,24);status=new TextView(this);status.setText("Elegí una captura del estado de cuenta desde la galería.");r.addView(status);Button choose=new Button(this);choose.setText("Elegir imagen de la galería");r.addView(choose);ScrollView sc=new ScrollView(this);preview=new TextView(this);sc.addView(preview);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));process=new Button(this);process.setText("Procesar y guardar estado");process.setEnabled(false);r.addView(process);setContentView(r);choose.setOnClickListener(v->pick());process.setOnClickListener(v->save());pick();}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,PICK);}
 protected void onActivityResult(int q,int res,Intent data){super.onActivityResult(q,res,data);if(q!=PICK||res!=RESULT_OK||data==null)return;Uri u=data.getData();if(u==null)return;status.setText("Reconociendo texto…");try{InputImage im=InputImage.fromFilePath(this,u);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(im).addOnSuccessListener(t->{recognized=t.getText();preview.setText(recognized);process.setEnabled(!recognized.trim().isEmpty());status.setText("Texto reconocido. Revisalo y procesalo.");}).addOnFailureListener(e->err(e.getMessage()));}catch(Exception e){err(e.getMessage());}}
 void save(){try{Parsed p=parse(recognized);CreditCardDb db=new CreditCardDb(this);long cid=db.card(p.bank,p.last4),sid=db.statement(cid,p.close,p.due,p.total,"UYU");db.clearItems(sid);for(Row x:p.rows)db.item(sid,x.date,x.desc,x.inst,x.amount,"UYU");db.close();new AlertDialog.Builder(this).setTitle("Estado guardado").setMessage("Tarjeta: "+p.bank+" ****"+p.last4+"\nCierre: "+p.close+"\nVencimiento: "+p.due+"\nSaldo contado: $ "+String.format(Locale.US,"%,.2f",p.total)+"\nMovimientos: "+p.rows.size()).setPositiveButton("Aceptar",(d,w)->finish()).show();}catch(Exception e){err(e.getMessage());}}
 static class Row{String date,desc,inst;double amount;}static class Parsed{String bank="BROU MasterCard",last4,close,due;double total;ArrayList<Row> rows=new ArrayList<>();}
 Parsed parse(String text)throws Exception{String f=text.replace('\n',' ').replaceAll("\\s+"," ");Parsed p=new Parsed();Matcher c=Pattern.compile("(?i)TARJETA\\s*(?:No)?[.: ]*([0-9]{4,6})\\s*[*xX]+\\s*([0-9]{4})").matcher(f);if(!c.find())throw new Exception("No pude identificar la tarjeta enmascarada. Usá una captura donde se vea la tabla completa.");p.last4=c.group(2);p.close=find(f,"(?i)Fecha de cierre[: ]+([0-3]?\\d/[01]?\\d/\\d{2,4})");p.due=find(f,"(?i)Vencimiento actual[: ]+([0-3]?\\d/[01]?\\d/\\d{2,4})");String b=find(f,"(?i)Banco[: ]+([A-Za-z ]+MasterCard)");if(!b.isEmpty())p.bank=b.trim();p.total=num(find(f,"(?i)SALDO CONTADO\\s+([0-9][0-9.,]*)"));Matcher m=Pattern.compile("([0-3]?\\d/[01]?\\d/\\d{2,4})\\s+(.{3,80}?)\\s+(-?[0-9][0-9.,]*)\\s+(?:\\.00|0[.,]00|[-–—]+)(?=\\s|$)",Pattern.CASE_INSENSITIVE).matcher(f);while(m.find()){String d=m.group(2).trim();if(d.matches("(?i).*(SALDO ANTERIOR|PAGOS|TOTAL TARJETA).*"))continue;Row x=new Row();x.date=m.group(1);x.desc=d;x.amount=num(m.group(3));x.inst=find(d,"(?i)(CUOTA\\s*0*\\d{1,2}/0*\\d{1,2})");p.rows.add(x);}if(p.close.isEmpty()||p.total<=0)throw new Exception("La captura fue leída, pero faltan datos esenciales (cierre o saldo contado).");return p;}
 String find(String s,String re){Matcher m=Pattern.compile(re).matcher(s);return m.find()?m.group(1):"";}double num(String x){try{String q=x.trim();int c=q.lastIndexOf(','),d=q.lastIndexOf('.');if(c>=0&&d>=0)q=d>c?q.replace(",",""):q.replace(".","").replace(',','.');else if(c>=0)q=(q.length()-c-1==2)?q.replace(',','.'):q.replace(",","");return Double.parseDouble(q);}catch(Exception e){return 0;}}
 void err(String s){new AlertDialog.Builder(this).setTitle("No se pudo procesar la captura").setMessage(s==null?"Error desconocido":s).setPositiveButton("Aceptar",null).show();}
}
