package com.pablo.controlgastos;
import android.app.*;import android.os.Bundle;import android.content.*;import android.net.Uri;import android.graphics.Rect;import android.view.*;import android.widget.*;import java.util.*;import java.util.regex.*;
import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.TextRecognizerOptions;import com.google.mlkit.vision.text.Text;
public class CaptureStatementActivity extends Activity{
 static final int PICK=4102;TextView status,preview;Button process;String recognized="";Text recognizedResult;
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(24,60,24,24);status=new TextView(this);status.setText("Elegí una captura del estado de cuenta desde la galería.");r.addView(status);Button choose=new Button(this);choose.setText("Elegir imagen de la galería");r.addView(choose);ScrollView sc=new ScrollView(this);preview=new TextView(this);sc.addView(preview);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));process=new Button(this);process.setText("Procesar y guardar estado");process.setEnabled(false);r.addView(process);setContentView(r);r.setOnApplyWindowInsetsListener((v,in)->{r.setPadding(24,in.getSystemWindowInsetTop()+18,24,in.getSystemWindowInsetBottom()+18);return in;});r.requestApplyInsets();choose.setOnClickListener(v->pick());process.setOnClickListener(v->save());pick();}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,PICK);}
 protected void onActivityResult(int q,int res,Intent data){super.onActivityResult(q,res,data);if(q!=PICK||res!=RESULT_OK||data==null)return;Uri u=data.getData();if(u==null)return;status.setText("Reconociendo texto…");try{InputImage im=InputImage.fromFilePath(this,u);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(im).addOnSuccessListener(t->{recognizedResult=t;recognized=t.getText();preview.setText(recognized);process.setEnabled(!recognized.trim().isEmpty());status.setText("Texto reconocido. Revisalo y procesalo.");}).addOnFailureListener(e->err(e.getMessage()));}catch(Exception e){err(e.getMessage());}}
 void save(){try{Parsed p=parse(recognizedResult,recognized);CreditCardDb db=new CreditCardDb(this);long cid=db.card(p.bank,p.last4),sid=db.statement(cid,p.close,p.due,p.total,"UYU");db.clearItems(sid);for(Row x:p.rows)db.item(sid,x.date,x.desc,x.inst,x.amount,x.currency);db.close();int cuotas=0;for(Row x:p.rows)if(x.inst!=null&&!x.inst.isEmpty())cuotas++;new AlertDialog.Builder(this).setTitle("Estado guardado").setMessage("Tarjeta: "+p.bank+" ****"+p.last4+"\nCierre: "+p.close+"\nVencimiento: "+p.due+"\nSaldo contado: $ "+String.format(Locale.US,"%,.2f",p.total)+"\nMovimientos: "+p.rows.size()+"\nCompras en cuotas: "+cuotas).setPositiveButton("Aceptar",(d,w)->finish()).show();}catch(Exception e){err(e.getMessage());}}
 static class Row{String date,desc,inst,currency="UYU";double amount;}static class Parsed{String bank="BROU MasterCard",last4,close,due;double total;ArrayList<Row> rows=new ArrayList<>();}static class O{String s;Rect r;O(String x,Rect y){s=x;r=y;}}
 Parsed parse(Text result,String text)throws Exception{String f=text.replace('\n',' ').replaceAll("\\s+"," ");Parsed p=new Parsed();Matcher c=Pattern.compile("(?i)TARJETA\\s*(?:No)?[.: ]*([0-9]{4,8})\\s*[*xX]+\\s*([0-9]{4})").matcher(f);if(!c.find())throw new Exception("No pude identificar la tarjeta enmascarada. Usá una captura donde se vea la tabla completa.");p.last4=c.group(2);p.close=find(f,"(?i)Fecha de cierre[: ]+([0-3]?\\d/[01]?\\d/\\d{2,4})");p.due=find(f,"(?i)Vencimiento actual[: ]+([0-3]?\\d/[01]?\\d/\\d{2,4})");String b=find(f,"(?i)Banco[: ]+([^$]{2,30}?)(?=\\s+(?:Pr[oó]ximo|Fecha|Vencimiento|L[ií]mite|Cr[eé]dito|Origen|\\$|USD)|$)");if(!b.isEmpty())p.bank=b.trim();p.total=num(find(f,"(?i)SALDO CONTADO\\s+([0-9][0-9.,]*)"));if(result!=null)parseGeometry(result,p);if(p.rows.isEmpty())parseLines(text,p);if(p.close.isEmpty()||p.total<=0)throw new Exception("La captura fue leída, pero faltan datos esenciales (cierre o saldo contado).");return p;}
 void parseGeometry(Text t,Parsed p){ArrayList<O> els=new ArrayList<>();for(Text.TextBlock b:t.getTextBlocks())for(Text.Line l:b.getLines())for(Text.Element e:l.getElements())if(e.getBoundingBox()!=null)els.add(new O(e.getText(),e.getBoundingBox()));ArrayList<O> dates=new ArrayList<>();Pattern dp=Pattern.compile("^[0-3]?\\d/[01]?\\d/\\d{2,4}$");for(O o:els)if(dp.matcher(o.s.trim()).matches())dates.add(o);Collections.sort(dates,(a,b)->Integer.compare(a.r.centerY(),b.r.centerY()));for(O d:dates){int h=Math.max(16,d.r.height()),cy=d.r.centerY();ArrayList<O> same=new ArrayList<>();for(O o:els)if(Math.abs(o.r.centerY()-cy)<=Math.max(h,o.r.height())*.75&&o.r.left>d.r.right-5)same.add(o);Collections.sort(same,(a,b)->Integer.compare(a.r.left,b.r.left));StringBuilder desc=new StringBuilder();ArrayList<O> nums=new ArrayList<>();for(O o:same){String z=o.s.trim();if(isMoney(z))nums.add(o);else if(!z.equalsIgnoreCase("Origen")&&!z.equalsIgnoreCase("USD")&&!z.equals("$")){if(desc.length()>0)desc.append(' ');desc.append(z);}}String ds=desc.toString().replaceAll("\\s+"," ").trim();if(ds.isEmpty()||skip(ds)||nums.isEmpty())continue;O amount=nums.get(0);Row x=new Row();x.date=d.s.trim();x.desc=ds;x.inst=installment(ds);x.amount=num(amount.s);if(x.amount<=0)continue;p.rows.add(x);}}
 void parseLines(String text,Parsed p){String[] lines=text.split("\\r?\\n");Pattern start=Pattern.compile("^([0-3]?\\d/[01]?\\d/\\d{2,4})\\s+(.+)$");for(int i=0;i<lines.length;i++){Matcher m=start.matcher(lines[i].trim());if(!m.find())continue;String date=m.group(1),ds=m.group(2).trim();if(skip(ds))continue;String inst=installment(ds);if(inst.isEmpty())continue;double amount=0;for(int j=i;j<Math.min(lines.length,i+5);j++){Matcher a=Pattern.compile("(?:^|\\s)([0-9][0-9.,]{2,})(?:\\s|$)").matcher(lines[j]);while(a.find()){double n=num(a.group(1));if(n>0){amount=n;break;}}if(amount>0)break;}if(amount<=0)continue;boolean exists=false;for(Row r:p.rows)if(r.date.equals(date)&&installment(r.desc).equals(inst)){exists=true;break;}if(!exists){Row x=new Row();x.date=date;x.desc=ds;x.inst=inst;x.amount=amount;p.rows.add(x);}}}
 boolean skip(String s){return s.matches("(?i).*(SALDO ANTERIOR|PAGOS|TOTAL TARJETA|SALDO CONTADO|FECHA DE CIERRE|VENCIMIENTO).* ")||s.matches("(?i).*(SALDO ANTERIOR|PAGOS|TOTAL TARJETA|SALDO CONTADO).* ")||s.matches("(?i)^(SALDO ANTERIOR|PAGOS|TOTAL TARJETA.*|SALDO CONTADO)$");}
 String installment(String s){Matcher m=Pattern.compile("(?i)CUOTA\\s*0*(\\d{1,2})\\s*[/\\-]\\s*0*(\\d{1,2})").matcher(s);return m.find()?"CUOTA "+String.format(Locale.US,"%02d/%02d",Integer.parseInt(m.group(1)),Integer.parseInt(m.group(2))):"";}
 boolean isMoney(String s){String z=s.trim().replace("$","");return z.matches("-?\\s*[0-9][0-9.,]*")||z.matches("\\.[0-9]{2}");}
 String find(String s,String re){Matcher m=Pattern.compile(re).matcher(s);return m.find()?m.group(1):"";}double num(String x){try{String q=x.replace("$","").replaceAll("\\s+","").trim();if(q.startsWith("-"))q=q.substring(1);int c=q.lastIndexOf(','),d=q.lastIndexOf('.');if(c>=0&&d>=0)q=d>c?q.replace(",",""):q.replace(".","").replace(',','.');else if(c>=0)q=(q.length()-c-1==2)?q.replace(',','.'):q.replace(",","");return Double.parseDouble(q);}catch(Exception e){return 0;}}
 void err(String s){new AlertDialog.Builder(this).setTitle("No se pudo procesar la captura").setMessage(s==null?"Error desconocido":s).setPositiveButton("Aceptar",null).show();}
}
