package com.pablo.controlgastos;

import android.app.*;import android.os.Bundle;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;
import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.latin.TextRecognizerOptions;

public class CaptureStatementActivity extends Activity{
 static final int PICK=4102;TextView status,preview;String recognized="";
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);build();pick();}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 void build(){boolean light=ThemePrefs.isLight(this);int bg=light?0xfff6f8f9:0xff0b1218,fg=light?0xff1f262c:0xfff2f5f7;LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(28),dp(20),dp(20));root.setBackgroundColor(bg);TextView title=new TextView(this);title.setText("Lectura de captura");title.setTextSize(26);title.setTextColor(fg);root.addView(title);status=new TextView(this);status.setText("Seleccioná una captura de un estado de cuenta desde la galería.");status.setTextSize(15);status.setTextColor(fg);status.setPadding(0,dp(12),0,dp(12));root.addView(status);Button choose=new Button(this);choose.setText("Elegir imagen de la galería");choose.setAllCaps(false);root.addView(choose);choose.setOnClickListener(v->pick());ScrollView sc=new ScrollView(this);preview=new TextView(this);preview.setTextColor(fg);preview.setTextSize(13);preview.setPadding(0,dp(14),0,dp(14));sc.addView(preview);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button process=new Button(this);process.setText("Procesar y guardar estado");process.setAllCaps(false);process.setEnabled(false);root.addView(process);process.setOnClickListener(v->save());setContentView(root);process.setTag("process");}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req!=PICK||res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();status.setText("Leyendo texto de la captura…");preview.setText("");try{InputImage image=InputImage.fromFilePath(this,u);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(image).addOnSuccessListener(t->{recognized=t.getText();preview.setText(recognized);status.setText(recognized.trim().isEmpty()?"No se pudo reconocer texto en la imagen.":"Texto reconocido. Revisalo y tocá Procesar y guardar estado.");View v=findViewById(android.R.id.content);Button p=findButton((ViewGroup)v,"process");if(p!=null)p.setEnabled(!recognized.trim().isEmpty());}).addOnFailureListener(e->error("No se pudo leer la imagen: "+e.getMessage()));}catch(Exception e){error("No se pudo abrir la imagen: "+e.getMessage());}}
 Button findButton(ViewGroup g,String tag){for(int i=0;i<g.getChildCount();i++){View v=g.getChildAt(i);if(v instanceof Button&&tag.equals(v.getTag()))return(Button)v;if(v instanceof ViewGroup){Button b=findButton((ViewGroup)v,tag);if(b!=null)return b;}}return null;}
 void save(){try{EmailSyncEngine.CardImportResult r=EmailSyncEngine.importCardCapture(this,recognized);new AlertDialog.Builder(this).setTitle("Estado procesado").setMessage("Tarjeta: **** "+r.last4+"\nCierre: "+r.closeDate+"\nVencimiento: "+r.dueDate+"\nSaldo: $ "+String.format(java.util.Locale.US,"%,.2f",r.total)+"\nMovimientos: "+r.items).setPositiveButton("Aceptar",(d,w)->finish()).show();}catch(Exception e){error(e.getMessage()==null?e.toString():e.getMessage());}}
 void error(String s){status.setText(s);new AlertDialog.Builder(this).setTitle("No se pudo procesar la captura").setMessage(s).setPositiveButton("Aceptar",null).show();}
}
