package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.regex.*;
public class CardBrowserActivity extends Activity{
 CreditCardDb db;LinearLayout body;TextView title,summary;Button prevMonth,nextMonth,prevCard,nextCard;ArrayList<Card> cards=new ArrayList<>();ArrayList<Stmt> stmts=new ArrayList<>();int cardIndex=0,monthIndex=0;int BG,TEXT,CARD,MUTED,LINE;
 static class Card{String name,last;long id;Card(long i,String n,String l){id=i;name=n;last=l;}}static class Stmt{long id;String close,due,cur;double total;Stmt(long i,String c,String d,double t,String u){id=i;close=c;due=d;total=t;cur=u;}}
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new CreditCardDb(this);boolean l=ThemePrefs.isLight(this);BG=l?0xfff6f8f9:0xff0b1218;TEXT=l?0xff1f262c:0xfff2f5f7;CARD=l?Color.WHITE:0xff162029;MUTED=l?0xff5f6970:0xff9ea9b2;LINE=l?0xffd7dde1:0xff31404b;loadCards();String last=getIntent().getStringExtra("last4");for(int i=0;i<cards.size();i++)if(cards.get(i).last.equals(last))cardIndex=i;build();showCard();}
 void loadCards(){Cursor c=db.getReadableDatabase().rawQuery("SELECT id,name,last4 FROM cards ORDER BY id",null);while(c.moveToNext())cards.add(new Card(c.getLong(0),c.getString(1),c.getString(2)));c.close();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(52),dp(18),dp(16));root.setBackgroundColor(BG);title=tv("",25);root.addView(title);LinearLayout cb=new LinearLayout(this);prevCard=btn("‹ Tarjeta");nextCard=btn("Tarjeta ›");cb.addView(prevCard,new LinearLayout.LayoutParams(0,-2,1));cb.addView(nextCard,new LinearLayout.LayoutParams(0,-2,1));root.addView(cb);LinearLayout mb=new LinearLayout(this);prevMonth=btn("‹ Mes anterior");nextMonth=btn("Mes siguiente ›");mb.addView(prevMonth,new LinearLayout.LayoutParams(0,-2,1));mb.addView(nextMonth,new LinearLayout.LayoutParams(0,-2,1));root.addView(mb);summary=tv("",17);root.addView(summary);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);prevCard.setOnClickListener(v->{if(cards.size()>1){cardIndex=(cardIndex-1+cards.size())%cards.size();monthIndex=0;showCard();}});nextCard.setOnClickListener(v->{if(cards.size()>1){cardIndex=(cardIndex+1)%cards.size();monthIndex=0;showCard();}});prevMonth.setOnClickListener(v->{if(monthIndex+1<stmts.size()){monthIndex++;render();}});nextMonth.setOnClickListener(v->{if(monthIndex>0){monthIndex--;render();}else if(!stmts.isEmpty())simulate(stmts.get(0));});}
 void showCard(){if(cards.isEmpty()){title.setText("Tarjetas");summary.setText("No hay tarjetas importadas.");return;}Card c=cards.get(cardIndex);title.setText(c.name+" •••• "+c.last);stmts.clear();Cursor x=db.getReadableDatabase().rawQuery("SELECT id,close_date,due_date,total,currency FROM statements WHERE card_id=? ORDER BY id DESC",new String[]{""+c.id});while(x.moveToNext())stmts.add(new Stmt(x.getLong(0),x.getString(1),x.getString(2),x.getDouble(3),x.getString(4)));x.close();monthIndex=0;render();}
 TextView cell(String text,float weight,int gravity,boolean header){TextView v=tv(text,header?13:14);v.setGravity(gravity|Gravity.CENTER_VERTICAL);v.setSingleLine(false);v.setBackgroundColor(CARD);if(header)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,weight);lp.setMargins(0,0,dp(1),dp(1));v.setLayoutParams(lp);return v;}
 void tableHeader(){LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setBackgroundColor(LINE);h.addView(cell("Fecha",1.05f,Gravity.START,true));h.addView(cell("Descripción",2.45f,Gravity.START,true));h.addView(cell("Cuota",.9f,Gravity.CENTER,true));h.addView(cell("Monto (UYU)",1.25f,Gravity.END,true));body.addView(h,new LinearLayout.LayoutParams(-1,dp(48)));}
 void tableRow(String date,String desc,String cuota,double amount,String currency){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setBackgroundColor(LINE);row.setMinimumHeight(dp(52));row.addView(cell(date,1.05f,Gravity.START,false));row.addView(cell(desc,2.45f,Gravity.START,false));row.addView(cell(cuota,.9f,Gravity.CENTER,false));row.addView(cell(("USD".equalsIgnoreCase(currency)?"USD ":"")+money(amount),1.25f,Gravity.END,false));body.addView(row,new LinearLayout.LayoutParams(-1,-2));}
 void render(){body.removeAllViews();if(stmts.isEmpty()){summary.setText("Sin estados importados");prevMonth.setEnabled(false);nextMonth.setEnabled(false);return;}Stmt s=stmts.get(monthIndex);summary.setText("Cierre: "+s.close+"   ·   Vence: "+s.due+"\nPago contado: "+s.cur+" "+money(s.total)+(monthIndex==0?"\nMes siguiente: simulación automática":""));prevMonth.setEnabled(monthIndex+1<stmts.size());nextMonth.setEnabled(true);nextMonth.setText(monthIndex==0?"Simular mes siguiente ›":"Mes siguiente ›");TextView section=tv("Compras y cuotas",20);section.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(section);tableHeader();Cursor c=db.getReadableDatabase().rawQuery("SELECT tx_date,description,installment,amount,currency FROM installments WHERE statement_id=? ORDER BY id",new String[]{""+s.id});int count=0,installmentCount=0;double installmentTotal=0;while(c.moveToNext()){int[] q=q(c.getString(2));String cuota=q==null?"Sin cuotas":String.format(Locale.US,"%02d / %02d",q[0],q[1]);String desc=c.getString(1)==null?"":c.getString(1).replaceAll("(?i)\\s*CUOTA\\s*0*\\d{1,2}/0*\\d{1,2}\\s*"," ").replaceAll("\\s+"," ").trim();double amount=c.getDouble(3);String cur=c.getString(4);tableRow(c.getString(0),desc,cuota,amount,cur);count++;if(q!=null){installmentCount++;if(!"USD".equalsIgnoreCase(cur))installmentTotal+=amount;}}c.close();TextView foot=tv("Compras: "+count+"   ·   En cuotas: "+installmentCount+"   ·   Total cuotas del mes: UYU "+money(installmentTotal),14);foot.setTextColor(MUTED);foot.setPadding(dp(8),dp(14),dp(8),dp(14));body.addView(foot);}
 int[] q(String raw){if(raw==null)return null;Matcher m=Pattern.compile("(?i)CUOTA\\s*0*(\\d{1,2})/0*(\\d{1,2})").matcher(raw);if(!m.find())return null;return new int[]{Integer.parseInt(m.group(1)),Integer.parseInt(m.group(2))};}
 static class Row{String d,u;int a,t;double m;Switch sw;Row(String x,String y,int z,int w,double n){d=x;u=y;a=z;t=w;m=n;}}
 void simulate(Stmt s){ArrayList<Row> rows=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT description,installment,amount,currency FROM installments WHERE statement_id=? ORDER BY id",new String[]{""+s.id});while(c.moveToNext()){int[] q=q(c.getString(1));if(q!=null)rows.add(new Row(c.getString(0),c.getString(3),q[0],q[1],c.getDouble(2)));}c.close();if(rows.isEmpty()){new AlertDialog.Builder(this).setTitle("Mes siguiente").setMessage("No hay compras en cuotas para proyectar.").setPositiveButton("Cerrar",null).show();return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);TextView total=tv("",20);total.setBackgroundColor(CARD);box.addView(total);TextView note=tv("Estado real = último estado importado. Próximo estimado = solo cuotas conocidas que continúan. La diferencia se actualiza al activar o excluir cuotas. No incluye compras futuras, intereses, seguros, impuestos ni otros cargos todavía desconocidos.",13);note.setTextColor(MUTED);box.addView(note);Button restore=btn("Restaurar escenario");box.addView(restore);for(Row r:rows){boolean cont=r.a<r.t;r.sw=new Switch(this);r.sw.setChecked(cont);r.sw.setEnabled(cont);r.sw.setText(r.d+"\n"+(cont?("Próximo: cuota "+(r.a+1)+" de "+r.t):"Finaliza este mes")+" · "+r.u+" "+money(r.m));box.addView(r.sw);r.sw.setOnCheckedChangeListener((v,on)->calc(rows,total,s));}restore.setOnClickListener(v->{for(Row r:rows)if(r.a<r.t)r.sw.setChecked(true);calc(rows,total,s);});calc(rows,total,s);ScrollView sc=new ScrollView(this);sc.addView(box);new AlertDialog.Builder(this).setTitle(cards.get(cardIndex).name+" · Mes siguiente simulado").setView(sc).setPositiveButton("Cerrar",null).show();}
 void calc(ArrayList<Row> rows,TextView v,Stmt s){LinkedHashMap<String,Double> sums=new LinkedHashMap<>();int end=0,off=0;for(Row r:rows){if(r.a>=r.t){end++;continue;}if(r.sw.isChecked())sums.put(r.u,sums.containsKey(r.u)?sums.get(r.u)+r.m:r.m);else off++;}String cur=s.cur==null||s.cur.trim().isEmpty()?"UYU":s.cur;double projected=sums.containsKey(cur)?sums.get(cur):0;double diff=projected-s.total;StringBuilder b=new StringBuilder("ESTADO REAL\n").append(cur).append(" ").append(money(s.total)).append("\n\nPRÓXIMO ESTIMADO\n").append(cur).append(" ").append(money(projected)).append("\n\nDIFERENCIA\n").append(diff>0?"+":"").append(cur).append(" ").append(money(diff));for(Map.Entry<String,Double> e:sums.entrySet())if(!e.getKey().equals(cur))b.append("\n").append(e.getKey()).append(" ").append(money(e.getValue())).append(" (estimado)");b.append("\n\nFinalizan este mes: ").append(end).append(" · Excluidas: ").append(off);v.setText(b.toString());}
 String money(double x){return String.format(new Locale("es","UY"),"%,.2f",x);}
}
