package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class CategorySettingsActivity extends Activity{
 private ExpenseDb db;private LinearLayout list;private int BG,CARD,TEXT,MUTED;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new ExpenseDb(this);boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);build();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(8),dp(7),dp(8),dp(7));return v;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(14),i.getSystemWindowInsetTop()+dp(22),dp(14),i.getSystemWindowInsetBottom()+dp(12));return i;});root.requestApplyInsets();TextView t=tv("Categorías",26,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);root.addView(tv("Tocá una categoría para renombrarla. Tocá el color para cambiarlo. Las modificaciones se aplican también a los movimientos existentes.",14,MUTED));Button add=new Button(this);add.setText("+ Nueva categoría");add.setAllCaps(false);add.setOnClickListener(v->editCategory(null));root.addView(add);ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();}
 private void refresh(){list.removeAllViews();LinkedHashSet<String> cats=new LinkedHashSet<>(Arrays.asList("Supermercado","Comida","Combustible","Transporte","Servicios","Salud","Tecnología","Regalos","Educación","Vivienda","Pagos","Transferencias","Otros"));Cursor c=db.getReadableDatabase().rawQuery("SELECT DISTINCT category FROM tx WHERE category IS NOT NULL AND TRIM(category)<>'' ORDER BY category COLLATE NOCASE",null);while(c.moveToNext())cats.add(c.getString(0));c.close();for(String cat:cats)addRow(cat);}
 private void addRow(String cat){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(8),dp(10),dp(8));row.setBackground(bg(CARD,12));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(5),0,dp(5));row.setLayoutParams(rp);View sw=new View(this);sw.setBackground(bg(CategoryPrefs.color(this,cat),100));row.addView(sw,new LinearLayout.LayoutParams(dp(32),dp(32)));TextView name=tv(cat,17,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);row.addView(name,new LinearLayout.LayoutParams(0,-2,1));Button color=new Button(this);color.setText("Color");color.setAllCaps(false);row.addView(color,new LinearLayout.LayoutParams(dp(82),dp(44)));row.setOnClickListener(v->editCategory(cat));color.setOnClickListener(v->chooseColor(cat,sw));list.addView(row);}
 private void chooseColor(String cat,View sw){int current=CategoryPrefs.color(this,cat),idx=0;for(int i=0;i<CategoryPrefs.PALETTE.length;i++)if(CategoryPrefs.PALETTE[i]==current){idx=i;break;}int next=CategoryPrefs.PALETTE[(idx+1)%CategoryPrefs.PALETTE.length];CategoryPrefs.setColor(this,cat,next);sw.setBackground(bg(next,100));}
 private void editCategory(String oldName){EditText e=new EditText(this);e.setHint("Nombre de la categoría");if(oldName!=null)e.setText(oldName);new AlertDialog.Builder(this).setTitle(oldName==null?"Nueva categoría":"Editar categoría").setView(e).setPositiveButton("Guardar",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())return;if(oldName!=null&&!oldName.equals(n)){db.getWritableDatabase().execSQL("UPDATE tx SET category=? WHERE category=?",new Object[]{n,oldName});CategoryPrefs.rename(this,oldName,n);}else if(oldName==null)CategoryPrefs.setColor(this,n,CategoryPrefs.PALETTE[0]);refresh();}).setNegativeButton("Cancelar",null).show();}
}
