package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class CategorySettingsActivity extends Activity{
 private LinearLayout list;private int BG,CARD,TEXT,MUTED;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);build();}
 @Override protected void onResume(){super.onResume();if(list!=null)refresh();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(8),dp(7),dp(8),dp(7));return v;}
 private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(14),i.getSystemWindowInsetTop()+dp(22),dp(14),i.getSystemWindowInsetBottom()+dp(12));return i;});root.requestApplyInsets();TextView t=tv("Categorías",26,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);root.addView(tv("Las categorías salen de la Lista blanca. Acá podés cambiar su color o renombrarlas; al renombrar, también se actualizan las reglas y los movimientos existentes. 'Otros' queda reservado para lo que no coincide con ninguna regla.",14,MUTED));Button rules=btn("Editar Lista blanca");rules.setOnClickListener(v->startActivity(new Intent(this,RulesActivity.class)));root.addView(rules);Button clean=btn("🧹 Eliminar categorías vacías (12 meses)");clean.setOnClickListener(v->showCleanup());root.addView(clean);root.addView(tv("La limpieza solo propone categorías que no tuvieron ningún gasto durante los últimos 12 meses. No elimina movimientos y nunca elimina 'Otros'.",13,MUTED));ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();}
 private void refresh(){list.removeAllViews();for(String cat:DetectionRules.categoryNames(this))addRow(cat);}
 private void addRow(String cat){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(8),dp(10),dp(8));row.setBackground(bg(CARD,12));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(5),0,dp(5));row.setLayoutParams(rp);View sw=new View(this);sw.setBackground(bg(CategoryPrefs.color(this,cat),100));row.addView(sw,new LinearLayout.LayoutParams(dp(32),dp(32)));TextView name=tv(cat,17,TEXT);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);row.addView(name,new LinearLayout.LayoutParams(0,-2,1));Button color=btn("Color");row.addView(color,new LinearLayout.LayoutParams(dp(82),dp(44)));color.setOnClickListener(v->chooseColor(cat,sw));if(!cat.equalsIgnoreCase("Otros"))row.setOnClickListener(v->renameCategory(cat));list.addView(row);}
 private void chooseColor(String cat,View sw){int current=CategoryPrefs.color(this,cat),idx=0;for(int i=0;i<CategoryPrefs.PALETTE.length;i++)if(CategoryPrefs.PALETTE[i]==current){idx=i;break;}int next=CategoryPrefs.PALETTE[(idx+1)%CategoryPrefs.PALETTE.length];CategoryPrefs.setColor(this,cat,next);sw.setBackground(bg(next,100));}
 private void renameCategory(String oldName){EditText e=new EditText(this);e.setText(oldName);new AlertDialog.Builder(this).setTitle("Renombrar categoría").setMessage("Esto actualizará la Lista blanca y los movimientos existentes.").setView(e).setPositiveButton("Guardar",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty()||n.equalsIgnoreCase("Otros"))return;if(!oldName.equals(n)){DetectionRules.renameCategory(this,oldName,n);CategoryPrefs.rename(this,oldName,n);DetectionRules.reclassifyExisting(this);refresh();}}).setNegativeButton("Cancelar",null).show();}
 private void showCleanup(){ArrayList<String> empty=EmptyCategoryCleanup.findEmptyLast12Months(this);if(empty.isEmpty()){new AlertDialog.Builder(this).setTitle("Categorías vacías").setMessage("No hay categorías sin gastos en los últimos 12 meses.").setPositiveButton("Cerrar",null).show();return;}StringBuilder msg=new StringBuilder("Estas categorías no tuvieron gastos en los últimos 12 meses:\n\n");for(String s:empty)msg.append("• ").append(s).append('\n');msg.append("\nSe quitarán de la Lista blanca y de la lista de categorías. Los movimientos históricos no se borran.");new AlertDialog.Builder(this).setTitle("Eliminar categorías vacías").setMessage(msg.toString()).setPositiveButton("Eliminar",(d,w)->{int n=EmptyCategoryCleanup.removeCategories(this,empty);Toast.makeText(this,"Categorías eliminadas: "+n,Toast.LENGTH_LONG).show();refresh();}).setNegativeButton("Cancelar",null).show();}
}
