package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.text.InputType;import android.view.*;import android.widget.*;
public final class CreditCardsOverlay{
 private CreditCardsOverlay(){}
 public static void install(Activity a){View root=a.findViewById(android.R.id.content);if(root==null)return;if(a instanceof HomeActivity)root.post(()->injectHome(a,root));else if(a instanceof CreditCardsActivity)root.postDelayed(()->enhanceCards(a,root),250);}
 private static void injectHome(Activity a,View root){if(root.findViewWithTag("credit_cards_nav")!=null)return;ViewGroup content=(ViewGroup)root;if(content.getChildCount()==0)return;View v=content.getChildAt(0);if(!(v instanceof LinearLayout))return;LinearLayout outer=(LinearLayout)v;if(outer.getChildCount()==0)return;View last=outer.getChildAt(outer.getChildCount()-1);if(!(last instanceof LinearLayout))return;LinearLayout nav=(LinearLayout)last;Button b=new Button(a);b.setTag("credit_cards_nav");b.setText("▤\nTarjetas");b.setTextSize(11);b.setAllCaps(false);b.setOnClickListener(x->a.startActivity(new Intent(a,CreditCardsActivity.class)));nav.addView(b,new LinearLayout.LayoutParams(0,dp(a,66),1));}
 private static void enhanceCards(Activity a,View root){Button read=findButton(root,"Leer");Button prev=findExact(root,"‹"),next=findExact(root,"›");if(prev!=null){ViewGroup.LayoutParams p=prev.getLayoutParams();p.width=dp(a,78);p.height=dp(a,52);prev.setLayoutParams(p);prev.setTextSize(26);}if(next!=null){ViewGroup.LayoutParams p=next.getLayoutParams();p.width=dp(a,78);p.height=dp(a,52);next.setLayoutParams(p);next.setTextSize(26);}if(read!=null){read.setTag("cards_read_v2");read.setOnClickListener(v->askAndSearch(a));}}
 private static void askAndSearch(Activity a){android.content.SharedPreferences p=a.getSharedPreferences(EmailSyncEngine.PREF,0);EditText x=new EditText(a);x.setInputType(InputType.TYPE_CLASS_NUMBER);x.setText(String.valueOf(p.getInt("card_months_back",1)));x.setSelectAllOnFocus(true);new AlertDialog.Builder(a).setTitle("Buscar estados de Sistarbanc").setMessage("¿Cuántos meses hacia atrás querés buscar?").setView(x).setPositiveButton("Buscar",(d,w)->{int months;try{months=Math.max(1,Math.min(24,Integer.parseInt(x.getText().toString().trim())));}catch(Exception e){months=1;}p.edit().putInt("card_months_back",months).apply();startSearch(a,months,p.getInt("search_timeout_minutes",2));}).setNegativeButton("Cancelar",null).show();}
 private static void startSearch(Activity a,int months,int timeout){EmailSyncEngine.CancelToken token=new EmailSyncEngine.CancelToken();ProgressDialog d=new ProgressDialog(a);d.setTitle("Tarjetas");d.setMessage("Buscando correos con asunto Sistarbanc…");d.setIndeterminate(true);d.setCancelable(false);d.setButton(DialogInterface.BUTTON_NEGATIVE,"Cancelar búsqueda",(q,w)->{token.cancel();d.setMessage("Cancelando búsqueda…");});d.show();new Thread(()->{try{EmailSyncEngine.Result r=EmailSyncEngine.readCards(a,months,timeout,token);a.runOnUiThread(()->{if(d.isShowing())d.dismiss();if(a instanceof CreditCardsActivity)((CreditCardsActivity)a).loadCards();new AlertDialog.Builder(a).setTitle(r.cancelled?"Búsqueda cancelada":r.timedOut?"Tiempo máximo alcanzado":"Lectura terminada").setMessage(r.toString()).setPositiveButton("Aceptar",null).show();});}catch(Exception e){a.runOnUiThread(()->{if(d.isShowing())d.dismiss();new AlertDialog.Builder(a).setTitle("No se pudo leer el correo").setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("Aceptar",null).show();});}}).start();}
 private static Button findButton(View v,String contains){if(v instanceof Button&&((Button)v).getText()!=null&&((Button)v).getText().toString().contains(contains))return(Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findButton(g.getChildAt(i),contains);if(b!=null)return b;}}return null;}
 private static Button findExact(View v,String text){if(v instanceof Button&&text.contentEquals(((Button)v).getText()))return(Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findExact(g.getChildAt(i),text);if(b!=null)return b;}}return null;}
 private static int dp(Context a,int n){return(int)(n*a.getResources().getDisplayMetrics().density+.5f);}
}
