package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;import java.util.regex.*;import javax.mail.*;import javax.mail.search.*;
public class CreditCardsActivity extends Activity{
 LinearLayout list;CreditCardDb db;android.content.SharedPreferences p;int BG,TEXT,CARD,MUTED;
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);db=new CreditCardDb(this);p=getSharedPreferences("card_email",0);boolean l=ThemePrefs.isLight(this);BG=l?0xfff6f8f9:0xff0b1218;TEXT=l?0xff1f262c:0xfff2f5f7;CARD=l?Color.WHITE:0xff162029;MUTED=l?0xff5f6970:0xff9ea9b2;build();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setPadding(18,14,18,14);return v;}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}
 void build(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(20,55,20,20);r.setBackgroundColor(BG);TextView h=t("Tarjetas de crédito",26);r.addView(h);LinearLayout actions=new LinearLayout(this);Button cfg=b("⚙ Correo"),sync=b("↻ Leer estados");actions.addView(cfg,new LinearLayout.LayoutParams(0,-2,1));actions.addView(sync,new LinearLayout.LayoutParams(0,-2,1));r.addView(actions);cfg.setOnClickListener(v->config());sync.setOnClickListener(v->sync());ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);r.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);refresh();}
 void refresh(){list.removeAllViews();Cursor c=db.getReadableDatabase().rawQuery("SELECT c.id,c.name,c.last4,s.id,s.close_date,s.due_date,s.total,s.currency FROM cards c LEFT JOIN statements s ON s.card_id=c.id AND s.id=(SELECT MAX(x.id) FROM statements x WHERE x.card_id=c.id) ORDER BY c.id",null);while(c.moveToNext()){long sid=c.isNull(3)?-1:c.getLong(3);String name=c.getString(1),last=c.getString(2);TextView x=t(name+" •••• "+last+(sid<0?"\nSin estado importado":"\nCierre: "+c.getString(4)+"   Vence: "+c.getString(5)+"\nPago contado: "+c.getString(7)+" "+String.format(Locale.US,"%.2f",c.getDouble(6))),17);x.setBackgroundColor(CARD);x.setOnClickListener(v->{if(sid>0)showStatement(sid,name,last);});list.addView(x,new LinearLayout.LayoutParams(-1,-2));}c.close();if(list.getChildCount()==0)list.addView(t("Todavía no hay tarjetas. Al leer un estado se agregará automáticamente.",15));}
 void showStatement(long sid,String name,String last){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);Cursor c=db.getReadableDatabase().rawQuery("SELECT tx_date,description,installment,amount,currency FROM installments WHERE statement_id=? ORDER BY id",new String[]{""+sid});while(c.moveToNext())f.addView(t(c.getString(0)+"  "+c.getString(1)+(c.getString(2).isEmpty()?"":"  "+c.getString(2))+"\n"+c.getString(4)+" "+String.format(Locale.US,"%.2f",c.getDouble(3)),14));c.close();ScrollView s=new ScrollView(this);s.addView(f);new AlertDialog.Builder(this).setTitle(name+" •••• "+last+" — cuotas y montos").setView(s).setPositiveButton("Cerrar",null).show();}
 EditText e(String hint,String val){EditText x=new EditText(this);x.setHint(hint);x.setText(val);x.setTextColor(TEXT);x.setHintTextColor(MUTED);return x;}
 void config(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText email=e("Correo",p.getString("email","")),pass=e("Contraseña de aplicación",p.getString("pass","")),host=e("Servidor IMAP",p.getString("host","imap.gmail.com"));pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);Switch amount=new Switch(this);amount.setText("Identificar pago por monto coincidente");amount.setChecked(p.getBoolean("pay_amount",true));Switch text=new Switch(this);text.setText("Identificar pago porque dice PAGO TC");text.setChecked(p.getBoolean("pay_text",true));for(View v:new View[]{email,pass,host,amount,text})f.addView(v);new AlertDialog.Builder(this).setTitle("Correo de estados de cuenta").setMessage("Para Gmail usá una contraseña de aplicación, no la contraseña normal. La app buscará únicamente estados enviados por SistarBanc.").setView(f).setPositiveButton("Guardar",(d,w)->{if(!amount.isChecked()&&!text.isChecked()){Toast.makeText(this,"Activá al menos una forma de identificar el pago",Toast.LENGTH_LONG).show();return;}p.edit().putString("email",email.getText().toString().trim()).putString("pass",pass.getText().toString()).putString("host",host.getText().toString().trim()).putBoolean("pay_amount",amount.isChecked()).putBoolean("pay_text",text.isChecked()).apply();}).setNegativeButton("Cancelar",null).show();}
 void sync(){String email=p.getString("email",""),pass=p.getString("pass","");if(email.isEmpty()||pass.isEmpty()){config();return;}Toast.makeText(this,"Buscando estados de cuenta…",Toast.LENGTH_SHORT).show();new Thread(()->{int n=0;try{Properties pr=new Properties();pr.put("mail.store.protocol","imaps");Session se=Session.getInstance(pr);Store st=se.getStore("imaps");st.connect(p.getString("host","imap.gmail.com"),email,pass);Folder in=st.getFolder("INBOX");in.open(Folder.READ_ONLY);Message[] ms=in.search(new AndTerm(new FromStringTerm("sistarbank"),new SubjectTerm("Estado de cuenta")));int start=Math.max(0,ms.length-24);for(int i=start;i<ms.length;i++){String body=body(ms[i]);if(parse(body))n++;}in.close(false);st.close();int done=n;runOnUiThread(()->{refresh();Toast.makeText(this,"Estados leídos: "+done,Toast.LENGTH_LONG).show();});}catch(Exception ex){runOnUiThread(()->new AlertDialog.Builder(this).setTitle("No se pudo leer el correo").setMessage(ex.getMessage()+"\n\nEn Gmail debe estar habilitado IMAP y normalmente se necesita una contraseña de aplicación.").setPositiveButton("Aceptar",null).show());}}).start();}
 String body(Part p)throws Exception{Object o=p.getContent();if(o instanceof String)return(String)o;if(o instanceof Multipart){Multipart m=(Multipart)o;StringBuilder s=new StringBuilder();for(int i=0;i<m.getCount();i++)s.append(body(m.getBodyPart(i))).append('\n');return s.toString();}return"";}
 String clean(String h){return h.replaceAll("(?is)<style.*?</style>"," ").replaceAll("(?is)<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replaceAll("\\s+"," ");}
 boolean parse(String raw){String s=clean(raw);Matcher card=Pattern.compile("(?i)TARJETA\\s*(?:No)?[: ]+\\s*([0-9]{4,6})\\*+([0-9]{4})").matcher(s);if(!card.find())return false;String last=card.group(2);long cid=db.card("BROU MasterCard",last);String close=find(s,"(?i)Fecha de cierre[: ]+([0-9/]+)"),due=find(s,"(?i)Vencimiento actual[: ]+([0-9/]+)");double total=num(find(s,"(?i)SALDO CONTADO\\s+([0-9.,]+)"));long sid=db.statement(cid,close,due,total,"UYU");db.clearItems(sid);Matcher row=Pattern.compile("([0-3]?\\d/[01]?\\d/\\d{2,4})\\s+(.{3,80}?)\\s+([0-9][0-9.,]*)\\s+(?:\\.00|0[.,]00)",Pattern.CASE_INSENSITIVE).matcher(s);while(row.find()){String desc=row.group(2).trim();if(desc.matches("(?i).*(SALDO ANTERIOR|PAGOS|TOTAL TARJETA).*"))continue;String inst=find(desc,"(?i)(CUOTA\\s*\\d{1,2}/\\d{1,2})");db.item(sid,row.group(1),desc,inst,num(row.group(3)),"UYU");}return true;}
 String find(String s,String r){Matcher m=Pattern.compile(r).matcher(s);return m.find()?m.group(1):"";}double num(String x){try{String q=x.replace(".","").replace(',','.');return Double.parseDouble(q);}catch(Exception e){return 0;}}
}