package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;
public class EmailSettingsActivity extends Activity{
 SharedPreferences p;LinearLayout r;EditText email,pass,host,cm,em,tm;Switch cards,expenses;
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);p=getSharedPreferences(EmailSyncEngine.PREF,0);build();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(8,10,8,10);return v;}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}EditText e(String h,String s){EditText x=new EditText(this);x.setHint(h);x.setText(s);return x;}Switch sw(String s,boolean v){Switch x=new Switch(this);x.setText(s);x.setChecked(v);return x;}void add(View v){r.addView(v,new LinearLayout.LayoutParams(-1,-2));}
 void build(){LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(20,20,20,25);sc.addView(r);outer.addView(sc,new LinearLayout.LayoutParams(-1,0,1));add(t("Correo y lecturas",27));add(t("La lectura por correo y la lectura de captura son funciones independientes.",14));add(t("CUENTA DE CORREO",14));email=e("Correo",p.getString("email",""));pass=e("Contraseña de aplicación",SecretStore.get(this));pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);host=e("Servidor IMAP",p.getString("host","imap.gmail.com"));add(email);add(pass);add(host);Button test=b("Probar conexión");add(test);test.setOnClickListener(v->test());add(t("BÚSQUEDA EN CORREO",14));tm=e("Tiempo máximo de búsqueda (minutos)",String.valueOf(p.getInt("search_timeout_minutes",2)));tm.setInputType(InputType.TYPE_CLASS_NUMBER);add(tm);add(t("El tiempo es un límite máximo. Si termina antes, la búsqueda finaliza inmediatamente.",13));add(t("TARJETAS DE CRÉDITO",14));cards=sw("Leer estados de tarjetas desde el correo",p.getBoolean("enable_cards",true));add(cards);cm=e("Meses hacia atrás para estados",String.valueOf(p.getInt("card_months_back",1)));cm.setInputType(InputType.TYPE_CLASS_NUMBER);add(cm);Button wl=b("Administrar lista blanca de tarjetas");add(wl);wl.setOnClickListener(v->white("card_whitelist","Lista blanca · Tarjetas"));Button read=b("Leer estados de tarjeta");add(read);read.setOnClickListener(v->askCards());Button capture=b("Lectura de captura");add(capture);capture.setOnClickListener(v->startActivity(new Intent(this,CaptureStatementActivity.class)));add(t("Elegí una captura del estado de cuenta desde la galería. La app reconoce el texto y permite revisarlo antes de guardarlo.",13));add(t("GASTOS DESDE CORREO",14));expenses=sw("Tomar gastos desde el correo",p.getBoolean("enable_expenses",false));add(expenses);em=e("Meses hacia atrás para gastos",String.valueOf(p.getInt("expense_months_back",1)));em.setInputType(InputType.TYPE_CLASS_NUMBER);add(em);Button wle=b("Administrar lista blanca de gastos");add(wle);wle.setOnClickListener(v->white("expense_whitelist","Lista blanca · Gastos"));Button re=b("Leer gastos del correo");add(re);re.setOnClickListener(v->readExpenses());Button save=b("Guardar configuración");outer.addView(save);save.setOnClickListener(v->{if(save())Toast.makeText(this,"Configuración guardada",Toast.LENGTH_SHORT).show();});outer.setOnApplyWindowInsetsListener((v,i)->{r.setPadding(20,i.getSystemWindowInsetTop()+18,20,25);return i;});setContentView(outer);outer.requestApplyInsets();}
 int n(EditText x){try{return Math.max(1,Math.min(24,Integer.parseInt(x.getText().toString().trim())));}catch(Exception e){return 1;}}int timeout(){try{return Math.max(1,Math.min(30,Integer.parseInt(tm.getText().toString().trim())));}catch(Exception e){return 2;}}
 boolean save(){p.edit().putString("email",email.getText().toString().trim()).putString("host",host.getText().toString().trim()).putInt("card_months_back",n(cm)).putInt("expense_months_back",n(em)).putInt("search_timeout_minutes",timeout()).putBoolean("enable_cards",cards.isChecked()).putBoolean("enable_expenses",expenses.isChecked()).apply();SecretStore.put(this,pass.getText().toString());return true;}
 void white(String k,String title){Intent i=new Intent(this,WhitelistEditorActivity.class);i.putExtra("key",k);i.putExtra("title",title);startActivity(i);}
 void test(){save();ProgressDialog d=ProgressDialog.show(this,"Correo","Probando conexión…",true,false);new Thread(()->{try{EmailSyncEngine.testConnection(this);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle("Conexión correcta").setMessage("ControlGastos pudo conectarse al correo.").setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();err(e);});}}).start();}
 void askCards(){save();final EditText x=e("Meses hacia atrás",String.valueOf(n(cm)));x.setInputType(InputType.TYPE_CLASS_NUMBER);new AlertDialog.Builder(this).setTitle("Buscar estados de Sistarbanc").setMessage("¿Cuántos meses hacia atrás querés buscar?").setView(x).setNegativeButton("Cancelar",null).setPositiveButton("Buscar",(d,w)->{int months;try{months=Math.max(1,Math.min(24,Integer.parseInt(x.getText().toString().trim())));}catch(Exception ex){months=1;}cm.setText(String.valueOf(months));save();readCards(months);}).show();}
 void readCards(int months){EmailSyncEngine.CancelToken token=new EmailSyncEngine.CancelToken();ProgressDialog d=new ProgressDialog(this);d.setTitle("Tarjetas");d.setMessage("Buscando estados de cuenta de Sistarbanc…");d.setIndeterminate(true);d.setCancelable(false);d.setButton(DialogInterface.BUTTON_NEGATIVE,"Cancelar búsqueda",(q,w)->{});d.setOnShowListener(q->d.getButton(DialogInterface.BUTTON_NEGATIVE).setOnClickListener(v->{token.cancel();d.setMessage("Cancelando búsqueda…");d.getButton(DialogInterface.BUTTON_NEGATIVE).setEnabled(false);}));d.show();new Thread(()->{try{EmailSyncEngine.Result x=EmailSyncEngine.readCards(this,months,timeout(),token);runOnUiThread(()->{d.dismiss();String title=x.timedOut?"Tiempo máximo alcanzado":x.cancelled?"Búsqueda cancelada":"Lectura terminada";new AlertDialog.Builder(this).setTitle(title).setMessage(x.toString()).setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();err(e);});}}).start();}
 void readExpenses(){save();ProgressDialog d=ProgressDialog.show(this,"Gastos","Leyendo gastos…",true,false);new Thread(()->{try{EmailSyncEngine.Result x=EmailSyncEngine.readExpenses(this,true);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle("Lectura terminada").setMessage(x.toString()).setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();err(e);});}}).start();}
 void err(Exception e){new AlertDialog.Builder(this).setTitle("No se pudo completar").setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("Aceptar",null).show();}
}
