package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public class EmailSettingsActivity extends Activity{
    SharedPreferences p;int BG,TEXT,CARD,MUTED;
    EditText email,pass,host,months,cardWhite,expenseWhite;
    Switch enableCards,enableExpenses,cardAmount,cardText,cardCurrency,cardDate,cardLast4,expenseDate,expenseAmount,expenseCurrency,expenseExact,expenseSimilar;

    @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);p=getSharedPreferences(EmailSyncEngine.PREF,MODE_PRIVATE);boolean l=ThemePrefs.isLight(this);BG=l?0xfff6f8f9:0xff0b1218;TEXT=l?0xff1f262c:0xfff2f5f7;CARD=l?Color.WHITE:0xff162029;MUTED=l?0xff5f6970:0xff9ea9b2;build();}
    int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}Switch sw(String s,boolean on){Switch x=new Switch(this);x.setText(s);x.setTextColor(TEXT);x.setChecked(on);x.setPadding(dp(8),dp(6),dp(8),dp(6));return x;}EditText ed(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(TEXT);e.setHintTextColor(MUTED);return e;}
    void title(LinearLayout r,String s){TextView t=tv(s,14);t.setTextColor(MUTED);r.addView(t);}void add(LinearLayout r,View v){r.addView(v,new LinearLayout.LayoutParams(-1,-2));}

    void build(){ScrollView sc=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(54),dp(18),dp(30));r.setBackgroundColor(BG);sc.addView(r);TextView h=tv("Correo y lecturas",27);r.addView(h);r.addView(tv("Una sola cuenta de correo para estados de tarjetas y gastos. Cada función tiene su propia lista blanca, criterios de comparación y lectura forzada.",14));

        title(r,"CUENTA DE CORREO");email=ed("Correo",p.getString("email",""));pass=ed("Contraseña de aplicación",SecretStore.get(this));pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);host=ed("Servidor IMAP",p.getString("host","imap.gmail.com"));months=ed("Meses hacia atrás",String.valueOf(p.getInt("months_back",6)));months.setInputType(InputType.TYPE_CLASS_NUMBER);add(r,email);add(r,pass);add(r,host);add(r,months);Button test=btn("Probar conexión");add(r,test);test.setOnClickListener(v->testConnection());

        title(r,"TARJETAS DE CRÉDITO");enableCards=sw("Leer estados de tarjetas desde el correo",p.getBoolean("enable_cards",true));add(r,enableCards);r.addView(tv("Lista blanca. Una regla por línea: remitente|asunto|texto opcional. Ejemplo: sistarbanc|Estado de cuenta",13));cardWhite=ed("Lista blanca de tarjetas",p.getString("card_whitelist","sistarbanc|Estado de cuenta"));cardWhite.setMinLines(3);add(r,cardWhite);r.addView(tv("Comparación para identificar el PAGO TOTAL de la tarjeta. Solo se exigen los criterios activados:",13));cardAmount=sw("Mismo importe total",p.getBoolean("card_cmp_amount",p.getBoolean("pay_amount",true)));cardText=sw("Texto PAGO TC / PAGO DE TARJETA",p.getBoolean("card_cmp_text",p.getBoolean("pay_text",true)));cardCurrency=sw("Misma moneda",p.getBoolean("card_cmp_currency",true));cardDate=sw("Fecha cercana al vencimiento",p.getBoolean("card_cmp_due_date",false));cardLast4=sw("Últimos 4 dígitos presentes",p.getBoolean("card_cmp_last4",false));for(Switch x:new Switch[]{cardAmount,cardText,cardCurrency,cardDate,cardLast4})add(r,x);Button readCards=btn("Leer estados ahora"),forceCards=btn("Forzar lectura de estados");add(r,readCards);add(r,forceCards);readCards.setOnClickListener(v->runCards(false));forceCards.setOnClickListener(v->confirmForce(true));

        title(r,"GASTOS DESDE CORREO");enableExpenses=sw("Tomar gastos desde el correo",p.getBoolean("enable_expenses",false));add(r,enableExpenses);r.addView(tv("Solo se procesan mensajes que coincidan con esta lista blanca. Podés usar remitente, asunto y/o una frase del contenido.",13));expenseWhite=ed("Lista blanca de gastos",p.getString("expense_whitelist",""));expenseWhite.setMinLines(4);add(r,expenseWhite);r.addView(tv("Comparación para no duplicar un gasto que ya llegó por notificación u otra fuente. Todos los criterios activados deben coincidir:",13));expenseDate=sw("Misma fecha",p.getBoolean("expense_cmp_date",true));expenseAmount=sw("Mismo importe",p.getBoolean("expense_cmp_amount",true));expenseCurrency=sw("Misma moneda",p.getBoolean("expense_cmp_currency",true));expenseExact=sw("Mismo nombre exacto",p.getBoolean("expense_cmp_exact_name",false));expenseSimilar=sw("Nombre parecido",p.getBoolean("expense_cmp_similar_name",true));for(Switch x:new Switch[]{expenseDate,expenseAmount,expenseCurrency,expenseExact,expenseSimilar})add(r,x);expenseExact.setOnCheckedChangeListener((x,on)->{if(on)expenseSimilar.setChecked(false);});expenseSimilar.setOnCheckedChangeListener((x,on)->{if(on)expenseExact.setChecked(false);});Button readExpenses=btn("Leer gastos ahora"),forceExpenses=btn("Forzar lectura de gastos");add(r,readExpenses);add(r,forceExpenses);readExpenses.setOnClickListener(v->runExpenses(false));forceExpenses.setOnClickListener(v->confirmForce(false));

        title(r,"AYUDA");Button help=btn("? Cómo funciona el correo");add(r,help);help.setOnClickListener(v->help());Button save=btn("Guardar configuración");add(r,save);save.setOnClickListener(v->{if(save())Toast.makeText(this,"Configuración guardada",Toast.LENGTH_SHORT).show();});setContentView(sc);
    }

    boolean save(){int m;try{m=Integer.parseInt(months.getText().toString().trim());}catch(Exception e){Toast.makeText(this,"Revisá los meses hacia atrás",Toast.LENGTH_LONG).show();return false;}if(m<1||m>24){Toast.makeText(this,"Los meses hacia atrás deben estar entre 1 y 24",Toast.LENGTH_LONG).show();return false;}if(enableCards.isChecked()&&cardWhite.getText().toString().trim().isEmpty()){Toast.makeText(this,"La lista blanca de tarjetas no puede quedar vacía",Toast.LENGTH_LONG).show();return false;}if(enableExpenses.isChecked()&&expenseWhite.getText().toString().trim().isEmpty()){Toast.makeText(this,"La lista blanca de gastos no puede quedar vacía",Toast.LENGTH_LONG).show();return false;}
        p.edit().putString("email",email.getText().toString().trim()).putString("host",host.getText().toString().trim()).putInt("months_back",m).putBoolean("enable_cards",enableCards.isChecked()).putBoolean("enable_expenses",enableExpenses.isChecked()).putString("card_whitelist",cardWhite.getText().toString().trim()).putString("expense_whitelist",expenseWhite.getText().toString().trim()).putBoolean("card_cmp_amount",cardAmount.isChecked()).putBoolean("card_cmp_text",cardText.isChecked()).putBoolean("card_cmp_currency",cardCurrency.isChecked()).putBoolean("card_cmp_due_date",cardDate.isChecked()).putBoolean("card_cmp_last4",cardLast4.isChecked()).putBoolean("pay_amount",cardAmount.isChecked()).putBoolean("pay_text",cardText.isChecked()).putBoolean("expense_cmp_date",expenseDate.isChecked()).putBoolean("expense_cmp_amount",expenseAmount.isChecked()).putBoolean("expense_cmp_currency",expenseCurrency.isChecked()).putBoolean("expense_cmp_exact_name",expenseExact.isChecked()).putBoolean("expense_cmp_similar_name",expenseSimilar.isChecked()).remove("pass").apply();SecretStore.put(this,pass.getText().toString());return true;}

    void testConnection(){if(!save())return;ProgressDialog d=ProgressDialog.show(this,"Correo","Probando conexión IMAP…",true,false);new Thread(()->{try{EmailSyncEngine.testConnection(this);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle("Conexión correcta").setMessage("ControlGastos pudo conectarse al correo configurado.").setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();error(e);});}}).start();}
    void runCards(boolean force){if(!save())return;ProgressDialog d=ProgressDialog.show(this,"Tarjetas",force?"Forzando lectura de estados…":"Leyendo estados nuevos…",true,false);new Thread(()->{try{EmailSyncEngine.Result r=EmailSyncEngine.readCards(this,force);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle(force?"Lectura forzada terminada":"Lectura terminada").setMessage(r.toString()).setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();error(e);});}}).start();}
    void runExpenses(boolean force){if(!save())return;ProgressDialog d=ProgressDialog.show(this,"Gastos por correo",force?"Forzando lectura de gastos…":"Leyendo gastos nuevos…",true,false);new Thread(()->{try{EmailSyncEngine.Result r=EmailSyncEngine.readExpenses(this,force);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle(force?"Lectura forzada terminada":"Lectura terminada").setMessage(r.toString()).setPositiveButton("Aceptar",null).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();error(e);});}}).start();}
    void confirmForce(boolean cards){new AlertDialog.Builder(this).setTitle(cards?"Forzar lectura de estados":"Forzar lectura de gastos").setMessage("Se volverán a revisar todos los correos de la lista blanca dentro de los meses configurados. Los estados se reconstruyen sin duplicarse y los gastos vuelven a pasar por la comparación de duplicados.").setPositiveButton("Forzar",(d,w)->{if(cards)runCards(true);else runExpenses(true);}).setNegativeButton("Cancelar",null).show();}
    void error(Exception e){String m=e.getMessage()==null?e.toString():e.getMessage();new AlertDialog.Builder(this).setTitle("No se pudo leer el correo").setMessage(m+"\n\nEn Gmail normalmente se necesita una contraseña de aplicación y la verificación en dos pasos habilitada.").setPositiveButton("Aceptar",null).show();}
    void help(){String t="CORREO EN CONTROLGASTOS\n\nLa cuenta se configura una sola vez. La contraseña se guarda cifrada con Android Keystore.\n\nPERÍODO\n‘Meses hacia atrás’ limita cuánto historial de correo se revisa.\n\nLISTAS BLANCAS\nTarjetas y gastos tienen listas independientes. Cada línea usa: remitente|asunto|texto opcional. Los campos vacíos no se exigen. Ejemplo: sistarbanc|Estado de cuenta.\n\nTARJETAS\nLos mensajes admitidos se interpretan como estados de cuenta. Se extraen tarjeta, cierre, vencimiento, pago contado, compras y especialmente CUOTA actual/total y monto. Los switches de comparación de tarjeta sirven solo para encontrar el movimiento que representa el PAGO TOTAL de la tarjeta. No afectan la lectura de las compras ni de las cuotas.\n\nGASTOS POR CORREO\nLos mensajes admitidos pueden generar un GASTO. La app intenta obtener importe, moneda, comercio/descripción y fecha. Antes de crear el movimiento compara contra lo ya guardado usando únicamente los criterios activados: fecha, importe, moneda, nombre exacto o nombre parecido.\n\nLECTURA NORMAL Y FORZADA\nLa lectura normal omite mensajes ya procesados. ‘Forzar lectura’ vuelve a analizar todo el período configurado. Los estados se actualizan sin duplicarse y los gastos conservan protección contra duplicados.\n\nPRIVACIDAD\nSolo se intentan procesar mensajes que coinciden con las listas blancas configuradas.";TextView v=tv(t,15);ScrollView s=new ScrollView(this);s.addView(v);new AlertDialog.Builder(this).setTitle("Ayuda · Correo").setView(s).setPositiveButton("Entendido",null).show();}
}
