package com.pablo.controlgastos;
import android.content.*;import android.database.Cursor;import android.database.sqlite.SQLiteDatabase;import java.text.*;import java.util.*;import java.util.regex.*;import javax.mail.*;import javax.mail.search.*;
public final class EmailSyncEngine{
 private EmailSyncEngine(){}public static final String PREF="card_email";private static final String PROCESSED="email_processed";private static final int MAX_MESSAGES=250;
 public static class CancelToken{private volatile boolean cancelled=false;private volatile Store store;public void cancel(){cancelled=true;Store s=store;if(s!=null)try{s.close();}catch(Exception ignored){}}boolean isCancelled(){return cancelled;}void store(Store s){store=s;if(cancelled&&s!=null)try{s.close();}catch(Exception ignored){}}}
 public static class Result{public int scanned,imported,skipped,failed;public boolean cancelled,timedOut;public String detail="";public String toString(){return "Revisados: "+scanned+"\nImportados/actualizados: "+imported+"\nOmitidos: "+skipped+(failed>0?"\nCon error: "+failed:"")+(cancelled?"\nBúsqueda cancelada por el usuario.":"")+(timedOut?"\nSe alcanzó el tiempo máximo de búsqueda.":"");}}
 public static Result readCards(Context c,boolean force)throws Exception{SharedPreferences p=c.getSharedPreferences(PREF,0);return readCards(c,p.getInt("card_months_back",1),p.getInt("search_timeout_minutes",2),new CancelToken());}
 public static Result readCards(Context c,int months,int timeoutMinutes,CancelToken token)throws Exception{SharedPreferences p=c.getSharedPreferences(PREF,0);if(!p.getBoolean("enable_cards",true))throw new Exception("La lectura de estados de tarjeta está desactivada.");return readCardsOnce(c,sinceMonths(months),Math.max(1,timeoutMinutes)*60000L,token==null?new CancelToken():token);}
 public static Result readCardsSince(Context c,Date since)throws Exception{return readCardsOnce(c,since,120000,new CancelToken());}
 public static Result readExpenses(Context c,boolean force)throws Exception{SharedPreferences p=c.getSharedPreferences(PREF,0);if(!p.getBoolean("enable_expenses",false))throw new Exception("La lectura de gastos por correo está desactivada.");return readExpensesOnce(c,sinceMonths(p.getInt("expense_months_back",1)));}
 public static void testConnection(Context c)throws Exception{Store s=openStore(c);try{}finally{try{s.close();}catch(Exception ignored){}}}
 private static Date sinceMonths(int m){m=Math.max(1,Math.min(24,m));Calendar c=Calendar.getInstance();c.add(Calendar.MONTH,-(m-1));c.set(Calendar.DAY_OF_MONTH,1);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTime();}
 private static Result readCardsOnce(Context c,Date since,long limit,CancelToken token)throws Exception{long deadline=System.currentTimeMillis()+limit;Result r=new Result();Store st=null;Folder in=null;try{if(token.isCancelled()){r.cancelled=true;return r;}st=openStore(c);token.store(st);in=st.getFolder("INBOX");in.open(Folder.READ_ONLY);SearchTerm term=new AndTerm(new ReceivedDateTerm(ComparisonTerm.GE,since),new SubjectTerm("Sistarbanc"));Message[] all=in.search(term);int start=Math.max(0,all.length-MAX_MESSAGES);for(int i=all.length-1;i>=start;i--){if(token.isCancelled()){r.cancelled=true;break;}if(System.currentTimeMillis()>=deadline){r.timedOut=true;break;}Message m=all[i];Date d=m.getReceivedDate();if(d==null)d=m.getSentDate();if(d!=null&&d.before(since))break;r.scanned++;try{String text=cleanLines(body(m));if(parseCard(c,text)){r.imported++;if(d!=null){SharedPreferences p=c.getSharedPreferences(PREF,0);long old=p.getLong("last_card_email_date",0);if(d.getTime()>old)p.edit().putLong("last_card_email_date",d.getTime()).apply();}}else r.skipped++;}catch(FolderClosedException e){if(token.isCancelled()){r.cancelled=true;break;}throw e;}catch(Exception e){if(token.isCancelled()){r.cancelled=true;break;}r.failed++;r.detail=e.getMessage()==null?e.toString():e.getMessage();}}return r;}catch(MessagingException e){if(token.isCancelled()){r.cancelled=true;return r;}throw new Exception("No se pudo completar la búsqueda de Sistarbanc en el correo.",e);}finally{if(in!=null&&in.isOpen())try{in.close(false);}catch(Exception ignored){}if(st!=null)try{st.close();}catch(Exception ignored){}token.store(null);}}
 private static Result readExpensesOnce(Context c,Date since)throws Exception{SharedPreferences p=c.getSharedPreferences(PREF,0);String whitelist=p.getString("expense_whitelist","");if(whitelist.trim().isEmpty())throw new Exception("La lista blanca de gastos está vacía.");Store st=openStore(c);Folder in=null;Result r=new Result();try{in=st.getFolder("INBOX");in.open(Folder.READ_ONLY);Message[] all=in.search(new ReceivedDateTerm(ComparisonTerm.GE,since));int start=Math.max(0,all.length-MAX_MESSAGES);for(int i=all.length-1;i>=start;i--){Message m=all[i];String from=addresses(m.getFrom()),subject=safe(m.getSubject()),text=cleanLines(body(m));if(!matchesWhitelist(whitelist,from,subject,text))continue;r.scanned++;try{if(parseExpense(c,m,from,subject,text))r.imported++;else r.skipped++;}catch(Exception e){r.failed++;}}}finally{if(in!=null&&in.isOpen())try{in.close(false);}catch(Exception ignored){}try{st.close();}catch(Exception ignored){}}return r;}
 private static Store openStore(Context c)throws Exception{SharedPreferences p=c.getSharedPreferences(PREF,0);String email=p.getString("email","").trim(),pass=SecretStore.get(c),host=p.getString("host","imap.gmail.com").trim();if(email.isEmpty()||pass.isEmpty())throw new Exception("Primero configurá el correo y la contraseña de aplicación.");Properties q=new Properties();q.put("mail.store.protocol","imaps");q.put("mail.imaps.ssl.enable","true");q.put("mail.imaps.connectiontimeout","15000");q.put("mail.imaps.timeout","30000");q.put("mail.imaps.writetimeout","30000");Session se=Session.getInstance(q);Store st=se.getStore("imaps");st.connect(host,email,pass);return st;}
 private static boolean matchesWhitelist(String rules,String from,String subject,String body){String f=norm(from),s=norm(subject),b=norm(body);for(String line:rules.split("\\r?\\n")){line=line.trim();if(line.isEmpty())continue;String[] x=line.split("\\|",-1);String rf=x.length>0?norm(x[0]):"",rs=x.length>1?norm(x[1]):"",rb=x.length>2?norm(x[2]):"";if((rf.isEmpty()||f.contains(rf))&&(rs.isEmpty()||s.contains(rs))&&(rb.isEmpty()||b.contains(rb)))return true;}return false;}
 private static boolean parseCard(Context c,String lines){String flat=lines.replaceAll("\\s+"," ");Matcher card=Pattern.compile("(?i)TARJETA\\s*(?:No)?[: ]+\\s*([0-9]{4,6})\\*+([0-9]{4})").matcher(flat);if(!card.find())return false;CreditCardDb db=new CreditCardDb(c);long cid=db.card("BROU MasterCard",card.group(2));String close=find(flat,"(?i)Fecha de cierre[: ]+([0-9/]+)"),due=find(flat,"(?i)Vencimiento actual[: ]+([0-9/]+)");double total=num(find(flat,"(?i)SALDO CONTADO\\s+(?:UYU\\s*)?([0-9.,]+)"));long sid=db.statement(cid,close,due,total,"UYU");db.clearItems(sid);Matcher row=Pattern.compile("([0-3]?\\d/[01]?\\d/\\d{2,4})\\s+(.{3,100}?)\\s+([0-9][0-9.,]*)\\s+(?:\\.00|0[.,]00)",2).matcher(flat);int count=0;while(row.find()){String desc=row.group(2).trim();if(desc.matches("(?i).*(SALDO ANTERIOR|PAGOS|TOTAL TARJETA).*"))continue;db.item(sid,row.group(1),desc,find(desc,"(?i)(CUOTA\\s*0*\\d{1,2}/0*\\d{1,2})"),num(row.group(3)),"UYU");count++;}db.close();return count>0||total>0;}
 private static boolean parseExpense(Context c,Message m,String from,String subject,String lines)throws Exception{Matcher a=Pattern.compile("(?im)(?:importe|monto|total|valor)\\s*[:=-]?\\s*(UYU|USD|U\\$S|\\$)?\\s*([0-9][0-9.,]*)").matcher(lines);if(!a.find())return false;double amount=num(a.group(2));if(amount<=0)return false;ExpenseDb db=new ExpenseDb(c);try{ContentValues v=new ContentValues();v.put("type","GASTO");v.put("amount",amount);v.put("currency","UYU");v.put("category",DetectionRules.categoryFor(c,subject+"\n"+lines,"Otros"));v.put("description",subject);v.put("original_text",lines);v.put("ts",dateOf(m));v.put("original_ts",dateOf(m));v.put("source","correo");v.put("fingerprint","EMAIL:"+Integer.toHexString((from+subject+dateOf(m)+amount).hashCode()));return db.getWritableDatabase().insertWithOnConflict("tx",null,v,SQLiteDatabase.CONFLICT_IGNORE)!=-1;}finally{db.close();}}
 private static long dateOf(Message m){try{Date d=m.getSentDate();if(d==null)d=m.getReceivedDate();return d==null?System.currentTimeMillis():d.getTime();}catch(Exception e){return System.currentTimeMillis();}}
 private static String addresses(Address[] a){if(a==null)return"";StringBuilder s=new StringBuilder();for(Address x:a)s.append(x).append(' ');return s.toString();}private static String body(Part p)throws Exception{Object o=p.getContent();if(o instanceof String)return(String)o;if(o instanceof Multipart){StringBuilder s=new StringBuilder();Multipart m=(Multipart)o;for(int i=0;i<m.getCount();i++)s.append(body(m.getBodyPart(i))).append('\n');return s.toString();}return"";}private static String cleanLines(String h){return safe(h).replaceAll("(?is)<style.*?</style>"," ").replaceAll("(?i)<br\\s*/?>","\n").replaceAll("(?i)</(?:p|div|tr|li|h[1-6])>","\n").replaceAll("(?is)<[^>]+>"," ").replace("&nbsp;"," ").replace("&amp;","&").replaceAll("[ \\t]+"," ").trim();}private static String find(String s,String re){Matcher m=Pattern.compile(re).matcher(s);return m.find()?m.group(1):"";}private static double num(String x){try{String q=safe(x).trim();int c=q.lastIndexOf(','),d=q.lastIndexOf('.');if(c>=0&&d>=0)q=d>c?q.replace(",",""):q.replace(".","").replace(',','.');else if(c>=0)q=(q.length()-c-1==2)?q.replace(',','.'):q.replace(",","");return Double.parseDouble(q);}catch(Exception e){return 0;}}private static String norm(String s){return java.text.Normalizer.normalize(safe(s),java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("\\s+"," ").trim();}private static String safe(String s){return s==null?"":s;}
}
