package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 private ExpenseDb db;private int BG,CARD,TEXT,MUTED;private final DecimalFormat money=new DecimalFormat("#,##0.00");private static final int REQ_EXPORT=44,REQ_IMPORT=45;private Uri lastIncomingUri;
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);initPalette();db=new ExpenseDb(this);build();handleIncomingExcel(getIntent());}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleIncomingExcel(i);}
 private void handleIncomingExcel(Intent i){if(i==null)return;Uri u=null;if(Intent.ACTION_VIEW.equals(i.getAction()))u=i.getData();else if(Intent.ACTION_SEND.equals(i.getAction())){try{u=i.getParcelableExtra(Intent.EXTRA_STREAM);}catch(Exception ignored){}if(u==null&&i.getClipData()!=null&&i.getClipData().getItemCount()>0)u=i.getClipData().getItemAt(0).getUri();}if(u==null||u.equals(lastIncomingUri))return;lastIncomingUri=u;final Uri x=u;getWindow().getDecorView().postDelayed(()->previewImport(x),180);}
 private void initPalette(){boolean l=ThemePrefs.isLight(this);BG=l?Color.rgb(246,248,249):Color.rgb(11,18,24);CARD=l?Color.WHITE:Color.rgb(22,32,41);TEXT=l?Color.rgb(31,38,44):Color.rgb(242,245,247);MUTED=l?Color.rgb(95,105,112):Color.rgb(158,169,178);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(10),dp(8),dp(10),dp(8));return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(TEXT);b.setBackground(bg(CARD,14));return b;}
 private void build(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(BG);sc.addView(root);TextView t=tv("Herramientas",28,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(t);root.addView(tv("Importación, reglas, exportación y movimientos recurrentes",14,MUTED));Button imp=btn("⬆ Importar banco (.xls)"),rules=btn("🔎 Palabras y categorías (hasta 50)"),exp=btn("⬇ Exportar CSV"),rec=btn("↻ Movimientos recurrentes"),add=btn("＋ Agregar movimiento manual"),notif=btn(notificationEnabled()?"🟢 Lectura de notificaciones: activa":"🔴 Activar lectura de notificaciones");for(Button b:new Button[]{imp,rules,exp,rec,add,notif}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(7),0,dp(7));root.addView(b,p);}root.addView(tv("Las reglas se aplican a notificaciones y al Excel. El Excel siempre importa todos los movimientos válidos; las reglas solo ayudan a categorizarlos.",13,MUTED));setContentView(sc);imp.setOnClickListener(v->pickBankFile());rules.setOnClickListener(v->startActivity(new Intent(this,RulesActivity.class)));exp.setOnClickListener(v->exportCsv());rec.setOnClickListener(v->showRecurring());add.setOnClickListener(v->showAdd(false));notif.setOnClickListener(v->openNotificationSettings());}
 private LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(24),0,dp(24),0);return f;}private Spinner spinner(String[]v){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,v));return s;}
 private void showAdd(boolean recurring){LinearLayout f=form();Spinner type=spinner(new String[]{"GASTO","INGRESO"});EditText amount=new EditText(this);amount.setHint("Monto");amount.setInputType(2|8192);Spinner cur=spinner(new String[]{"UYU","USD"});EditText desc=new EditText(this);desc.setHint("Descripción");EditText cat=new EditText(this);cat.setHint("Categoría");f.addView(type);f.addView(amount);f.addView(cur);f.addView(desc);f.addView(cat);final Calendar chosen=Calendar.getInstance();Button date=btn("Fecha: "+new SimpleDateFormat("dd/MM/yyyy",Locale.US).format(chosen.getTime()));EditText day=null;if(recurring){day=new EditText(this);day.setHint("Día del mes (1-31)");day.setInputType(2);f.addView(day);}else{f.addView(date);date.setOnClickListener(v->new DatePickerDialog(this,(view,y,m,d)->{chosen.set(y,m,d);date.setText("Fecha: "+new SimpleDateFormat("dd/MM/yyyy",Locale.US).format(chosen.getTime()));},chosen.get(Calendar.YEAR),chosen.get(Calendar.MONTH),chosen.get(Calendar.DAY_OF_MONTH)).show());}final EditText dayF=day;new AlertDialog.Builder(this).setTitle(recurring?"Nuevo recurrente":"Nuevo movimiento").setView(f).setPositiveButton("Guardar",(d,w)->{try{double a=Double.parseDouble(amount.getText().toString().trim().replace(',','.'));if(a<=0)throw new Exception();String de=desc.getText().toString().trim();if(de.isEmpty())de="Sin descripción";String ca=cat.getText().toString().trim();if(ca.isEmpty())ca="Sin categoría";if(recurring)db.addRecurring(type.getSelectedItem().toString(),a,cur.getSelectedItem().toString(),ca,de,Integer.parseInt(dayF.getText().toString()));else db.addTx(type.getSelectedItem().toString(),a,cur.getSelectedItem().toString(),ca,de,"",chosen.getTimeInMillis(),"manual");Toast.makeText(this,"Guardado",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Revisá los datos",Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancelar",null).show();}
 private void showRecurring(){LinearLayout box=form();Cursor c=db.allRecurring();boolean any=false;while(c.moveToNext()){any=true;long id=c.getLong(0);String line=c.getString(1)+" · "+c.getString(3)+" "+money.format(c.getDouble(2))+" · día "+c.getInt(6)+" · "+c.getString(5);TextView v=tv(line,15,TEXT);box.addView(v);v.setOnLongClickListener(z->{new AlertDialog.Builder(this).setTitle("Eliminar recurrente").setMessage(line).setPositiveButton("Eliminar",(a,b)->db.deleteRecurring(id)).setNegativeButton("Cancelar",null).show();return true;});}c.close();if(!any)box.addView(tv("No hay movimientos recurrentes.",15,MUTED));Button add=btn("+ Agregar recurrente");box.addView(add);AlertDialog d=new AlertDialog.Builder(this).setTitle("Movimientos recurrentes").setView(box).setNegativeButton("Cerrar",null).create();add.setOnClickListener(v->{d.dismiss();showAdd(true);});d.show();}
 private void pickBankFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/vnd.ms-excel");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/vnd.ms-excel","application/octet-stream","*/*"});startActivityForResult(i,REQ_IMPORT);}private void exportCsv(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"gastos_"+new SimpleDateFormat("yyyy_MM",Locale.US).format(new Date())+".csv");startActivityForResult(i,REQ_EXPORT);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(c!=RESULT_OK||data==null)return;if(r==REQ_EXPORT)writeCsv(data.getData());else if(r==REQ_IMPORT)previewImport(data.getData());}
 private void previewImport(Uri uri){final ProgressDialog p=ProgressDialog.show(this,"Leyendo Excel","Analizando movimientos…",true,false);new Thread(()->{try{BankXlsImporter.Result result=BankXlsImporter.parse(this,uri);int dup=0;for(BankXlsImporter.Tx tx:result.rows)if(db.hasFingerprint(tx.fingerprint))dup++;int dups=dup;runOnUiThread(()->{p.dismiss();new AlertDialog.Builder(this).setTitle("Vista previa").setMessage("Movimientos detectados: "+result.rows.size()+"\nYa existentes: "+dups+"\nNuevos: "+(result.rows.size()-dups)).setPositiveButton("Importar nuevos",(d,w)->commitImport(result)).setNegativeButton("Cancelar",null).show();});}catch(Exception e){runOnUiThread(()->{p.dismiss();new AlertDialog.Builder(this).setTitle("No pude leer el Excel").setMessage(e.getMessage()).setPositiveButton("Aceptar",null).show();});}}).start();}
 private void commitImport(BankXlsImporter.Result r){int a=0,d=0;for(BankXlsImporter.Tx tx:r.rows){if(db.addImportedTx(tx.type,tx.amount,tx.currency,tx.category,tx.description,tx.original,tx.ts,"banco-xls",tx.fingerprint))a++;else d++;}Toast.makeText(this,"Importados "+a+" · "+d+" duplicados omitidos",Toast.LENGTH_LONG).show();}
 private void writeCsv(Uri u){try(OutputStream os=getContentResolver().openOutputStream(u);OutputStreamWriter w=new OutputStreamWriter(os)){w.write("fecha,tipo,moneda,monto,categoria,descripcion,origen,texto_original\n");Cursor c=db.monthTx();SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US);while(c.moveToNext())w.write(csv(df.format(new Date(c.getLong(7))))+","+csv(c.getString(1))+","+csv(c.getString(3))+","+c.getDouble(2)+","+csv(c.getString(4))+","+csv(c.getString(5))+","+csv(c.getString(8))+","+csv(c.getString(6))+"\n");c.close();Toast.makeText(this,"CSV exportado",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo exportar",Toast.LENGTH_LONG).show();}}private String csv(String s){if(s==null)s="";return"\""+s.replace("\"","\"\"")+"\"";}private boolean notificationEnabled(){String e=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");return e!=null&&e.contains(getPackageName());}private void openNotificationSettings(){try{startActivity(new Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"));}catch(Exception ignored){}}
}
