package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.graphics.drawable.Drawable;import android.view.*;import android.widget.*;
public final class NormalDuplicatePrefs{
 private static final String PREF="normal_duplicate_detection";private NormalDuplicatePrefs(){}
 public static boolean sameDate(Context c){return p(c).getBoolean("same_date",true);}public static boolean sameAmount(Context c){return p(c).getBoolean("same_amount",true);}public static boolean sameCurrency(Context c){return p(c).getBoolean("same_currency",true);}public static boolean exactName(Context c){return p(c).getBoolean("exact_name",false);}public static boolean similarName(Context c){return p(c).getBoolean("similar_name",true);}private static android.content.SharedPreferences p(Context c){return c.getSharedPreferences(PREF,Context.MODE_PRIVATE);}
 public static void install(Activity a){if(!(a instanceof MainActivity))return;View root=a.findViewById(android.R.id.content);if(root==null)return;root.postDelayed(()->inject(a,root),300);}
 private static void inject(Activity a,View root){if(root.findViewWithTag("normal_duplicate_settings")!=null)return;Button anchor=findButton(root,"Importar archivo eBROU");LinearLayout host=anchor!=null&&anchor.getParent() instanceof LinearLayout?(LinearLayout)anchor.getParent():findVertical(root);if(host==null)return;Button b=new Button(a);b.setTag("normal_duplicate_settings");b.setText("🔁 Detección de movimientos repetidos");b.setAllCaps(false);if(anchor!=null){b.setTextColor(anchor.getTextColors());Drawable d=anchor.getBackground();if(d!=null&&d.getConstantState()!=null)b.setBackground(d.getConstantState().newDrawable().mutate());}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(a,58));lp.setMargins(0,dp(a,7),0,dp(a,7));host.addView(b,lp);b.setOnClickListener(v->show(a));}
 private static Button findButton(View v,String text){if(v instanceof Button&&((Button)v).getText()!=null&&((Button)v).getText().toString().contains(text))return(Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findButton(g.getChildAt(i),text);if(b!=null)return b;}}return null;}
 private static LinearLayout findVertical(View v){if(v instanceof LinearLayout&&((LinearLayout)v).getOrientation()==LinearLayout.VERTICAL)return(LinearLayout)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){LinearLayout x=findVertical(g.getChildAt(i));if(x!=null)return x;}}return null;}
 private static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}private static Switch sw(Context c,String text,boolean checked){Switch s=new Switch(c);s.setText(text);s.setChecked(checked);s.setPadding(dp(c,8),dp(c,8),dp(c,8),dp(c,8));return s;}
 private static void show(Activity a){LinearLayout f=new LinearLayout(a);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(a,24),0,dp(a,24),0);TextView info=new TextView(a);info.setText("Estos criterios se usan automáticamente cuando llega una notificación o se importa un movimiento. No modifican la herramienta manual ‘Unificar movimientos repetidos’.\n\nSolo se comparan los criterios que estén activados.");info.setPadding(0,0,0,dp(a,10));f.addView(info);Switch date=sw(a,"Misma fecha",sameDate(a)),amount=sw(a,"Mismo importe",sameAmount(a)),currency=sw(a,"Misma moneda",sameCurrency(a)),exact=sw(a,"Mismo nombre exacto",exactName(a)),similar=sw(a,"Nombre parecido",similarName(a));f.addView(date);f.addView(amount);f.addView(currency);f.addView(exact);f.addView(similar);exact.setOnCheckedChangeListener((x,on)->{if(on)similar.setChecked(false);});similar.setOnCheckedChangeListener((x,on)->{if(on)exact.setChecked(false);});new AlertDialog.Builder(a).setTitle("Detección de movimientos repetidos").setView(f).setPositiveButton("Guardar",(d,w)->{if(!date.isChecked()&&!amount.isChecked()&&!currency.isChecked()&&!exact.isChecked()&&!similar.isChecked()){Toast.makeText(a,"Activá al menos un criterio",Toast.LENGTH_LONG).show();return;}p(a).edit().putBoolean("same_date",date.isChecked()).putBoolean("same_amount",amount.isChecked()).putBoolean("same_currency",currency.isChecked()).putBoolean("exact_name",exact.isChecked()).putBoolean("similar_name",similar.isChecked()).apply();Toast.makeText(a,"Criterios guardados",Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancelar",null).show();}
}
