package com.pablo.controlgastos;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.lang.reflect.Method;
import java.text.DecimalFormat;
import java.util.*;

public final class ReconciliationOverlay {
    private static final WeakHashMap<Activity,Boolean> installed=new WeakHashMap<>();
    private static final DecimalFormat MONEY=new DecimalFormat("#,##0.00");
    private ReconciliationOverlay(){}
    public static void install(Activity a){synchronized(installed){if(installed.containsKey(a))return;installed.put(a,true);}a.getWindow().getDecorView().postDelayed(()->{if(a.isFinishing())return;if(a instanceof MainActivity)attachSettings(a);else if(a instanceof HomeActivity)attachHelp(a);},420);}
    private static void attachSettings(Activity a){Button anchor=findButton(a.getWindow().getDecorView(),"Importar archivo eBROU");if(anchor==null||!(anchor.getParent() instanceof LinearLayout))return;LinearLayout parent=(LinearLayout)anchor.getParent();for(int i=0;i<parent.getChildCount();i++)if(parent.getChildAt(i) instanceof Button&&((Button)parent.getChildAt(i)).getText().toString().contains("Unificar movimientos repetidos"))return;Button b=new Button(a);b.setText("🔎 Unificar movimientos repetidos");b.setAllCaps(false);b.setTextColor(ThemePrefs.isLight(a)?Color.rgb(31,38,44):Color.rgb(242,245,247));GradientDrawable bg=new GradientDrawable();bg.setColor(ThemePrefs.isLight(a)?Color.WHITE:Color.rgb(22,32,41));bg.setCornerRadius(dp(a,14));b.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(a,58));p.setMargins(0,dp(a,7),0,dp(a,7));int index=parent.indexOfChild(anchor);parent.addView(b,index+1,p);b.setOnClickListener(v->scan(a));}
    private static void attachHelp(Activity a){Button help=findButton(a.getWindow().getDecorView(),"Ayuda");if(help==null)return;help.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Ayuda · ControlGastos").setItems(new String[]{"Guía completa y novedades","Ayuda general","Correo y lecturas","Importación inteligente","Análisis automático del mes","Vista anual por categoría","Unificación de movimientos repetidos","Seguridad y respaldo"},(d,w)->{if(w==0)showCurrentHelp(a);else if(w==1)invokeGeneralHelp(a);else if(w==2)showEmailHelp(a);else if(w==3)showSmartImportHelp(a);else if(w==4)showAnalysisHelp(a);else if(w==5)showAnnualHelp(a);else if(w==6)showReconciliationHelp(a);else showSecurityBackupHelp(a);}).setNegativeButton("Cerrar",null).show());}
    private static void invokeGeneralHelp(Activity a){try{Method m=a.getClass().getDeclaredMethod("showHelp");m.setAccessible(true);m.invoke(a);}catch(Exception e){Toast.makeText(a,"No se pudo abrir la ayuda general",Toast.LENGTH_LONG).show();}}
    private static void showEmailHelp(Activity a){String t="CORREO Y LECTURAS\n\nCONFIGURAR GMAIL\nControlGastos no usa tu contraseña normal de Google. Para usar Gmail primero tenés que activar la Verificación en dos pasos en tu Cuenta de Google → Seguridad. Después entrá en Contraseñas de aplicaciones, escribí ‘ControlGastos’, generá la contraseña de 16 caracteres y pegala en Ajustes → Correo y lecturas → Contraseña de aplicación. Si ‘Contraseñas de aplicaciones’ no aparece, comprobá que la verificación en dos pasos esté activa.\n\nCUENTA Y PERÍODO\n‘Meses hacia atrás’ limita cuánto historial de correo se revisa. ‘Probar conexión’ comprueba la cuenta y la contraseña configuradas.\n\nLISTAS BLANCAS\nTarjetas y gastos tienen listas independientes. Entrá en ‘Administrar lista blanca’ y agregá las filas que necesites. Cada fila puede filtrar por remitente, asunto y/o una frase del contenido.\n\nESTADOS DE TARJETA\nLa lectura busca correos admitidos por la lista blanca y extrae cierre, vencimiento, pago contado, compras y cuotas cuando el formato es reconocido. Los criterios de comparación sirven para identificar el pago total sin confundirlo con otro movimiento.\n\nGASTOS DESDE CORREO\nEsta función es independiente de Tarjetas. Antes de crear un gasto aplica los criterios activados para evitar duplicar un movimiento que ya haya llegado por notificación u otra fuente.\n\nLECTURA NORMAL Y FORZADA\nLa lectura normal evita reprocesar mensajes ya tratados. La lectura forzada vuelve a revisar los correos admitidos dentro del período configurado; las reglas de duplicados siguen protegiendo los movimientos.\n\nPRIVACIDAD\nLa contraseña de aplicación se guarda cifrada mediante Android Keystore. Podés revocarla desde tu Cuenta de Google sin cambiar tu contraseña principal.";showHelpText(a,"Correo y lecturas",t);}
    private static void showCurrentHelp(Activity a){String t="GUÍA COMPLETA Y NOVEDADES\n\nINICIO\nPodés cambiar mes, filtrar movimientos por monto y moneda, editar un movimiento tocándolo o cambiar solo su categoría tocando la línea Categoría.\n\nNOTIFICACIONES\nControlGastos puede registrar compras, pagos, transferencias e ingresos desde notificaciones compatibles. En instalaciones fuera de Play Store Android puede exigir habilitar ‘Permitir configuraciones restringidas’.\n\nCORREO Y TARJETAS\nAjustes → Correo y lecturas permite leer estados de tarjeta y gastos admitidos por listas blancas independientes. La explicación completa, incluida la contraseña de aplicación de Gmail y la verificación en dos pasos, está en Ayuda → Correo y lecturas.\n\nEXCEL Y RESPALDO\nLa app importa el .xls original de eBROU. El Excel exportado por ControlGastos funciona además como respaldo completo de movimientos y configuración compatible.\n\nGRÁFICOS Y ANÁLISIS\nIncluye vistas por categorías, comercios, evolución, análisis automático y vista anual.\n\nPRESUPUESTO Y RECURRENTES\nPodés definir presupuesto por categoría y movimientos recurrentes.\n\nPAPELERA\nLos movimientos eliminados pasan a Papelera y varias acciones admiten deshacer.\n\nSEGURIDAD\nModo claro, bloqueo de capturas y bloqueo biométrico están en Ajustes.\n\nPRIVACIDAD\nLos movimientos, reglas, presupuestos y análisis se procesan localmente.";showHelpText(a,"Guía completa y novedades",t);}
    private static void showSmartImportHelp(Activity a){String t="IMPORTACIÓN INTELIGENTE\n\nEsta opción está pensada para archivos .xls de bancos que no tienen el formato eBROU. No reemplaza al importador específico de eBROU ni al restaurador de respaldos.\n\nControlGastos delimita el rango útil e intenta identificar fecha, descripción/comercio, débito, crédito, importe, moneda y tipo. Antes de importar muestra una vista previa con las columnas detectadas, el rango y una estimación de confianza.\n\nSi el formato es desconocido conviene revisar la vista previa antes de guardar.";showHelpText(a,"Importación inteligente",t);}
    private static void showAnalysisHelp(Activity a){String t="ANÁLISIS AUTOMÁTICO DEL MES\n\nEn Gráficos → Análisis, ControlGastos evalúa el período seleccionado usando solamente los movimientos guardados en el teléfono.\n\nPuede mostrar ahorro o déficit, tasa de ahorro, comparación con meses anteriores, categorías o gastos fuera de lo común, acumulación de gastos pequeños y tendencias. El análisis es orientativo y se calcula localmente.";showHelpText(a,"Análisis automático",t);}
    private static void showAnnualHelp(Activity a){String t="VISTA ANUAL POR CATEGORÍA\n\nEn Gráficos → Vista anual podés elegir una categoría y ver su evolución durante los últimos 12 meses hasta el período seleccionado. Tocá una barra para ver el importe exacto.\n\nDebajo se muestran promedio mensual, máximo, mínimo, meses con gasto y variación.";showHelpText(a,"Vista anual",t);}
    private static void showReconciliationHelp(Activity a){String t="UNIFICACIÓN DE MOVIMIENTOS REPETIDOS\n\nControlGastos usa la misma regla tanto al importar eBROU como en Ajustes → Unificar movimientos repetidos.\n\nLos criterios configurados determinan cuándo dos registros pueden corresponder al mismo movimiento. La revisión manual nunca unifica sin tu confirmación y la copia eliminada queda en la Papelera.";showHelpText(a,"Unificar movimientos repetidos",t);}
    private static void showSecurityBackupHelp(Activity a){String t="SEGURIDAD Y RESPALDO\n\nEl bloqueo biométrico viene desactivado por defecto y puede activarse en Ajustes → Apariencia y seguridad. El bloqueo de capturas es independiente.\n\nEl Excel exportado funciona como respaldo completo de movimientos y configuración compatible. Al restaurarlo se muestra una advertencia antes de reemplazar la configuración actual.";showHelpText(a,"Seguridad y respaldo",t);}
    private static void showHelpText(Activity a,String title,String text){TextView tv=new TextView(a);tv.setText(text);tv.setTextSize(15);tv.setPadding(dp(a,24),dp(a,16),dp(a,24),dp(a,16));ScrollView sc=new ScrollView(a);sc.addView(tv);new AlertDialog.Builder(a).setTitle(title).setView(sc).setPositiveButton("Entendido",null).show();}
    private static void scan(Activity a){ProgressDialog p=ProgressDialog.show(a,"Buscando repetidos","Buscando posibles duplicados…",true,false);new Thread(()->{ExpenseDb db=new ExpenseDb(a);ArrayList<MovementReconciler.Candidate> items=MovementReconciler.findCandidates(db);a.runOnUiThread(()->{p.dismiss();if(items.isEmpty()){new AlertDialog.Builder(a).setTitle("Unificar movimientos repetidos").setMessage("No encontré posibles duplicados con la regla actual.").setPositiveButton("Cerrar",null).show();return;}new AlertDialog.Builder(a).setTitle("Unificar movimientos repetidos").setMessage("Encontré "+items.size()+" posible"+(items.size()==1?" duplicado":"s duplicados")+". Nada se unifica sin que lo confirmes.").setPositiveButton("Revisar",(d,w)->review(a,db,items,0,0)).setNegativeButton("Cancelar",null).show();});}).start();}
    private static void review(Activity a,ExpenseDb db,ArrayList<MovementReconciler.Candidate> items,int index,int merged){if(index>=items.size()){new AlertDialog.Builder(a).setTitle("Unificación terminada").setMessage("Movimientos unificados: "+merged+".\n\nLas copias eliminadas quedan en la Papelera.").setPositiveButton("Cerrar",null).show();return;}MovementReconciler.Candidate c=items.get(index);String sign="GASTO".equals(c.type)?"-":"+";String amount=("USD".equals(c.currency)?"USD ":"$ ")+MONEY.format(c.amount);String msg="Fecha: "+c.dateLabel+"\nImporte: "+sign+amount+"\n\n1) "+safe(c.descriptionA)+"\nCategoría: "+safeCat(c.categoryA)+"\nOrigen: "+safe(c.sourceA)+"\n\n2) "+safe(c.descriptionB)+"\nCategoría: "+safeCat(c.categoryB)+"\nOrigen: "+safe(c.sourceB)+"\n\n¿Son el mismo movimiento?";new AlertDialog.Builder(a).setTitle((index+1)+" de "+items.size()+" · Posible duplicado").setMessage(msg).setPositiveButton("Unificar",(d,w)->{boolean ok=MovementReconciler.merge(db,c);Toast.makeText(a,ok?"Movimientos unificados":"No se pudo unificar",Toast.LENGTH_SHORT).show();review(a,db,items,index+1,merged+(ok?1:0));}).setNeutralButton("Omitir",(d,w)->review(a,db,items,index+1,merged)).setNegativeButton("Cerrar",null).show();}
    private static Button findButton(View v,String contains){if(v instanceof Button&&((Button)v).getText()!=null&&((Button)v).getText().toString().contains(contains))return(Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findButton(g.getChildAt(i),contains);if(b!=null)return b;}}return null;}
    private static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}
    private static String safe(String s){return s==null||s.trim().isEmpty()?"Sin descripción":s;}
    private static String safeCat(String s){return s==null||s.trim().isEmpty()?"Sin categoría":s;}
}
