package com.pablo.controlgastos;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class WhitelistEditorActivity extends Activity{
 SharedPreferences p;LinearLayout rows;String key,title;int BG,TEXT,MUTED,CARD;
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 @Override public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);p=getSharedPreferences(EmailSyncEngine.PREF,0);key=getIntent().getStringExtra("key");title=getIntent().getStringExtra("title");if(key==null)key="card_whitelist";if(title==null)title="Lista blanca";boolean l=ThemePrefs.isLight(this);BG=l?0xfff6f8f9:0xff0b1218;TEXT=l?0xff1f262c:0xfff2f5f7;MUTED=l?0xff5f6970:0xff9ea9b2;CARD=l?Color.WHITE:0xff162029;build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(18),dp(48),dp(18),dp(12));root.addView(tv(title,26));TextView info=tv("Cada fila es una regla. Completá remitente, asunto y/o texto del mensaje. Solo se exigen los campos que completes.",14);info.setTextColor(MUTED);root.addView(info);ScrollView sc=new ScrollView(this);rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);sc.addView(rows);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=new LinearLayout(this);Button add=btn("+ Agregar fila"),save=btn("Guardar lista");actions.addView(add,new LinearLayout.LayoutParams(0,-2,1));actions.addView(save,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);setContentView(root);String raw=p.getString(key,key.equals("card_whitelist")?"sistarbanc|Estado de cuenta":"");if(!raw.trim().isEmpty())for(String line:raw.split("\\r?\\n")){String[] a=line.split("\\|",-1);addRow(a.length>0?a[0]:"",a.length>1?a[1]:"",a.length>2?a[2]:"");}if(rows.getChildCount()==0)addRow("","","");add.setOnClickListener(v->addRow("","",""));save.setOnClickListener(v->save());}
 EditText field(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(true);return e;}
 void addRow(String from,String subject,String text){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(10),dp(8),dp(10),dp(8));card.setBackgroundColor(CARD);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(6),0,dp(6));EditText f=field("Remitente",from),s=field("Asunto",subject),t=field("Texto opcional",text);card.addView(f);card.addView(s);card.addView(t);Button del=btn("Eliminar fila");card.addView(del);rows.addView(card,cp);del.setOnClickListener(v->{rows.removeView(card);if(rows.getChildCount()==0)addRow("","","");});}
 void save(){ArrayList<String> out=new ArrayList<>();for(int i=0;i<rows.getChildCount();i++){LinearLayout c=(LinearLayout)rows.getChildAt(i);String f=((EditText)c.getChildAt(0)).getText().toString().trim(),s=((EditText)c.getChildAt(1)).getText().toString().trim(),t=((EditText)c.getChildAt(2)).getText().toString().trim();if(!f.isEmpty()||!s.isEmpty()||!t.isEmpty())out.add(f+"|"+s+"|"+t);}p.edit().putString(key,android.text.TextUtils.join("\n",out)).apply();Toast.makeText(this,"Lista guardada",Toast.LENGTH_SHORT).show();finish();}
}
