package com.pablo.controlgastos;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;
public class WhitelistActivity extends Activity{
 LinearLayout rows;SharedPreferences p;String key,title;int BG,TEXT,CARD,MUTED;
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(TEXT);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void onCreate(Bundle b){ThemePrefs.applyBaseTheme(this);super.onCreate(b);p=getSharedPreferences(EmailSyncEngine.PREF,0);key=getIntent().getStringExtra("key");title=getIntent().getStringExtra("title");if(key==null)key="card_whitelist";if(title==null)title="Lista blanca";boolean l=ThemePrefs.isLight(this);BG=l?0xfff6f8f9:0xff0b1218;TEXT=l?0xff1f262c:0xfff2f5f7;CARD=l?Color.WHITE:0xff162029;MUTED=l?0xff5f6970:0xff9ea9b2;build();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(54),dp(18),dp(18));root.setBackgroundColor(BG);root.addView(tv(title,26));TextView h=tv("Cada fila es una regla. Completá remitente, asunto y/o texto del mensaje. Los campos vacíos no se exigen.",13);h.setTextColor(MUTED);root.addView(h);ScrollView sc=new ScrollView(this);rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);sc.addView(rows);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);Button add=btn("＋ Agregar fila"),save=btn("Guardar");bar.addView(add,new LinearLayout.LayoutParams(0,-2,1));bar.addView(save,new LinearLayout.LayoutParams(0,-2,1));root.addView(bar);add.setOnClickListener(v->addRow(""));save.setOnClickListener(v->save());String raw=p.getString(key,key.equals("card_whitelist")?"sistarbanc|Estado de cuenta":"");if(raw.trim().isEmpty())addRow("");else for(String s:raw.split("\\r?\\n"))addRow(s);setContentView(root);}
 EditText field(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(TEXT);e.setHintTextColor(MUTED);return e;}
 void addRow(String raw){String[] a=raw.split("\\|",-1);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(8),dp(8),dp(8),dp(8));card.setBackgroundColor(CARD);EditText from=field("Remitente",a.length>0?a[0]:""),sub=field("Asunto",a.length>1?a[1]:""),body=field("Texto opcional",a.length>2?a[2]:"");card.addView(from);card.addView(sub);card.addView(body);Button del=btn("Eliminar fila");card.addView(del);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));rows.addView(card,lp);del.setOnClickListener(v->rows.removeView(card));}
 void save(){ArrayList<String> out=new ArrayList<>();for(int i=0;i<rows.getChildCount();i++){LinearLayout c=(LinearLayout)rows.getChildAt(i);String a=((EditText)c.getChildAt(0)).getText().toString().trim(),b=((EditText)c.getChildAt(1)).getText().toString().trim(),d=((EditText)c.getChildAt(2)).getText().toString().trim();if(!a.isEmpty()||!b.isEmpty()||!d.isEmpty())out.add(a+"|"+b+"|"+d);}String s=android.text.TextUtils.join("\n",out);p.edit().putString(key,s).apply();setResult(RESULT_OK);finish();}
}
