plugins { id 'com.android.application' }

android {
    namespace 'com.pablo.controlgastos'
    compileSdk 35
    defaultConfig {
        applicationId 'com.pablo.controlgastos.secure'
        minSdk 26
        targetSdk 35
        versionCode 58
        versionName '1.8.36'
    }
    buildTypes {
        debug { debuggable false }
        release { minifyEnabled true; shrinkResources true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
}
dependencies { implementation 'net.sourceforge.jexcelapi:jxl:2.6.12' }
