package com.emanuel.runner;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public class GameView extends View {
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); private final Random random=new Random(); private final List<Obstacle> obstacles=new ArrayList<>(); private final SharedPreferences prefs;
 private float density,groundY,playerX,playerY,playerW,playerH,velocityY,speed,worldOffset; private boolean onGround=true,started=false,gameOver=false,ponyActive=false; private long lastFrame=0,nextSpawn=0,ponyUntil=0,ponyCooldownUntil=0; private int score=0,best=0;
 public GameView(Context c){super(c);density=getResources().getDisplayMetrics().density;prefs=c.getSharedPreferences("emanuel_runner",Context.MODE_PRIVATE);best=prefs.getInt("best",0);p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);}
 protected void onSizeChanged(int w,int h,int ow,int oh){groundY=h*.80f;playerW=Math.max(52*density,h*.11f);playerH=playerW*1.65f;playerX=w*.18f;speed=Math.max(260*density,w*.28f);reset(false);}
 private void reset(boolean go){obstacles.clear();score=0;velocityY=0;onGround=true;gameOver=false;started=go;ponyActive=false;ponyUntil=ponyCooldownUntil=0;playerY=groundY-playerH;nextSpawn=System.currentTimeMillis()+1200;lastFrame=0;speed=Math.max(260*density,getWidth()*.28f);invalidate();}
 protected void onDraw(Canvas c){long now=System.currentTimeMillis();if(lastFrame==0)lastFrame=now;float dt=Math.min(.033f,(now-lastFrame)/1000f);lastFrame=now;if(started&&!gameOver)update(dt,now);background(c);ground(c);for(Obstacle o:obstacles)obstacle(c,o);player(c,now);hud(c,now);if(!started)message(c,"EMANUEL AVENTURAS","Tocá para empezar");if(gameOver)message(c,"¡UY, EMANUEL!","Tocá para volver a jugar");postInvalidateOnAnimation();}
 private void update(float dt,long now){if(ponyActive&&now>=ponyUntil){ponyActive=false;ponyCooldownUntil=now+5000;}worldOffset+=speed*dt;speed+=4.2f*density*dt;score+=(int)(40*dt);velocityY+=1700*density*dt;playerY+=velocityY*dt;if(playerY>=groundY-playerH){playerY=groundY-playerH;velocityY=0;onGround=true;}if(now>=nextSpawn){Obstacle o=new Obstacle();o.type=random.nextInt(3);o.w=(42+random.nextInt(30))*density;o.h=(42+random.nextInt(38))*density;o.x=getWidth()+30*density;obstacles.add(o);nextSpawn=now+Math.max(720,980+random.nextInt(900)-score*2L);}Iterator<Obstacle> it=obstacles.iterator();while(it.hasNext()){Obstacle o=it.next();o.x-=speed*dt;if(o.x+o.w<0){it.remove();score+=10;}}
 RectF ph=ponyActive?new RectF(playerX-playerW*.15f,playerY+playerH*.35f,playerX+playerW*1.45f,playerY+playerH*.96f):new RectF(playerX+playerW*.18f,playerY+playerH*.1f,playerX+playerW*.82f,playerY+playerH*.96f);for(Obstacle o:obstacles){RectF h=new RectF(o.x+o.w*.08f,groundY-o.h+o.h*.08f,o.x+o.w*.92f,groundY);if(RectF.intersects(ph,h)&&!ponyActive){gameOver=true;if(score>best){best=score;prefs.edit().putInt("best",best).apply();}break;}}}
 private void jump(){if(onGround&&started&&!gameOver){velocityY=-(ponyActive?900:720)*density;onGround=false;}}
 private RectF ponyButton(){float r=45*density;return new RectF(getWidth()-2*r-20*density,getHeight()-2*r-20*density,getWidth()-20*density,getHeight()-20*density);}
 private void summon(long now){if(started&&!gameOver&&!ponyActive&&now>=ponyCooldownUntil){ponyActive=true;ponyUntil=now+10000;}}
 public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){long now=System.currentTimeMillis();if(!started){reset(true);jump();}else if(gameOver)reset(true);else if(ponyButton().contains(e.getX(),e.getY()))summon(now);else jump();return true;}return true;}
 private void background(Canvas c){c.drawColor(Color.rgb(150,215,250));p.setColor(Color.rgb(247,235,159));c.drawCircle(getWidth()*.83f,getHeight()*.16f,getHeight()*.07f,p);p.setColor(Color.rgb(245,250,252));float sh=-(worldOffset*.12f)%(getWidth()+280*density);for(int i=-1;i<4;i++){float x=sh+i*getWidth()*.42f,y=getHeight()*(.14f+(i&1)*.09f);c.drawCircle(x,y,28*density,p);c.drawCircle(x+30*density,y-10*density,34*density,p);}p.setColor(Color.rgb(117,190,133));float hs=-(worldOffset*.23f)%(340*density);for(int i=-1;i<7;i++)c.drawOval(new RectF(hs+i*340*density,groundY-150*density,hs+i*340*density+300*density,groundY+130*density),p);}
 private void ground(Canvas c){p.setColor(Color.rgb(106,184,84));c.drawRect(0,groundY-12*density,getWidth(),groundY+14*density,p);p.setColor(Color.rgb(151,104,64));c.drawRect(0,groundY+14*density,getWidth(),getHeight(),p);}
 private void player(Canvas c,long now){float x=playerX,y=playerY,w=playerW,h=playerH;if(ponyActive){float py=y+h*.57f;p.setColor(Color.rgb(45,47,50));c.drawOval(new RectF(x-w*.2f,py,x+w*1.45f,py+h*.34f),p);c.drawCircle(x+w*1.28f,py+h*.05f,w*.34f,p);p.setColor(Color.rgb(205,205,205));c.drawOval(new RectF(x+w*1.18f,py+h*.08f,x+w*1.48f,py+h*.22f),p);p.setColor(Color.rgb(45,47,50));for(int i=0;i<4;i++){float lx=x+w*(-.05f+i*.38f);c.drawRect(lx,py+h*.22f,lx+w*.13f,py+h*.48f,p);}y-=h*.12f;}
 p.setColor(Color.rgb(69,55,50));c.drawRoundRect(new RectF(x+w*.2f,y+h*.58f,x+w*.8f,y+h*.88f),w*.1f,w*.1f,p);c.drawRect(x+w*.22f,y+h*.78f,x+w*.46f,y+h*.97f,p);c.drawRect(x+w*.54f,y+h*.78f,x+w*.78f,y+h*.97f,p);p.setColor(Color.rgb(158,181,137));c.drawRoundRect(new RectF(x+w*.15f,y+h*.3f,x+w*.85f,y+h*.69f),w*.15f,w*.15f,p);p.setColor(Color.rgb(244,199,164));c.drawOval(new RectF(x+w*.23f,y+h*.02f,x+w*.77f,y+h*.34f),p);p.setColor(Color.rgb(86,63,49));c.drawArc(new RectF(x+w*.2f,y,x+w*.8f,y+h*.27f),190,160,true,p);p.setColor(Color.rgb(40,35,32));c.drawCircle(x+w*.39f,y+h*.17f,w*.027f,p);c.drawCircle(x+w*.61f,y+h*.17f,w*.027f,p);}
 private void obstacle(Canvas c,Obstacle o){float y=groundY-o.h;p.setColor(o.type==0?Color.rgb(177,113,62):o.type==1?Color.rgb(99,108,118):Color.rgb(208,83,63));c.drawRoundRect(new RectF(o.x,y,o.x+o.w,groundY),9*density,9*density,p);}
 private void hud(Canvas c,long now){p.setTextSize(22*density);p.setColor(Color.WHITE);c.drawText("PUNTOS "+score,20*density,35*density,p);RectF b=ponyButton();boolean cool=!ponyActive&&now<ponyCooldownUntil;p.setColor(ponyActive?Color.rgb(245,181,38):cool?Color.rgb(100,105,110):Color.rgb(55,145,75));c.drawOval(b,p);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(15*density);p.setColor(Color.WHITE);String s;if(ponyActive)s="PONY "+Math.max(0,(ponyUntil-now+999)/1000)+"s";else if(cool)s="PONY "+Math.max(0,(ponyCooldownUntil-now+999)/1000)+"s";else s="INVOCAR\nPONY";if(s.contains("\n")){c.drawText("INVOCAR",b.centerX(),b.centerY()-2*density,p);c.drawText("PONY",b.centerX(),b.centerY()+17*density,p);}else c.drawText(s,b.centerX(),b.centerY()+5*density,p);p.setTextAlign(Paint.Align.LEFT);if(ponyActive){float left=getWidth()*.3f,right=getWidth()*.7f,top=20*density;float f=Math.max(0,(ponyUntil-now)/10000f);p.setColor(Color.argb(160,20,20,20));c.drawRoundRect(new RectF(left,top,right,top+14*density),7*density,7*density,p);p.setColor(Color.rgb(255,190,35));c.drawRoundRect(new RectF(left,top,left+(right-left)*f,top+14*density),7*density,7*density,p);}}
 private void message(Canvas c,String a,String b){p.setColor(Color.argb(165,20,40,55));c.drawRoundRect(new RectF(getWidth()*.25f,getHeight()*.24f,getWidth()*.75f,getHeight()*.62f),25*density,25*density,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(getHeight()*.08f);c.drawText(a,getWidth()/2f,getHeight()*.39f,p);p.setTextSize(getHeight()*.04f);c.drawText(b,getWidth()/2f,getHeight()*.52f,p);p.setTextAlign(Paint.Align.LEFT);}
 private static class Obstacle{float x,w,h;int type;}
}
