package com.emanuel.runner;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public class GameView extends View {
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG); private final Random random=new Random(); private final List<Enemy> enemies=new ArrayList<>(); private final List<Bark> barks=new ArrayList<>(); private final SharedPreferences prefs;
 private float density,groundY,playerX,playerY,playerW,playerH,velocityY,speed,worldOffset; private boolean onGround=true,started=false,gameOver=false,ponyActive=false,kicking=false; private long lastFrame=0,nextSpawn=0,ponyUntil=0,ponyCooldownUntil=0,invulnerableUntil=0,kickUntil=0,kickCooldownUntil=0,barkCooldownUntil=0; private int score=0,best=0,life=100;
 public GameView(Context c){super(c);density=getResources().getDisplayMetrics().density;prefs=c.getSharedPreferences("emanuel_runner",Context.MODE_PRIVATE);best=prefs.getInt("best",0);p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);}
 protected void onSizeChanged(int w,int h,int ow,int oh){groundY=h*.80f;playerW=Math.max(52*density,h*.11f);playerH=playerW*1.65f;playerX=w*.18f;speed=Math.max(260*density,w*.28f);reset(false);}
 private void reset(boolean go){enemies.clear();barks.clear();score=0;life=100;velocityY=0;onGround=true;gameOver=false;started=go;ponyActive=false;kicking=false;ponyUntil=ponyCooldownUntil=invulnerableUntil=kickUntil=kickCooldownUntil=barkCooldownUntil=0;playerY=groundY-playerH;nextSpawn=System.currentTimeMillis()+1200;lastFrame=0;speed=Math.max(260*density,getWidth()*.28f);invalidate();}
 protected void onDraw(Canvas c){long now=System.currentTimeMillis();if(lastFrame==0)lastFrame=now;float dt=Math.min(.033f,(now-lastFrame)/1000f);lastFrame=now;if(started&&!gameOver)update(dt,now);background(c);ground(c);for(Enemy e:enemies)enemy(c,e);for(Bark b:barks)drawBark(c,b);player(c,now);hud(c,now);if(!started)message(c,"EMANUEL AVENTURAS","Tocá para empezar");if(gameOver)message(c,"SIN VIDA","Tocá para volver a jugar");postInvalidateOnAnimation();}
 private void update(float dt,long now){if(ponyActive&&now>=ponyUntil){ponyActive=false;ponyCooldownUntil=now+5000;}if(kicking&&now>=kickUntil)kicking=false;worldOffset+=speed*dt;speed+=4.0f*density*dt;score+=(int)(40*dt);velocityY+=1700*density*dt;playerY+=velocityY*dt;if(playerY>=groundY-playerH){playerY=groundY-playerH;velocityY=0;onGround=true;}
 if(now>=nextSpawn){Enemy e=new Enemy();e.type=random.nextInt(3);e.w=(42+random.nextInt(28))*density;e.h=(45+random.nextInt(35))*density;e.x=getWidth()+30*density;e.alive=true;enemies.add(e);nextSpawn=now+Math.max(700,1050+random.nextInt(750)-score*2L);}for(Bark b:barks)b.x+=760*density*dt;
 Iterator<Bark> bi=barks.iterator();while(bi.hasNext())if(bi.next().x>getWidth()+100*density)bi.remove();
 Iterator<Enemy> it=enemies.iterator();while(it.hasNext()){Enemy e=it.next();e.x-=speed*dt;if(!e.alive||e.x+e.w<0){it.remove();continue;}RectF eh=new RectF(e.x+e.w*.08f,groundY-e.h+e.h*.08f,e.x+e.w*.92f,groundY);
  boolean killed=false;for(Bark b:barks){RectF bh=new RectF(b.x,b.y-b.h/2,b.x+b.w,b.y+b.h/2);if(RectF.intersects(bh,eh)){killed=true;break;}}if(killed){e.alive=false;score+=35;continue;}
  if(kicking&&!ponyActive){RectF kh=new RectF(playerX+playerW*.65f,playerY+playerH*.35f,playerX+playerW*1.45f,playerY+playerH*.82f);if(RectF.intersects(kh,eh)){e.alive=false;score+=25;continue;}}
  RectF ph=playerHit();if(RectF.intersects(ph,eh)){float playerBottom=playerY+playerH*.96f;boolean stomp=!ponyActive&&velocityY>0&&playerBottom<groundY-e.h+e.h*.55f;if(stomp){e.alive=false;velocityY=-420*density;onGround=false;score+=30;}else if(now>=invulnerableUntil){life=Math.max(0,life-10);invulnerableUntil=now+1100;if(life<=0){gameOver=true;if(score>best){best=score;prefs.edit().putInt("best",best).apply();}}}}
 }
 }
 private RectF playerHit(){return ponyActive?new RectF(playerX-playerW*.1f,playerY+playerH*.28f,playerX+playerW*1.42f,playerY+playerH*.96f):new RectF(playerX+playerW*.18f,playerY+playerH*.1f,playerX+playerW*.82f,playerY+playerH*.96f);}
 private void jump(){if(onGround&&started&&!gameOver){velocityY=-(ponyActive?900:720)*density;onGround=false;}}
 private RectF ponyButton(){float r=43*density;return new RectF(getWidth()-2*r-18*density,getHeight()-2*r-18*density,getWidth()-18*density,getHeight()-18*density);}
 private RectF attackButton(){float r=43*density;return new RectF(getWidth()-4*r-32*density,getHeight()-2*r-18*density,getWidth()-2*r-32*density,getHeight()-18*density);}
 private void summon(long now){if(started&&!gameOver&&!ponyActive&&now>=ponyCooldownUntil){ponyActive=true;ponyUntil=now+10000;}}
 private void attack(long now){if(gameOver||!started)return;if(ponyActive){if(now>=barkCooldownUntil){Bark b=new Bark();b.x=playerX+playerW*1.25f;b.y=playerY+playerH*.62f;b.w=130*density;b.h=80*density;barks.add(b);barkCooldownUntil=now+850;}}else if(now>=kickCooldownUntil){kicking=true;kickUntil=now+260;kickCooldownUntil=now+520;}}
 public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){long now=System.currentTimeMillis();if(!started){reset(true);jump();}else if(gameOver)reset(true);else if(ponyButton().contains(e.getX(),e.getY()))summon(now);else if(attackButton().contains(e.getX(),e.getY()))attack(now);else jump();return true;}return true;}
 private void background(Canvas c){c.drawColor(Color.rgb(150,215,250));p.setColor(Color.rgb(247,235,159));c.drawCircle(getWidth()*.83f,getHeight()*.16f,getHeight()*.07f,p);p.setColor(Color.rgb(245,250,252));float sh=-(worldOffset*.12f)%(getWidth()+280*density);for(int i=-1;i<4;i++){float x=sh+i*getWidth()*.42f,y=getHeight()*(.14f+(i&1)*.09f);c.drawCircle(x,y,28*density,p);c.drawCircle(x+30*density,y-10*density,34*density,p);}p.setColor(Color.rgb(117,190,133));float hs=-(worldOffset*.23f)%(340*density);for(int i=-1;i<7;i++)c.drawOval(new RectF(hs+i*340*density,groundY-150*density,hs+i*340*density+300*density,groundY+130*density),p);}
 private void ground(Canvas c){p.setColor(Color.rgb(106,184,84));c.drawRect(0,groundY-12*density,getWidth(),groundY+14*density,p);p.setColor(Color.rgb(151,104,64));c.drawRect(0,groundY+14*density,getWidth(),getHeight(),p);}
 private void player(Canvas c,long now){float x=playerX,y=playerY,w=playerW,h=playerH;boolean blink=now<invulnerableUntil&&((now/90)%2==0);if(blink)return;if(ponyActive){float py=y+h*.57f;p.setColor(Color.rgb(45,47,50));c.drawOval(new RectF(x-w*.2f,py,x+w*1.45f,py+h*.34f),p);c.drawCircle(x+w*1.28f,py+h*.05f,w*.34f,p);p.setColor(Color.rgb(205,205,205));c.drawOval(new RectF(x+w*1.18f,py+h*.08f,x+w*1.48f,py+h*.22f),p);p.setColor(Color.rgb(45,47,50));for(int i=0;i<4;i++){float lx=x+w*(-.05f+i*.38f);c.drawRect(lx,py+h*.22f,lx+w*.13f,py+h*.48f,p);}y-=h*.12f;}
 p.setColor(Color.rgb(69,55,50));c.drawRoundRect(new RectF(x+w*.2f,y+h*.58f,x+w*.8f,y+h*.88f),w*.1f,w*.1f,p);float leg= kicking&&!ponyActive?w*.55f:0;c.drawRect(x+w*.22f,y+h*.78f,x+w*.46f+leg,y+h*.97f,p);c.drawRect(x+w*.54f,y+h*.78f,x+w*.78f,y+h*.97f,p);p.setColor(Color.rgb(158,181,137));c.drawRoundRect(new RectF(x+w*.15f,y+h*.3f,x+w*.85f,y+h*.69f),w*.15f,w*.15f,p);p.setColor(Color.rgb(244,199,164));c.drawOval(new RectF(x+w*.23f,y+h*.02f,x+w*.77f,y+h*.34f),p);p.setColor(Color.rgb(86,63,49));c.drawArc(new RectF(x+w*.2f,y,x+w*.8f,y+h*.27f),190,160,true,p);p.setColor(Color.rgb(40,35,32));c.drawCircle(x+w*.39f,y+h*.17f,w*.027f,p);c.drawCircle(x+w*.61f,y+h*.17f,w*.027f,p);}
 private void enemy(Canvas c,Enemy e){float y=groundY-e.h;p.setColor(e.type==0?Color.rgb(177,70,58):e.type==1?Color.rgb(92,86,170):Color.rgb(70,120,70));c.drawOval(new RectF(e.x,y,e.x+e.w,groundY),p);p.setColor(Color.WHITE);c.drawCircle(e.x+e.w*.35f,y+e.h*.35f,e.w*.08f,p);c.drawCircle(e.x+e.w*.65f,y+e.h*.35f,e.w*.08f,p);p.setColor(Color.BLACK);c.drawCircle(e.x+e.w*.35f,y+e.h*.35f,e.w*.035f,p);c.drawCircle(e.x+e.w*.65f,y+e.h*.35f,e.w*.035f,p);}
 private void drawBark(Canvas c,Bark b){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5*density);p.setColor(Color.rgb(255,225,80));c.drawArc(new RectF(b.x-b.w*.15f,b.y-b.h*.45f,b.x+b.w,b.y+b.h*.45f),-55,110,false,p);c.drawArc(new RectF(b.x+b.w*.15f,b.y-b.h*.6f,b.x+b.w*1.25f,b.y+b.h*.6f),-55,110,false,p);p.setStyle(Paint.Style.FILL);}
 private void hud(Canvas c,long now){p.setColor(Color.WHITE);p.setTextSize(19*density);c.drawText("PUNTOS "+score,18*density,30*density,p);float lx=18*density,ly=42*density,lw=getWidth()*.28f,lh=16*density;p.setColor(Color.argb(170,25,25,25));c.drawRoundRect(new RectF(lx,ly,lx+lw,ly+lh),8*density,8*density,p);p.setColor(life>50?Color.rgb(55,190,75):life>20?Color.rgb(245,175,40):Color.rgb(220,55,55));c.drawRoundRect(new RectF(lx,ly,lx+lw*life/100f,ly+lh),8*density,8*density,p);p.setColor(Color.WHITE);p.setTextSize(13*density);c.drawText("VIDA "+life+"/100",lx+6*density,ly+13*density,p);
 drawButton(c,ponyButton(),ponyActive?"PONY "+Math.max(0,(ponyUntil-now+999)/1000)+"s":now<ponyCooldownUntil?"PONY "+Math.max(0,(ponyCooldownUntil-now+999)/1000)+"s":"INVOCAR\nPONY",ponyActive?Color.rgb(245,181,38):now<ponyCooldownUntil?Color.rgb(105,105,110):Color.rgb(55,145,75));drawButton(c,attackButton(),ponyActive?(now<barkCooldownUntil?"LADRIDO\nRECARGA":"MEGA\nLADRIDO"):(now<kickCooldownUntil?"PATADA\nRECARGA":"PATADA"),ponyActive?Color.rgb(65,130,230):Color.rgb(220,95,45));}
 private void drawButton(Canvas c,RectF b,String text,int color){p.setColor(color);c.drawOval(b,p);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(13*density);p.setColor(Color.WHITE);String[] lines=text.split("\\n");if(lines.length==1)c.drawText(lines[0],b.centerX(),b.centerY()+5*density,p);else{c.drawText(lines[0],b.centerX(),b.centerY()-2*density,p);c.drawText(lines[1],b.centerX(),b.centerY()+16*density,p);}p.setTextAlign(Paint.Align.LEFT);}
 private void message(Canvas c,String a,String b){p.setColor(Color.argb(165,20,40,55));c.drawRoundRect(new RectF(getWidth()*.25f,getHeight()*.24f,getWidth()*.75f,getHeight()*.62f),25*density,25*density,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(getHeight()*.075f);c.drawText(a,getWidth()/2f,getHeight()*.39f,p);p.setTextSize(getHeight()*.04f);c.drawText(b,getWidth()/2f,getHeight()*.52f,p);p.setTextAlign(Paint.Align.LEFT);}
 private static class Enemy{float x,w,h;int type;boolean alive;} private static class Bark{float x,y,w,h;}
}
