from pathlib import Path
import re
p=Path('app/src/main/java/com/pablo/controlgastos/AnalyticsActivity.java')
s=p.read_text()
old='LinearLayout controls=new LinearLayout(this);controls.setPadding(dp(12),dp(4),dp(12),dp(4));periodBtn=btn(periodLabel());periodBtn.setOnClickListener(v->choosePeriod());Button mode=btn("Mes / Año");mode.setOnClickListener(v->{annual=!annual;periodBtn.setText(periodLabel());renderActive();});controls.addView(periodBtn,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(105),dp(46));mp.setMargins(dp(8),0,0,0);controls.addView(mode,mp);root.addView(controls);'
new='LinearLayout controls=new LinearLayout(this);controls.setPadding(dp(12),dp(4),dp(12),dp(4));Button prev=btn("‹"),next=btn("›");periodBtn=btn(periodLabel());periodBtn.setOnClickListener(v->choosePeriod());prev.setOnClickListener(v->{selected.add(annual?Calendar.YEAR:Calendar.MONTH,-1);periodBtn.setText(periodLabel());renderActive();});next.setOnClickListener(v->{selected.add(annual?Calendar.YEAR:Calendar.MONTH,1);periodBtn.setText(periodLabel());renderActive();});Button mode=btn("Mes / Año");mode.setOnClickListener(v->{annual=!annual;periodBtn.setText(periodLabel());renderActive();});controls.addView(prev,new LinearLayout.LayoutParams(dp(44),dp(46)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(46),1);pp.setMargins(dp(5),0,dp(5),0);controls.addView(periodBtn,pp);controls.addView(next,new LinearLayout.LayoutParams(dp(44),dp(46)));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(96),dp(46));mp.setMargins(dp(6),0,0,0);controls.addView(mode,mp);root.addView(controls);'
assert old in s
s=s.replace(old,new,1)
old='private void choosePeriod(){DatePickerDialog d=new DatePickerDialog(this,(v,y,m,day)->{selected.set(y,m,1);periodBtn.setText(periodLabel());renderActive();},selected.get(Calendar.YEAR),selected.get(Calendar.MONTH),1);d.setTitle(annual?"Elegí año":"Elegí mes");d.show();}'
new='private void choosePeriod(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),dp(8),dp(18),0);String[] months={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};Spinner ms=new Spinner(this);ms.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,months));ms.setSelection(selected.get(Calendar.MONTH));NumberPicker yp=new NumberPicker(this);int cy=Calendar.getInstance().get(Calendar.YEAR);yp.setMinValue(2000);yp.setMaxValue(cy+10);yp.setValue(selected.get(Calendar.YEAR));yp.setWrapSelectorWheel(false);if(!annual){f.addView(tv("Mes",14,MUTED));f.addView(ms);}f.addView(tv("Año",14,MUTED));f.addView(yp);new AlertDialog.Builder(this).setTitle(annual?"Elegir año":"Elegir mes y año").setView(f).setPositiveButton("Ver",(d,w)->{selected.set(yp.getValue(),annual?selected.get(Calendar.MONTH):ms.getSelectedItemPosition(),1,0,0,0);selected.set(Calendar.MILLISECOND,0);periodBtn.setText(periodLabel());renderActive();}).setNegativeButton("Cancelar",null).show();}'
assert old in s
s=s.replace(old,new,1)
anchor=' private LinkedHashMap<String,Double> categoryMap(Calendar p,boolean year)'
helpers=' private double[] financialTotals(Calendar p,boolean year){double in=0,out=0;for(Object[]r:rowsFor(p,year)){if(!"UYU".equals(r[2]))continue;if("INGRESO".equals(r[0]))in+=(Double)r[1];else if("GASTO".equals(r[0]))out+=(Double)r[1];}return new double[]{in,out};}\n private void addFinancialSummary(){double[] x=financialTotals(selected,annual);double bal=x[0]-x[1];int bc=bal>=0?Color.rgb(55,170,105):Color.rgb(220,80,80);String label=bal>=0?"Ahorro":"Déficit";TextView t=tv("Ingresos: $ "+money.format(x[0])+"   ·   Gastos: $ "+money.format(x[1])+"\\n"+label+": $ "+money.format(Math.abs(bal)),17,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable g=bg(CARD,14);g.setStroke(dp(1),bc);t.setBackground(g);t.setPadding(dp(14),dp(11),dp(14),dp(11));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));content.addView(t,lp);}\n private String merchantCategory(String merchant,Calendar p,boolean year){HashMap<String,Double> totals=new HashMap<>();for(Object[]r:rowsFor(p,year)){if(!"GASTO".equals(r[0])||!"UYU".equals(r[2]))continue;if(!merchant.equals(merchantKey((String)r[4])))continue;String cat=categoryKey((String)r[3],(String)r[4]);totals.put(cat,totals.getOrDefault(cat,0.0)+(Double)r[1]);}String best="Otros";double max=-1;for(Map.Entry<String,Double>e:totals.entrySet())if(e.getValue()>max){max=e.getValue();best=e.getKey();}return best;}\n'
assert anchor in s
s=s.replace(anchor,helpers+anchor,1)
s=s.replace('total+=e.getValue();}addTotal(total);if(!items.isEmpty()){DonutView','total+=e.getValue();}addFinancialSummary();addTotal(total);if(!items.isEmpty()){DonutView',1)
old='if(ix>=12)break;int c=CategoryPrefs.PALETTE[ix%CategoryPrefs.PALETTE.length];items.add(new Item(e.getKey(),e.getValue(),c));total+=e.getValue();ix++;}addTotal(total);'
new='if(ix>=12)break;String mc=merchantCategory(e.getKey(),selected,annual);int c=CategoryPrefs.color(this,mc);items.add(new Item(e.getKey(),e.getValue(),c));total+=e.getValue();ix++;}addFinancialSummary();addTotal(total);'
assert old in s
s=s.replace(old,new,1)
old='LineView v=new LineView(this,months);content.addView(v,new LinearLayout.LayoutParams(-1,dp(280)));content.addView(tv("La línea usa el gasto total mensual. Elegí otro mes arriba para mover la ventana de 12 meses.",14,MUTED));'
new='double max=0;for(Item it:months)max=Math.max(max,it.value);double step=niceStep(max/4.0);double top=step<=0?1:Math.ceil(max/step)*step;LinearLayout graph=new LinearLayout(this);graph.setGravity(Gravity.CENTER_VERTICAL);TextView scale=tv(scaleText(top),11,MUTED);scale.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);graph.addView(scale,new LinearLayout.LayoutParams(dp(78),dp(280)));LineView v=new LineView(this,months);graph.addView(v,new LinearLayout.LayoutParams(0,dp(280),1));content.addView(graph,new LinearLayout.LayoutParams(-1,dp(280)));content.addView(tv("Escala en pesos uruguayos a la izquierda. La línea usa el gasto total mensual.",14,MUTED));'
assert old in s
s=s.replace(old,new,1)
anchor=' private void showCompare(){'
helper=' private double niceStep(double x){if(x<=0)return 1;double p=Math.pow(10,Math.floor(Math.log10(x)));double n=x/p;double k=n<=1?1:n<=2?2:n<=5?5:10;return k*p;} private String shortMoney(double v){if(v>=1000000)return "$"+new DecimalFormat("0.#").format(v/1000000)+"M";if(v>=1000)return "$"+new DecimalFormat("0.#").format(v/1000)+"k";return "$"+new DecimalFormat("0").format(v);} private String scaleText(double top){StringBuilder b=new StringBuilder();for(int i=4;i>=0;i--){b.append(shortMoney(top*i/4.0));if(i>0)b.append("\\n\\n\\n");}return b.toString();}\n'
assert anchor in s
s=s.replace(anchor,helper+anchor,1)
p.write_text(s)
g=Path('app/build.gradle');t=g.read_text();t=re.sub(r'versionCode\s+\d+','versionCode 52',t,1);t=re.sub(r"versionName\s+'[^']+'","versionName '1.8.30'",t,1);g.write_text(t)
